-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity posit_comp_add is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in1 : IN STD_LOGIC_VECTOR (15 downto 0);
    in2 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of posit_comp_add is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "posit_comp_add_posit_comp_add,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=5000.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=36.910150,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=1153,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv14_3FFF : STD_LOGIC_VECTOR (13 downto 0) := "11111111111111";
    constant ap_const_lv13_1FFF : STD_LOGIC_VECTOR (12 downto 0) := "1111111111111";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv15_7FFF : STD_LOGIC_VECTOR (14 downto 0) := "111111111111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal val_V_119_fu_226_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_120_fu_230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_fu_218_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_210_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ext_fu_254_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1527_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_274_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_fu_282_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_5_fu_298_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_fu_304_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lower_V_fu_314_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln359_1_fu_324_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal comp_V_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_3_fu_332_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_6_fu_340_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_1_fu_348_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal lower_V_1_fu_358_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln359_2_fu_368_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal comp_V_1_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_4_fu_376_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_7_fu_384_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_121_fu_392_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lower_V_2_fu_402_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln359_3_fu_412_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal comp_V_2_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_5_fu_420_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_8_fu_428_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_6_fu_436_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln312_fu_450_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln422_fu_462_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_5_fu_454_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal top_is_leading_V_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_6_fu_474_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal val_V_122_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal opt1_V_6_fu_466_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln356_fu_290_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_fu_492_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ret_9_fu_500_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal xor_ln939_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln217_1_fu_506_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln359_4_fu_526_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal es_V_fu_540_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln359_5_fu_550_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_3_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_10_fu_534_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_11_fu_558_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_4_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fraction_V_fu_510_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal val_V_123_fu_596_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_124_fu_600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_fu_588_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_12_fu_606_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_fu_580_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_2_fu_612_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ext_1_fu_624_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1527_1_fu_632_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_644_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_6_fu_652_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_15_fu_668_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_3_fu_674_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lower_V_3_fu_684_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln359_7_fu_694_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal comp_V_3_fu_688_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_10_fu_702_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_16_fu_710_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_4_fu_718_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal lower_V_4_fu_728_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln359_8_fu_738_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal comp_V_4_fu_732_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_11_fu_746_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_17_fu_754_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_fu_762_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lower_V_5_fu_772_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln359_9_fu_782_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal comp_V_5_fu_776_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_12_fu_790_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_18_fu_798_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_13_fu_806_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln312_1_fu_820_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln422_1_fu_832_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_7_fu_824_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal top_is_leading_V_1_fu_814_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_13_fu_844_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal val_V_125_fu_856_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal opt1_V_7_fu_836_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln356_1_fu_660_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_2_fu_862_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ret_19_fu_870_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal xor_ln939_3_fu_884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_3_fu_890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln217_2_fu_876_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln359_10_fu_896_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal es_V_1_fu_910_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln359_11_fu_920_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_13_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_20_fu_904_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_21_fu_928_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_14_fu_638_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fraction_V_1_fu_880_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal and_ln_fu_950_p6 : STD_LOGIC_VECTOR (20 downto 0);
    signal and_ln1528_1_fu_970_p6 : STD_LOGIC_VECTOR (20 downto 0);
    signal subExpOp2_V_fu_1004_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal opt1_V_8_fu_1012_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal val_V_126_fu_1026_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_5_fu_1020_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_22_fu_1032_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_4_fu_964_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal control_V_fu_1038_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lessSignificantSignificand_V_fu_994_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal mostSignificantSignificand_V_fu_984_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln422_2_fu_1060_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln422_3_fu_1068_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln422_4_fu_1076_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shiftValue_V_fu_1092_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal shift_weights_will_zero_V_fu_1106_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_15_fu_1098_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal res_3_fu_1084_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_16_fu_1128_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal shift_high_V_fu_1142_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_17_fu_1156_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln312_fu_1138_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal zext_ln978_1_fu_1164_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal r_7_fu_1168_p2 : STD_LOGIC_VECTOR (38 downto 0);
    signal shifted_out_V_fu_1184_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal shifted_V_fu_1174_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Result_18_fu_1194_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal shift_low_V_fu_1152_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln978_fu_1204_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal zext_ln978_2_fu_1208_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal lshr_ln978_2_fu_1212_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal shifted_out_V_1_fu_1228_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_6_fu_1116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_12_fu_1238_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal shifted_V_3_fu_1218_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1049_fu_1122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_127_fu_1188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_23_fu_1254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1528_fu_1260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_8_fu_1232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_4_fu_1246_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln422_fu_1044_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln422_1_fu_1052_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shiftedTop_V_fu_1272_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Result_20_fu_1294_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_19_fu_1286_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal addRes_V_fu_1302_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal usefulRes_V_fu_1316_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal guards_V_fu_1282_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ext_2_fu_1328_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_22_fu_1320_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln359_13_fu_1336_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal ret_25_fu_1344_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal upper_V_6_fu_1350_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lower_V_6_fu_1360_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln359_14_fu_1370_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal comp_V_6_fu_1364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_23_fu_1378_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal ret_26_fu_1386_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal upper_V_7_fu_1394_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal lower_V_7_fu_1404_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln359_15_fu_1414_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal comp_V_7_fu_1408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_24_fu_1422_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal ret_27_fu_1430_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal val_V_128_fu_1438_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lower_V_8_fu_1448_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln359_16_fu_1458_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal comp_V_8_fu_1452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_25_fu_1466_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal ret_28_fu_1474_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_fu_1482_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal lower_V_9_fu_1496_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_21_fu_1308_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_26_fu_1500_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal top_is_leading_V_2_fu_1490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal opt1_V_fu_1508_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln1529_fu_1536_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln1529_fu_1528_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal xor_ln1529_1_fu_1550_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln1529_1_fu_1540_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_24_fu_1266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_30_fu_1564_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_27_fu_1516_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln1526_fu_1580_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln1526_fu_1576_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_7_fu_564_p7 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_Result_14_fu_934_p7 : STD_LOGIC_VECTOR (20 downto 0);
    signal or_ln1528_3_fu_1592_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal ret_29_fu_1544_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Val2_23_fu_1586_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal es_wo_xor_V_fu_1624_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_21_fu_1642_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_34_fu_1650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal low_k_V_fu_1664_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_30_fu_1634_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_9_fu_1674_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal res_5_fu_1656_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_31_fu_1688_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_33_fu_1628_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal val_V_129_fu_1614_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_28_fu_1556_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_32_fu_1696_p7 : STD_LOGIC_VECTOR (28 downto 0);
    signal opt1_V_9_fu_1680_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal shift_high_V_1_fu_1716_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_33_fu_1730_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln312_1_fu_1712_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal zext_ln978_fu_1738_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal r_10_fu_1742_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal shifted_out_V_2_fu_1758_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal shifted_V_4_fu_1748_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_34_fu_1768_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal shift_low_V_1_fu_1726_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln978_1_fu_1778_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln978_3_fu_1782_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal lshr_ln978_fu_1786_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_out_V_3_fu_1792_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_11_fu_1796_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_130_fu_1762_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_31_fu_1570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_36_fu_1826_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1528_5_fu_1834_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_35_fu_1802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_35_fu_1808_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_36_fu_1840_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_37_fu_1846_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal unroundedResult_V_fu_1816_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln217_fu_1852_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal roundedResult_V_fu_1856_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ret_32_fu_1598_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_29_fu_1606_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1527_fu_1878_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_38_fu_1884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_39_fu_1890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_38_fu_1870_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_37_fu_1862_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin



    addRes_V_fu_1302_p2 <= std_logic_vector(unsigned(p_Result_20_fu_1294_p3) + unsigned(p_Result_19_fu_1286_p3));
    add_ln1526_fu_1580_p2 <= std_logic_vector(unsigned(select_ln422_2_fu_1060_p3) + unsigned(ap_const_lv7_1));
    and_ln1528_1_fu_970_p6 <= ((((ret_3_fu_248_p2 & ap_const_lv7_0) & p_Result_s_fu_210_p3) & ret_4_fu_268_p2) & ap_const_lv11_0);
    and_ln_fu_950_p6 <= ((((ret_13_fu_618_p2 & ap_const_lv7_0) & p_Result_8_fu_580_p3) & ret_14_fu_638_p2) & ap_const_lv11_0);
    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_ready <= ap_start;
    ap_return <= 
        p_Result_38_fu_1870_p3 when (ret_39_fu_1890_p2(0) = '1') else 
        p_Result_37_fu_1862_p3;
    comp_V_1_fu_362_p2 <= "1" when (upper_V_1_fu_348_p4 = ap_const_lv4_0) else "0";
    comp_V_2_fu_406_p2 <= "1" when (val_V_121_fu_392_p4 = ap_const_lv2_0) else "0";
    comp_V_3_fu_688_p2 <= "1" when (upper_V_3_fu_674_p4 = ap_const_lv8_0) else "0";
    comp_V_4_fu_732_p2 <= "1" when (upper_V_4_fu_718_p4 = ap_const_lv4_0) else "0";
    comp_V_5_fu_776_p2 <= "1" when (val_V_fu_762_p4 = ap_const_lv2_0) else "0";
    comp_V_6_fu_1364_p2 <= "1" when (upper_V_6_fu_1350_p4 = ap_const_lv8_0) else "0";
    comp_V_7_fu_1408_p2 <= "1" when (upper_V_7_fu_1394_p4 = ap_const_lv4_0) else "0";
    comp_V_8_fu_1452_p2 <= "1" when (val_V_128_fu_1438_p4 = ap_const_lv2_0) else "0";
    comp_V_fu_318_p2 <= "1" when (upper_V_fu_304_p4 = ap_const_lv8_0) else "0";
    control_V_fu_1038_p2 <= (ret_22_fu_1032_p2 or r_4_fu_964_p2);
    es_V_1_fu_910_p4 <= ret_19_fu_870_p2(12 downto 11);
    es_V_fu_540_p4 <= ret_9_fu_500_p2(12 downto 11);
    es_wo_xor_V_fu_1624_p1 <= p_Val2_23_fu_1586_p2(2 - 1 downto 0);
    ext_1_fu_624_p3 <= in2(15 downto 15);
    ext_2_fu_1328_p3 <= addRes_V_fu_1302_p2(13 downto 13);
    ext_fu_254_p3 <= in1(15 downto 15);
    fraction_V_1_fu_880_p1 <= ret_19_fu_870_p2(11 - 1 downto 0);
    fraction_V_fu_510_p1 <= ret_9_fu_500_p2(11 - 1 downto 0);
    guards_V_fu_1282_p1 <= res_4_fu_1246_p3(2 - 1 downto 0);
    icmp_ln1049_fu_1122_p2 <= "0" when (p_Result_15_fu_1098_p3 = ap_const_lv15_0) else "1";
    lessSignificantSignificand_V_fu_994_p4 <= ((p_Result_s_fu_210_p3 & ret_4_fu_268_p2) & fraction_V_fu_510_p1);
    low_k_V_fu_1664_p4 <= p_Val2_23_fu_1586_p2(5 downto 2);
    lower_V_1_fu_358_p1 <= ret_6_fu_340_p3(10 - 1 downto 0);
    lower_V_2_fu_402_p1 <= ret_7_fu_384_p3(12 - 1 downto 0);
    lower_V_3_fu_684_p1 <= ret_15_fu_668_p2(6 - 1 downto 0);
    lower_V_4_fu_728_p1 <= ret_16_fu_710_p3(10 - 1 downto 0);
    lower_V_5_fu_772_p1 <= ret_17_fu_754_p3(12 - 1 downto 0);
    lower_V_6_fu_1360_p1 <= ret_25_fu_1344_p2(7 - 1 downto 0);
    lower_V_7_fu_1404_p1 <= ret_26_fu_1386_p3(11 - 1 downto 0);
    lower_V_8_fu_1448_p1 <= ret_27_fu_1430_p3(13 - 1 downto 0);
    lower_V_9_fu_1496_p1 <= ret_28_fu_1474_p3(14 - 1 downto 0);
    lower_V_fu_314_p1 <= ret_5_fu_298_p2(6 - 1 downto 0);
    lshr_ln978_2_fu_1212_p2 <= std_logic_vector(shift_right(unsigned(sext_ln978_fu_1204_p1),to_integer(unsigned('0' & zext_ln978_2_fu_1208_p1(21-1 downto 0)))));
    lshr_ln978_fu_1786_p2 <= std_logic_vector(shift_right(unsigned(sext_ln978_1_fu_1778_p1),to_integer(unsigned('0' & zext_ln978_3_fu_1782_p1(22-1 downto 0)))));
    mostSignificantSignificand_V_fu_984_p4 <= ((p_Result_8_fu_580_p3 & ret_14_fu_638_p2) & fraction_V_1_fu_880_p1);
    opt1_V_6_fu_466_p3 <= 
        trunc_ln422_fu_462_p1 when (tmp_6_fu_436_p3(0) = '1') else 
        tmp_5_fu_454_p3;
    opt1_V_7_fu_836_p3 <= 
        trunc_ln422_1_fu_832_p1 when (tmp_13_fu_806_p3(0) = '1') else 
        tmp_7_fu_824_p3;
    opt1_V_8_fu_1012_p3 <= (ret_20_fu_904_p2 & ret_21_fu_928_p2);
    opt1_V_9_fu_1680_p3 <= 
        r_9_fu_1674_p2 when (p_Result_30_fu_1634_p3(0) = '1') else 
        low_k_V_fu_1664_p4;
    opt1_V_fu_1508_p3 <= 
        ret_28_fu_1474_p3 when (tmp_fu_1482_p3(0) = '1') else 
        p_Result_26_fu_1500_p3;
    or_ln1527_fu_1878_p2 <= (p_Result_29_fu_1606_p3 or p_Result_21_fu_1308_p3);
    or_ln1528_3_fu_1592_p2 <= (p_Result_7_fu_564_p7 or p_Result_14_fu_934_p7);
    or_ln1528_5_fu_1834_p2 <= (ret_31_fu_1570_p2 or p_Result_36_fu_1826_p3);
    or_ln1528_fu_1260_p2 <= (val_V_127_fu_1188_p2 or ret_23_fu_1254_p2);
    p_Result_10_fu_702_p3 <= (lower_V_3_fu_684_p1 & select_ln359_7_fu_694_p3);
    p_Result_11_fu_746_p3 <= (lower_V_4_fu_728_p1 & select_ln359_8_fu_738_p3);
    p_Result_12_fu_790_p3 <= (lower_V_5_fu_772_p1 & select_ln359_9_fu_782_p3);
    p_Result_13_fu_844_p5 <= (((comp_V_3_fu_688_p2 & comp_V_4_fu_732_p2) & comp_V_5_fu_776_p2) & top_is_leading_V_1_fu_814_p2);
    p_Result_14_fu_934_p7 <= (((((ret_13_fu_618_p2 & ret_20_fu_904_p2) & ret_21_fu_928_p2) & p_Result_8_fu_580_p3) & ret_14_fu_638_p2) & fraction_V_1_fu_880_p1);
    p_Result_15_fu_1098_p3 <= (select_ln422_4_fu_1076_p3 & ap_const_lv2_0);
    p_Result_16_fu_1128_p4 <= ((res_3_fu_1084_p3 & select_ln422_4_fu_1076_p3) & ap_const_lv14_0);
    p_Result_17_fu_1156_p3 <= (shift_high_V_fu_1142_p4 & ap_const_lv2_0);
    p_Result_18_fu_1194_p4 <= ((res_3_fu_1084_p3 & shifted_V_fu_1174_p4) & ap_const_lv3_0);
    p_Result_19_fu_1286_p3 <= (select_ln422_fu_1044_p3 & select_ln422_1_fu_1052_p3);
    p_Result_20_fu_1294_p3 <= (res_3_fu_1084_p3 & shiftedTop_V_fu_1272_p4);
    p_Result_21_fu_1308_p3 <= addRes_V_fu_1302_p2(13 downto 13);
    p_Result_22_fu_1320_p3 <= (usefulRes_V_fu_1316_p1 & guards_V_fu_1282_p1);
    p_Result_23_fu_1378_p3 <= (lower_V_6_fu_1360_p1 & select_ln359_14_fu_1370_p3);
    p_Result_24_fu_1422_p3 <= (lower_V_7_fu_1404_p1 & select_ln359_15_fu_1414_p3);
    p_Result_25_fu_1466_p3 <= (lower_V_8_fu_1448_p1 & select_ln359_16_fu_1458_p3);
    p_Result_26_fu_1500_p3 <= (lower_V_9_fu_1496_p1 & p_Result_21_fu_1308_p3);
    p_Result_27_fu_1516_p5 <= (((comp_V_6_fu_1364_p2 & comp_V_7_fu_1408_p2) & comp_V_8_fu_1452_p2) & top_is_leading_V_2_fu_1490_p2);
    p_Result_28_fu_1556_p3 <= xor_ln1529_1_fu_1550_p2(2 downto 2);
    p_Result_29_fu_1606_p3 <= ret_29_fu_1544_p2(14 downto 14);
    p_Result_2_fu_218_p3 <= in1(14 downto 14);
    p_Result_30_fu_1634_p3 <= p_Val2_23_fu_1586_p2(6 downto 6);
    p_Result_31_fu_1688_p3 <= res_5_fu_1656_p3(1 downto 1);
    p_Result_32_fu_1696_p7 <= (((((p_Result_31_fu_1688_p3 & res_5_fu_1656_p3) & ret_33_fu_1628_p2) & val_V_129_fu_1614_p4) & p_Result_28_fu_1556_p3) & ap_const_lv12_0);
    p_Result_33_fu_1730_p3 <= (shift_high_V_1_fu_1716_p4 & ap_const_lv2_0);
    p_Result_34_fu_1768_p4 <= ((p_Result_31_fu_1688_p3 & shifted_V_4_fu_1748_p4) & ap_const_lv3_0);
    p_Result_35_fu_1808_p3 <= lshr_ln978_fu_1786_p2(3 downto 3);
    p_Result_36_fu_1826_p3 <= lshr_ln978_fu_1786_p2(4 downto 4);
    p_Result_37_fu_1862_p3 <= (p_Result_21_fu_1308_p3 & roundedResult_V_fu_1856_p2);
    p_Result_38_fu_1870_p3 <= (ret_32_fu_1598_p3 & ap_const_lv15_0);
    p_Result_3_fu_332_p3 <= (lower_V_fu_314_p1 & select_ln359_1_fu_324_p3);
    p_Result_4_fu_376_p3 <= (lower_V_1_fu_358_p1 & select_ln359_2_fu_368_p3);
    p_Result_5_fu_420_p3 <= (lower_V_2_fu_402_p1 & select_ln359_3_fu_412_p3);
    p_Result_6_fu_474_p5 <= (((comp_V_fu_318_p2 & comp_V_1_fu_362_p2) & comp_V_2_fu_406_p2) & top_is_leading_V_fu_444_p2);
    p_Result_7_fu_564_p7 <= (((((ret_3_fu_248_p2 & ret_10_fu_534_p2) & ret_11_fu_558_p2) & p_Result_s_fu_210_p3) & ret_4_fu_268_p2) & fraction_V_fu_510_p1);
    p_Result_8_fu_580_p3 <= in2(15 downto 15);
    p_Result_9_fu_588_p3 <= in2(14 downto 14);
    p_Result_s_fu_210_p3 <= in1(15 downto 15);
    p_Val2_23_fu_1586_p2 <= std_logic_vector(unsigned(add_ln1526_fu_1580_p2) - unsigned(zext_ln1526_fu_1576_p1));
    r_10_fu_1742_p2 <= std_logic_vector(shift_right(unsigned(sext_ln312_1_fu_1712_p1),to_integer(unsigned('0' & zext_ln978_fu_1738_p1(31-1 downto 0)))));
    r_11_fu_1796_p2 <= "0" when (shifted_out_V_3_fu_1792_p1 = ap_const_lv3_0) else "1";
    r_1_fu_520_p2 <= (xor_ln939_fu_514_p2 xor ap_const_lv1_1);
    r_2_fu_612_p2 <= (ret_12_fu_606_p2 xor ap_const_lv1_1);
    r_3_fu_890_p2 <= (xor_ln939_3_fu_884_p2 xor ap_const_lv1_1);
    r_4_fu_964_p2 <= "1" when (and_ln_fu_950_p6 = ap_const_lv21_0) else "0";
    r_5_fu_1020_p2 <= "0" when (and_ln1528_1_fu_970_p6 = ap_const_lv21_0) else "1";
    r_6_fu_1116_p2 <= "0" when (shift_weights_will_zero_V_fu_1106_p4 = ap_const_lv3_0) else "1";
    r_7_fu_1168_p2 <= std_logic_vector(shift_right(unsigned(sext_ln312_fu_1138_p1),to_integer(unsigned('0' & zext_ln978_1_fu_1164_p1(31-1 downto 0)))));
    r_8_fu_1232_p2 <= "0" when (shifted_out_V_1_fu_1228_p1 = ap_const_lv3_0) else "1";
    r_9_fu_1674_p2 <= (low_k_V_fu_1664_p4 xor ap_const_lv4_F);
    r_fu_242_p2 <= (ret_fu_236_p2 xor ap_const_lv1_1);
    res_2_fu_862_p3 <= 
        ap_const_lv4_E when (val_V_125_fu_856_p2(0) = '1') else 
        p_Result_13_fu_844_p5;
    res_3_fu_1084_p3 <= 
        p_Result_8_fu_580_p3 when (control_V_fu_1038_p2(0) = '1') else 
        p_Result_s_fu_210_p3;
    res_4_fu_1246_p3 <= 
        select_ln359_12_fu_1238_p3 when (r_6_fu_1116_p2(0) = '1') else 
        shifted_V_3_fu_1218_p4;
    res_5_fu_1656_p3 <= 
        ap_const_lv2_1 when (ret_34_fu_1650_p2(0) = '1') else 
        ap_const_lv2_2;
    res_fu_492_p3 <= 
        ap_const_lv4_E when (val_V_122_fu_486_p2(0) = '1') else 
        p_Result_6_fu_474_p5;
    ret_10_fu_534_p2 <= (zext_ln217_1_fu_506_p1 xor select_ln359_4_fu_526_p3);
    ret_11_fu_558_p2 <= (select_ln359_5_fu_550_p3 xor es_V_fu_540_p4);
    ret_12_fu_606_p2 <= (val_V_124_fu_600_p2 or p_Result_9_fu_588_p3);
    ret_13_fu_618_p2 <= (r_2_fu_612_p2 and p_Result_8_fu_580_p3);
    ret_14_fu_638_p2 <= (xor_ln1527_1_fu_632_p2 and ret_12_fu_606_p2);
    ret_15_fu_668_p2 <= (val_V_123_fu_596_p1 xor select_ln359_6_fu_652_p3);
    ret_16_fu_710_p3 <= 
        p_Result_10_fu_702_p3 when (comp_V_3_fu_688_p2(0) = '1') else 
        ret_15_fu_668_p2;
    ret_17_fu_754_p3 <= 
        p_Result_11_fu_746_p3 when (comp_V_4_fu_732_p2(0) = '1') else 
        ret_16_fu_710_p3;
    ret_18_fu_798_p3 <= 
        p_Result_12_fu_790_p3 when (comp_V_5_fu_776_p2(0) = '1') else 
        ret_17_fu_754_p3;
    ret_19_fu_870_p2 <= (select_ln356_1_fu_660_p3 xor opt1_V_7_fu_836_p3);
    ret_20_fu_904_p2 <= (zext_ln217_2_fu_876_p1 xor select_ln359_10_fu_896_p3);
    ret_21_fu_928_p2 <= (select_ln359_11_fu_920_p3 xor es_V_1_fu_910_p4);
    ret_22_fu_1032_p2 <= (val_V_126_fu_1026_p2 and r_5_fu_1020_p2);
    ret_23_fu_1254_p2 <= (r_6_fu_1116_p2 and icmp_ln1049_fu_1122_p2);
    ret_24_fu_1266_p2 <= (r_8_fu_1232_p2 or or_ln1528_fu_1260_p2);
    ret_25_fu_1344_p2 <= (select_ln359_13_fu_1336_p3 xor p_Result_22_fu_1320_p3);
    ret_26_fu_1386_p3 <= 
        p_Result_23_fu_1378_p3 when (comp_V_6_fu_1364_p2(0) = '1') else 
        ret_25_fu_1344_p2;
    ret_27_fu_1430_p3 <= 
        p_Result_24_fu_1422_p3 when (comp_V_7_fu_1408_p2(0) = '1') else 
        ret_26_fu_1386_p3;
    ret_28_fu_1474_p3 <= 
        p_Result_25_fu_1466_p3 when (comp_V_8_fu_1452_p2(0) = '1') else 
        ret_27_fu_1430_p3;
    ret_29_fu_1544_p2 <= (select_ln359_13_fu_1336_p3 xor opt1_V_fu_1508_p3);
    ret_30_fu_1564_p2 <= "0" when (trunc_ln1529_1_fu_1540_p1 = select_ln359_16_fu_1458_p3) else "1";
    ret_31_fu_1570_p2 <= (ret_30_fu_1564_p2 or ret_24_fu_1266_p2);
    ret_32_fu_1598_p3 <= or_ln1528_3_fu_1592_p2(20 downto 20);
    ret_33_fu_1628_p2 <= (select_ln359_16_fu_1458_p3 xor es_wo_xor_V_fu_1624_p1);
    ret_34_fu_1650_p2 <= (tmp_21_fu_1642_p3 xor p_Result_21_fu_1308_p3);
    ret_35_fu_1802_p2 <= (val_V_130_fu_1762_p2 or r_11_fu_1796_p2);
    ret_36_fu_1840_p2 <= (ret_35_fu_1802_p2 or or_ln1528_5_fu_1834_p2);
    ret_37_fu_1846_p2 <= (ret_36_fu_1840_p2 and p_Result_35_fu_1808_p3);
    ret_38_fu_1884_p2 <= (or_ln1527_fu_1878_p2 xor ap_const_lv1_1);
    ret_39_fu_1890_p2 <= (ret_38_fu_1884_p2 or ret_32_fu_1598_p3);
    ret_3_fu_248_p2 <= (r_fu_242_p2 and p_Result_s_fu_210_p3);
    ret_4_fu_268_p2 <= (xor_ln1527_fu_262_p2 and ret_fu_236_p2);
    ret_5_fu_298_p2 <= (val_V_119_fu_226_p1 xor select_ln359_fu_282_p3);
    ret_6_fu_340_p3 <= 
        p_Result_3_fu_332_p3 when (comp_V_fu_318_p2(0) = '1') else 
        ret_5_fu_298_p2;
    ret_7_fu_384_p3 <= 
        p_Result_4_fu_376_p3 when (comp_V_1_fu_362_p2(0) = '1') else 
        ret_6_fu_340_p3;
    ret_8_fu_428_p3 <= 
        p_Result_5_fu_420_p3 when (comp_V_2_fu_406_p2(0) = '1') else 
        ret_7_fu_384_p3;
    ret_9_fu_500_p2 <= (select_ln356_fu_290_p3 xor opt1_V_6_fu_466_p3);
    ret_fu_236_p2 <= (val_V_120_fu_230_p2 or p_Result_2_fu_218_p3);
    roundedResult_V_fu_1856_p2 <= std_logic_vector(unsigned(unroundedResult_V_fu_1816_p4) + unsigned(zext_ln217_fu_1852_p1));
    select_ln1529_fu_1528_p3 <= 
        ap_const_lv3_7 when (ext_2_fu_1328_p3(0) = '1') else 
        ap_const_lv3_0;
    select_ln356_1_fu_660_p3 <= 
        ap_const_lv13_1FFF when (tmp_9_fu_644_p3(0) = '1') else 
        ap_const_lv13_0;
    select_ln356_fu_290_p3 <= 
        ap_const_lv13_1FFF when (tmp_1_fu_274_p3(0) = '1') else 
        ap_const_lv13_0;
    select_ln359_10_fu_896_p3 <= 
        ap_const_lv5_1F when (r_3_fu_890_p2(0) = '1') else 
        ap_const_lv5_0;
    select_ln359_11_fu_920_p3 <= 
        ap_const_lv2_3 when (ext_1_fu_624_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_12_fu_1238_p3 <= 
        ap_const_lv15_7FFF when (res_3_fu_1084_p3(0) = '1') else 
        ap_const_lv15_0;
    select_ln359_13_fu_1336_p3 <= 
        ap_const_lv15_7FFF when (ext_2_fu_1328_p3(0) = '1') else 
        ap_const_lv15_0;
    select_ln359_14_fu_1370_p3 <= 
        ap_const_lv8_FF when (ext_2_fu_1328_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_15_fu_1414_p3 <= 
        ap_const_lv4_F when (ext_2_fu_1328_p3(0) = '1') else 
        ap_const_lv4_0;
    select_ln359_16_fu_1458_p3 <= 
        ap_const_lv2_3 when (ext_2_fu_1328_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_1_fu_324_p3 <= 
        ap_const_lv8_FF when (tmp_1_fu_274_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_2_fu_368_p3 <= 
        ap_const_lv4_F when (tmp_1_fu_274_p3(0) = '1') else 
        ap_const_lv4_0;
    select_ln359_3_fu_412_p3 <= 
        ap_const_lv2_3 when (tmp_1_fu_274_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_4_fu_526_p3 <= 
        ap_const_lv5_1F when (r_1_fu_520_p2(0) = '1') else 
        ap_const_lv5_0;
    select_ln359_5_fu_550_p3 <= 
        ap_const_lv2_3 when (ext_fu_254_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_6_fu_652_p3 <= 
        ap_const_lv14_3FFF when (tmp_9_fu_644_p3(0) = '1') else 
        ap_const_lv14_0;
    select_ln359_7_fu_694_p3 <= 
        ap_const_lv8_FF when (tmp_9_fu_644_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_8_fu_738_p3 <= 
        ap_const_lv4_F when (tmp_9_fu_644_p3(0) = '1') else 
        ap_const_lv4_0;
    select_ln359_9_fu_782_p3 <= 
        ap_const_lv2_3 when (tmp_9_fu_644_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_fu_282_p3 <= 
        ap_const_lv14_3FFF when (tmp_1_fu_274_p3(0) = '1') else 
        ap_const_lv14_0;
    select_ln422_1_fu_1052_p3 <= 
        lessSignificantSignificand_V_fu_994_p4 when (control_V_fu_1038_p2(0) = '1') else 
        mostSignificantSignificand_V_fu_984_p4;
    select_ln422_2_fu_1060_p3 <= 
        subExpOp2_V_fu_1004_p3 when (control_V_fu_1038_p2(0) = '1') else 
        opt1_V_8_fu_1012_p3;
    select_ln422_3_fu_1068_p3 <= 
        opt1_V_8_fu_1012_p3 when (control_V_fu_1038_p2(0) = '1') else 
        subExpOp2_V_fu_1004_p3;
    select_ln422_4_fu_1076_p3 <= 
        mostSignificantSignificand_V_fu_984_p4 when (control_V_fu_1038_p2(0) = '1') else 
        lessSignificantSignificand_V_fu_994_p4;
    select_ln422_fu_1044_p3 <= 
        p_Result_s_fu_210_p3 when (control_V_fu_1038_p2(0) = '1') else 
        p_Result_8_fu_580_p3;
        sext_ln312_1_fu_1712_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_32_fu_1696_p7),40));

        sext_ln312_fu_1138_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_16_fu_1128_p4),39));

        sext_ln978_1_fu_1778_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_34_fu_1768_p4),22));

        sext_ln978_fu_1204_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_18_fu_1194_p4),21));

    shiftValue_V_fu_1092_p2 <= std_logic_vector(unsigned(select_ln422_2_fu_1060_p3) - unsigned(select_ln422_3_fu_1068_p3));
    shift_high_V_1_fu_1716_p4 <= opt1_V_9_fu_1680_p3(3 downto 2);
    shift_high_V_fu_1142_p4 <= shiftValue_V_fu_1092_p2(3 downto 2);
    shift_low_V_1_fu_1726_p1 <= opt1_V_9_fu_1680_p3(2 - 1 downto 0);
    shift_low_V_fu_1152_p1 <= shiftValue_V_fu_1092_p2(2 - 1 downto 0);
    shift_weights_will_zero_V_fu_1106_p4 <= shiftValue_V_fu_1092_p2(6 downto 4);
    shiftedTop_V_fu_1272_p4 <= res_4_fu_1246_p3(14 downto 2);
    shifted_V_3_fu_1218_p4 <= lshr_ln978_2_fu_1212_p2(17 downto 3);
    shifted_V_4_fu_1748_p4 <= r_10_fu_1742_p2(27 downto 12);
    shifted_V_fu_1174_p4 <= r_7_fu_1168_p2(26 downto 12);
    shifted_out_V_1_fu_1228_p1 <= lshr_ln978_2_fu_1212_p2(3 - 1 downto 0);
    shifted_out_V_2_fu_1758_p1 <= r_10_fu_1742_p2(12 - 1 downto 0);
    shifted_out_V_3_fu_1792_p1 <= lshr_ln978_fu_1786_p2(3 - 1 downto 0);
    shifted_out_V_fu_1184_p1 <= r_7_fu_1168_p2(12 - 1 downto 0);
    subExpOp2_V_fu_1004_p3 <= (ret_10_fu_534_p2 & ret_11_fu_558_p2);
    tmp_13_fu_806_p3 <= ret_18_fu_798_p3(13 downto 13);
    tmp_1_fu_274_p3 <= in1(14 downto 14);
    tmp_21_fu_1642_p3 <= p_Val2_23_fu_1586_p2(6 downto 6);
    tmp_5_fu_454_p3 <= (trunc_ln312_fu_450_p1 & p_Result_2_fu_218_p3);
    tmp_6_fu_436_p3 <= ret_8_fu_428_p3(13 downto 13);
    tmp_7_fu_824_p3 <= (trunc_ln312_1_fu_820_p1 & p_Result_9_fu_588_p3);
    tmp_9_fu_644_p3 <= in2(14 downto 14);
    tmp_fu_1482_p3 <= ret_28_fu_1474_p3(14 downto 14);
    top_is_leading_V_1_fu_814_p2 <= (tmp_13_fu_806_p3 xor ap_const_lv1_1);
    top_is_leading_V_2_fu_1490_p2 <= (tmp_fu_1482_p3 xor ap_const_lv1_1);
    top_is_leading_V_fu_444_p2 <= (tmp_6_fu_436_p3 xor ap_const_lv1_1);
    trunc_ln1529_1_fu_1540_p1 <= opt1_V_fu_1508_p3(2 - 1 downto 0);
    trunc_ln1529_fu_1536_p1 <= opt1_V_fu_1508_p3(3 - 1 downto 0);
    trunc_ln312_1_fu_820_p1 <= ret_18_fu_798_p3(12 - 1 downto 0);
    trunc_ln312_fu_450_p1 <= ret_8_fu_428_p3(12 - 1 downto 0);
    trunc_ln422_1_fu_832_p1 <= ret_18_fu_798_p3(13 - 1 downto 0);
    trunc_ln422_fu_462_p1 <= ret_8_fu_428_p3(13 - 1 downto 0);
    unroundedResult_V_fu_1816_p4 <= lshr_ln978_fu_1786_p2(18 downto 4);
    upper_V_1_fu_348_p4 <= ret_6_fu_340_p3(13 downto 10);
    upper_V_3_fu_674_p4 <= ret_15_fu_668_p2(13 downto 6);
    upper_V_4_fu_718_p4 <= ret_16_fu_710_p3(13 downto 10);
    upper_V_6_fu_1350_p4 <= ret_25_fu_1344_p2(14 downto 7);
    upper_V_7_fu_1394_p4 <= ret_26_fu_1386_p3(14 downto 11);
    upper_V_fu_304_p4 <= ret_5_fu_298_p2(13 downto 6);
    usefulRes_V_fu_1316_p1 <= addRes_V_fu_1302_p2(13 - 1 downto 0);
    val_V_119_fu_226_p1 <= in1(14 - 1 downto 0);
    val_V_120_fu_230_p2 <= "0" when (val_V_119_fu_226_p1 = ap_const_lv14_0) else "1";
    val_V_121_fu_392_p4 <= ret_7_fu_384_p3(13 downto 12);
    val_V_122_fu_486_p2 <= "1" when (p_Result_6_fu_474_p5 = ap_const_lv4_F) else "0";
    val_V_123_fu_596_p1 <= in2(14 - 1 downto 0);
    val_V_124_fu_600_p2 <= "0" when (val_V_123_fu_596_p1 = ap_const_lv14_0) else "1";
    val_V_125_fu_856_p2 <= "1" when (p_Result_13_fu_844_p5 = ap_const_lv4_F) else "0";
    val_V_126_fu_1026_p2 <= "1" when (signed(subExpOp2_V_fu_1004_p3) > signed(opt1_V_8_fu_1012_p3)) else "0";
    val_V_127_fu_1188_p2 <= "0" when (shifted_out_V_fu_1184_p1 = ap_const_lv12_0) else "1";
    val_V_128_fu_1438_p4 <= ret_27_fu_1430_p3(14 downto 13);
    val_V_129_fu_1614_p4 <= ret_29_fu_1544_p2(13 downto 3);
    val_V_130_fu_1762_p2 <= "0" when (shifted_out_V_2_fu_1758_p1 = ap_const_lv12_0) else "1";
    val_V_fu_762_p4 <= ret_17_fu_754_p3(13 downto 12);
    xor_ln1527_1_fu_632_p2 <= (ext_1_fu_624_p3 xor ap_const_lv1_1);
    xor_ln1527_fu_262_p2 <= (ext_fu_254_p3 xor ap_const_lv1_1);
    xor_ln1529_1_fu_1550_p2 <= (trunc_ln1529_fu_1536_p1 xor select_ln1529_fu_1528_p3);
    xor_ln939_3_fu_884_p2 <= (tmp_9_fu_644_p3 xor ext_1_fu_624_p3);
    xor_ln939_fu_514_p2 <= (tmp_1_fu_274_p3 xor ext_fu_254_p3);
    zext_ln1526_fu_1576_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_27_fu_1516_p5),7));
    zext_ln217_1_fu_506_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_fu_492_p3),5));
    zext_ln217_2_fu_876_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_2_fu_862_p3),5));
    zext_ln217_fu_1852_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_37_fu_1846_p2),15));
    zext_ln978_1_fu_1164_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_17_fu_1156_p3),39));
    zext_ln978_2_fu_1208_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shift_low_V_fu_1152_p1),21));
    zext_ln978_3_fu_1782_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shift_low_V_1_fu_1726_p1),22));
    zext_ln978_fu_1738_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_33_fu_1730_p3),40));
end behav;
