-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity posit_comp_mul is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in1 : IN STD_LOGIC_VECTOR (31 downto 0);
    in2 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of posit_comp_mul is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "posit_comp_mul_posit_comp_mul,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=100.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=34.758014,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=1672,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv30_3FFFFFFF : STD_LOGIC_VECTOR (29 downto 0) := "111111111111111111111111111111";
    constant ap_const_lv29_1FFFFFFF : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111111111111111111";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv27_0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    constant ap_const_lv38_0 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000000";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv37_10F0000000 : STD_LOGIC_VECTOR (36 downto 0) := "1000011110000000000000000000000000000";
    constant ap_const_lv37_1108000000 : STD_LOGIC_VECTOR (36 downto 0) := "1000100001000000000000000000000000000";
    constant ap_const_lv37_EF0000000 : STD_LOGIC_VECTOR (36 downto 0) := "0111011110000000000000000000000000000";
    constant ap_const_lv37_F08000000 : STD_LOGIC_VECTOR (36 downto 0) := "0111100001000000000000000000000000000";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal val_V_fu_242_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal val_V_84_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_fu_234_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_fu_252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_226_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ext_fu_270_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1527_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_290_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_fu_298_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_3_fu_314_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal upper_V_fu_320_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal lower_V_fu_330_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln359_1_fu_340_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal comp_V_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_3_fu_348_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_4_fu_356_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal upper_V_1_fu_364_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lower_V_1_fu_374_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln359_2_fu_384_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal comp_V_1_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_4_fu_392_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_5_fu_400_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal upper_V_2_fu_408_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal lower_V_2_fu_418_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal select_ln359_3_fu_428_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal comp_V_2_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_5_fu_436_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_6_fu_444_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal val_V_85_fu_452_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lower_V_3_fu_462_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln359_4_fu_472_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal comp_V_3_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_6_fu_480_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_7_fu_488_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_7_fu_496_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln312_fu_510_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal trunc_ln422_fu_522_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_6_fu_514_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal top_is_leading_V_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_7_fu_534_p6 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_V_86_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal opt1_V_9_fu_526_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln356_fu_306_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal res_12_fu_554_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_8_fu_562_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal xor_ln939_fu_576_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln217_fu_568_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln359_5_fu_588_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal es_V_fu_602_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln359_6_fu_612_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_1_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_9_fu_596_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ret_10_fu_620_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_2_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fraction_V_fu_572_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal val_V_87_fu_658_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal val_V_88_fu_662_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_10_fu_650_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_11_fu_668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_fu_642_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_2_fu_674_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ext_1_fu_686_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1527_1_fu_694_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_706_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_7_fu_714_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_14_fu_730_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal upper_V_4_fu_736_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal lower_V_4_fu_746_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln359_8_fu_756_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal comp_V_4_fu_750_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_11_fu_764_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_15_fu_772_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal upper_V_5_fu_780_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lower_V_5_fu_790_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln359_9_fu_800_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal comp_V_5_fu_794_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_12_fu_808_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_16_fu_816_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal upper_V_6_fu_824_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal lower_V_6_fu_834_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal select_ln359_10_fu_844_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal comp_V_6_fu_838_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_13_fu_852_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_17_fu_860_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal val_V_89_fu_868_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lower_V_7_fu_878_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln359_11_fu_888_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal comp_V_7_fu_882_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_14_fu_896_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_18_fu_904_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_15_fu_912_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln312_1_fu_926_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal trunc_ln422_1_fu_938_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_8_fu_930_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal top_is_leading_V_1_fu_920_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_15_fu_950_p6 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_V_90_fu_964_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal opt1_V_10_fu_942_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln356_1_fu_722_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal res_13_fu_970_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_19_fu_978_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal xor_ln939_3_fu_992_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_3_fu_998_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln217_1_fu_984_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln359_12_fu_1004_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal es_V_1_fu_1018_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln359_13_fu_1028_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_12_fu_680_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_20_fu_1012_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ret_21_fu_1036_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_13_fu_700_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fraction_V_1_fu_988_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_16_fu_1042_p7 : STD_LOGIC_VECTOR (37 downto 0);
    signal p_Result_8_fu_626_p7 : STD_LOGIC_VECTOR (37 downto 0);
    signal or_ln1528_fu_1058_p2 : STD_LOGIC_VECTOR (37 downto 0);
    signal and_ln_fu_1072_p6 : STD_LOGIC_VECTOR (37 downto 0);
    signal and_ln1528_1_fu_1092_p6 : STD_LOGIC_VECTOR (37 downto 0);
    signal r_4_fu_1086_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_5_fu_1106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_17_fu_1118_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal p_Result_18_fu_1128_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal ret_24_fu_1146_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal tmp_fu_1168_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_21_fu_1182_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_6_fu_1176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_1196_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_25_fu_1190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_26_fu_1204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_20_fu_1160_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_28_fu_1216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_bits_V_fu_1222_p1 : STD_LOGIC_VECTOR (54 downto 0);
    signal ret_27_fu_1210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_22_fu_1226_p3 : STD_LOGIC_VECTOR (55 downto 0);
    signal p_Result_23_fu_1234_p3 : STD_LOGIC_VECTOR (55 downto 0);
    signal exp1_V_fu_1250_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal exp2_V_fu_1258_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln225_2_fu_1266_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln225_3_fu_1270_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln217_2_fu_1278_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln306_fu_1274_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln217_1_fu_1288_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln217_3_fu_1294_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln217_fu_1282_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_23_fu_1112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal expSumVal_V_fu_1298_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal opt1_V_11_fu_1242_p3 : STD_LOGIC_VECTOR (55 downto 0);
    signal p_what2_s_fu_1320_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_19_fu_1152_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_1330_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_14_fu_1304_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_23_fu_1344_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_7_fu_1352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_14_fu_1358_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal or_ln_fu_1372_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln217_fu_1380_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln217_4_fu_1384_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_29_fu_1366_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_s_fu_1388_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_22_fu_1064_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_9_fu_1338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_8_fu_1402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1527_fu_1408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_25_fu_1394_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_30_fu_1414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_31_fu_1420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln416_fu_1434_p3 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_fu_1426_p3 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_15_fu_1442_p3 : STD_LOGIC_VECTOR (36 downto 0);
    signal p_Result_24_fu_1312_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_91_fu_1324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_92_fu_1454_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_25_fu_1458_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln217_5_fu_1450_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal p_Result_26_fu_1468_p7 : STD_LOGIC_VECTOR (39 downto 0);
    signal opt1_V_12_fu_1484_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_28_fu_1504_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal es_wo_xor_V_fu_1520_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln359_15_fu_1512_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_30_fu_1544_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_33_fu_1552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal low_k_V_fu_1566_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Result_28_fu_1536_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_10_fu_1576_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal res_16_fu_1558_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_30_fu_1598_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_32_fu_1530_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal significand_V_fu_1500_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_29_fu_1590_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_fu_1606_p7 : STD_LOGIC_VECTOR (56 downto 0);
    signal opt1_V_13_fu_1582_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shift_high_V_fu_1626_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_32_fu_1636_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln312_fu_1622_p1 : STD_LOGIC_VECTOR (79 downto 0);
    signal zext_ln978_fu_1644_p1 : STD_LOGIC_VECTOR (79 downto 0);
    signal r_11_fu_1648_p2 : STD_LOGIC_VECTOR (79 downto 0);
    signal shifted_out_V_fu_1664_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal shifted_V_fu_1654_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_33_fu_1674_p4 : STD_LOGIC_VECTOR (38 downto 0);
    signal shift_high_V_1_fu_1688_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_34_fu_1702_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln312_1_fu_1684_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal zext_ln978_1_fu_1710_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal r_12_fu_1714_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal shifted_out_V_1_fu_1730_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shifted_V_3_fu_1720_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_V_94_fu_1698_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_35_fu_1740_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln978_2_fu_1750_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal r_13_fu_1754_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal val_V_95_fu_1734_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_93_fu_1668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1528_6_fu_1764_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shifted_out_V_3_fu_1760_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_37_fu_1802_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_38_fu_1794_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1528_8_fu_1810_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_34_fu_1770_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_36_fu_1776_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_35_fu_1816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_36_fu_1822_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal unroundedResult_V_fu_1784_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln217_6_fu_1828_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal p_Result_27_fu_1492_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal roundedResult_V_fu_1832_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal p_Result_40_fu_1846_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_44_fu_1862_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1527_fu_1870_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_37_fu_1876_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_38_fu_1882_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_41_fu_1854_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_39_fu_1838_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component posit_comp_mul_mul_29s_29s_58_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (28 downto 0);
        din1 : IN STD_LOGIC_VECTOR (28 downto 0);
        dout : OUT STD_LOGIC_VECTOR (57 downto 0) );
    end component;



begin
    mul_29s_29s_58_1_1_U1 : component posit_comp_mul_mul_29s_29s_58_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 29,
        din1_WIDTH => 29,
        dout_WIDTH => 58)
    port map (
        din0 => p_Result_18_fu_1128_p4,
        din1 => p_Result_17_fu_1118_p4,
        dout => ret_24_fu_1146_p2);




    add_ln217_1_fu_1288_p2 <= std_logic_vector(unsigned(zext_ln217_2_fu_1278_p1) + unsigned(zext_ln306_fu_1274_p1));
    add_ln217_fu_1282_p2 <= std_logic_vector(signed(sext_ln225_2_fu_1266_p1) + signed(sext_ln225_3_fu_1270_p1));
    and_ln1527_fu_1408_p2 <= (r_9_fu_1338_p2 and r_8_fu_1402_p2);
    and_ln1528_1_fu_1092_p6 <= ((((ret_12_fu_680_p2 & ap_const_lv8_0) & p_Result_9_fu_642_p3) & ret_13_fu_700_p2) & ap_const_lv27_0);
    and_ln_fu_1072_p6 <= ((((ret_1_fu_264_p2 & ap_const_lv8_0) & p_Result_s_fu_226_p3) & ret_2_fu_284_p2) & ap_const_lv27_0);
    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_ready <= ap_start;
    ap_return <= 
        p_Result_41_fu_1854_p3 when (ret_38_fu_1882_p2(0) = '1') else 
        p_Result_39_fu_1838_p3;
    comp_V_1_fu_378_p2 <= "1" when (upper_V_1_fu_364_p4 = ap_const_lv8_0) else "0";
    comp_V_2_fu_422_p2 <= "1" when (upper_V_2_fu_408_p4 = ap_const_lv4_0) else "0";
    comp_V_3_fu_466_p2 <= "1" when (val_V_85_fu_452_p4 = ap_const_lv2_0) else "0";
    comp_V_4_fu_750_p2 <= "1" when (upper_V_4_fu_736_p4 = ap_const_lv16_0) else "0";
    comp_V_5_fu_794_p2 <= "1" when (upper_V_5_fu_780_p4 = ap_const_lv8_0) else "0";
    comp_V_6_fu_838_p2 <= "1" when (upper_V_6_fu_824_p4 = ap_const_lv4_0) else "0";
    comp_V_7_fu_882_p2 <= "1" when (val_V_89_fu_868_p4 = ap_const_lv2_0) else "0";
    comp_V_fu_334_p2 <= "1" when (upper_V_fu_320_p4 = ap_const_lv16_0) else "0";
    es_V_1_fu_1018_p4 <= ret_19_fu_978_p2(28 downto 27);
    es_V_fu_602_p4 <= ret_8_fu_562_p2(28 downto 27);
    es_wo_xor_V_fu_1520_p4 <= opt1_V_12_fu_1484_p3(30 downto 29);
    exp1_V_fu_1250_p3 <= (ret_9_fu_596_p2 & ret_10_fu_620_p2);
    exp2_V_fu_1258_p3 <= (ret_20_fu_1012_p2 & ret_21_fu_1036_p2);
    expSumVal_V_fu_1298_p2 <= std_logic_vector(unsigned(zext_ln217_3_fu_1294_p1) + unsigned(add_ln217_fu_1282_p2));
    ext_1_fu_686_p3 <= in2(31 downto 31);
    ext_fu_270_p3 <= in1(31 downto 31);
    fraction_V_1_fu_988_p1 <= ret_19_fu_978_p2(27 - 1 downto 0);
    fraction_V_fu_572_p1 <= ret_8_fu_562_p2(27 - 1 downto 0);
    last_bits_V_fu_1222_p1 <= ret_24_fu_1146_p2(55 - 1 downto 0);
    low_k_V_fu_1566_p4 <= opt1_V_12_fu_1484_p3(35 downto 31);
    lower_V_1_fu_374_p1 <= ret_4_fu_356_p3(22 - 1 downto 0);
    lower_V_2_fu_418_p1 <= ret_5_fu_400_p3(26 - 1 downto 0);
    lower_V_3_fu_462_p1 <= ret_6_fu_444_p3(28 - 1 downto 0);
    lower_V_4_fu_746_p1 <= ret_14_fu_730_p2(14 - 1 downto 0);
    lower_V_5_fu_790_p1 <= ret_15_fu_772_p3(22 - 1 downto 0);
    lower_V_6_fu_834_p1 <= ret_16_fu_816_p3(26 - 1 downto 0);
    lower_V_7_fu_878_p1 <= ret_17_fu_860_p3(28 - 1 downto 0);
    lower_V_fu_330_p1 <= ret_3_fu_314_p2(14 - 1 downto 0);
    opt1_V_10_fu_942_p3 <= 
        trunc_ln422_1_fu_938_p1 when (tmp_15_fu_912_p3(0) = '1') else 
        tmp_8_fu_930_p3;
    opt1_V_11_fu_1242_p3 <= 
        p_Result_22_fu_1226_p3 when (ret_27_fu_1210_p2(0) = '1') else 
        p_Result_23_fu_1234_p3;
    opt1_V_12_fu_1484_p3 <= 
        zext_ln217_5_fu_1450_p1 when (ret_30_fu_1414_p2(0) = '1') else 
        p_Result_26_fu_1468_p7;
    opt1_V_13_fu_1582_p3 <= 
        r_10_fu_1576_p2 when (p_Result_28_fu_1536_p3(0) = '1') else 
        low_k_V_fu_1566_p4;
    opt1_V_9_fu_526_p3 <= 
        trunc_ln422_fu_522_p1 when (tmp_7_fu_496_p3(0) = '1') else 
        tmp_6_fu_514_p3;
    or_ln1527_fu_1870_p2 <= (tmp_44_fu_1862_p3 or tmp_28_fu_1504_p3);
    or_ln1528_6_fu_1764_p2 <= (val_V_95_fu_1734_p2 or val_V_93_fu_1668_p2);
    or_ln1528_8_fu_1810_p2 <= (p_Result_38_fu_1794_p3 or p_Result_37_fu_1802_p3);
    or_ln1528_fu_1058_p2 <= (p_Result_8_fu_626_p7 or p_Result_16_fu_1042_p7);
    or_ln_fu_1372_p3 <= (ap_const_lv3_4 & r_7_fu_1352_p2);
    p_Result_10_fu_650_p3 <= in2(30 downto 30);
    p_Result_11_fu_764_p3 <= (lower_V_4_fu_746_p1 & select_ln359_8_fu_756_p3);
    p_Result_12_fu_808_p3 <= (lower_V_5_fu_790_p1 & select_ln359_9_fu_800_p3);
    p_Result_13_fu_852_p3 <= (lower_V_6_fu_834_p1 & select_ln359_10_fu_844_p3);
    p_Result_14_fu_896_p3 <= (lower_V_7_fu_878_p1 & select_ln359_11_fu_888_p3);
    p_Result_15_fu_950_p6 <= ((((comp_V_4_fu_750_p2 & comp_V_5_fu_794_p2) & comp_V_6_fu_838_p2) & comp_V_7_fu_882_p2) & top_is_leading_V_1_fu_920_p2);
    p_Result_16_fu_1042_p7 <= (((((ret_12_fu_680_p2 & ret_20_fu_1012_p2) & ret_21_fu_1036_p2) & p_Result_9_fu_642_p3) & ret_13_fu_700_p2) & fraction_V_1_fu_988_p1);
    p_Result_17_fu_1118_p4 <= ((p_Result_s_fu_226_p3 & ret_2_fu_284_p2) & fraction_V_fu_572_p1);
    p_Result_18_fu_1128_p4 <= ((p_Result_9_fu_642_p3 & ret_13_fu_700_p2) & fraction_V_1_fu_988_p1);
    p_Result_19_fu_1152_p3 <= ret_24_fu_1146_p2(57 downto 57);
    p_Result_20_fu_1160_p3 <= ret_24_fu_1146_p2(55 downto 55);
    p_Result_21_fu_1182_p3 <= ret_24_fu_1146_p2(56 downto 56);
    p_Result_22_fu_1226_p3 <= (ret_28_fu_1216_p2 & last_bits_V_fu_1222_p1);
    p_Result_23_fu_1234_p3 <= (last_bits_V_fu_1222_p1 & ap_const_lv1_0);
    p_Result_24_fu_1312_p3 <= opt1_V_11_fu_1242_p3(27 downto 27);
    p_Result_25_fu_1394_p3 <= p_Val2_s_fu_1388_p2(8 downto 8);
    p_Result_26_fu_1468_p7 <= (((((p_Result_24_fu_1312_p3 & val_V_91_fu_1324_p2) & ret_22_fu_1064_p3) & val_V_92_fu_1454_p1) & p_Result_19_fu_1152_p3) & tmp_25_fu_1458_p4);
    p_Result_27_fu_1492_p3 <= opt1_V_12_fu_1484_p3(28 downto 28);
    p_Result_28_fu_1536_p3 <= opt1_V_12_fu_1484_p3(36 downto 36);
    p_Result_29_fu_1590_p3 <= opt1_V_12_fu_1484_p3(39 downto 39);
    p_Result_2_fu_234_p3 <= in1(30 downto 30);
    p_Result_30_fu_1598_p3 <= res_16_fu_1558_p3(1 downto 1);
    p_Result_31_fu_1606_p7 <= (((((p_Result_30_fu_1598_p3 & res_16_fu_1558_p3) & ret_32_fu_1530_p2) & significand_V_fu_1500_p1) & p_Result_29_fu_1590_p3) & ap_const_lv24_0);
    p_Result_32_fu_1636_p3 <= (shift_high_V_fu_1626_p4 & ap_const_lv3_0);
    p_Result_33_fu_1674_p4 <= ((p_Result_30_fu_1598_p3 & shifted_V_fu_1654_p4) & ap_const_lv6_0);
    p_Result_34_fu_1702_p3 <= (shift_high_V_1_fu_1688_p4 & ap_const_lv1_0);
    p_Result_35_fu_1740_p4 <= ((p_Result_30_fu_1598_p3 & shifted_V_3_fu_1720_p4) & ap_const_lv1_0);
    p_Result_36_fu_1776_p3 <= r_13_fu_1754_p2(1 downto 1);
    p_Result_37_fu_1802_p3 <= opt1_V_12_fu_1484_p3(38 downto 38);
    p_Result_38_fu_1794_p3 <= r_13_fu_1754_p2(2 downto 2);
    p_Result_39_fu_1838_p3 <= (p_Result_27_fu_1492_p3 & roundedResult_V_fu_1832_p2);
    p_Result_3_fu_348_p3 <= (lower_V_fu_330_p1 & select_ln359_1_fu_340_p3);
    p_Result_40_fu_1846_p3 <= opt1_V_12_fu_1484_p3(37 downto 37);
    p_Result_41_fu_1854_p3 <= (p_Result_40_fu_1846_p3 & ap_const_lv31_0);
    p_Result_4_fu_392_p3 <= (lower_V_1_fu_374_p1 & select_ln359_2_fu_384_p3);
    p_Result_5_fu_436_p3 <= (lower_V_2_fu_418_p1 & select_ln359_3_fu_428_p3);
    p_Result_6_fu_480_p3 <= (lower_V_3_fu_462_p1 & select_ln359_4_fu_472_p3);
    p_Result_7_fu_534_p6 <= ((((comp_V_fu_334_p2 & comp_V_1_fu_378_p2) & comp_V_2_fu_422_p2) & comp_V_3_fu_466_p2) & top_is_leading_V_fu_504_p2);
    p_Result_8_fu_626_p7 <= (((((ret_1_fu_264_p2 & ret_9_fu_596_p2) & ret_10_fu_620_p2) & p_Result_s_fu_226_p3) & ret_2_fu_284_p2) & fraction_V_fu_572_p1);
    p_Result_9_fu_642_p3 <= in2(31 downto 31);
    p_Result_s_fu_226_p3 <= in1(31 downto 31);
    p_Val2_s_fu_1388_p2 <= std_logic_vector(unsigned(zext_ln217_4_fu_1384_p1) + unsigned(ret_29_fu_1366_p2));
    p_what2_s_fu_1320_p1 <= opt1_V_11_fu_1242_p3(27 - 1 downto 0);
    r_10_fu_1576_p2 <= (low_k_V_fu_1566_p4 xor ap_const_lv5_1F);
    r_11_fu_1648_p2 <= std_logic_vector(shift_right(unsigned(sext_ln312_fu_1622_p1),to_integer(unsigned('0' & zext_ln978_fu_1644_p1(31-1 downto 0)))));
    r_12_fu_1714_p2 <= std_logic_vector(shift_right(unsigned(sext_ln312_1_fu_1684_p1),to_integer(unsigned('0' & zext_ln978_1_fu_1710_p1(31-1 downto 0)))));
    r_13_fu_1754_p2 <= std_logic_vector(shift_right(unsigned(p_Result_35_fu_1740_p4),to_integer(unsigned('0' & zext_ln978_2_fu_1750_p1(31-1 downto 0)))));
    r_1_fu_582_p2 <= (xor_ln939_fu_576_p2 xor ap_const_lv1_1);
    r_2_fu_674_p2 <= (ret_11_fu_668_p2 xor ap_const_lv1_1);
    r_3_fu_998_p2 <= (xor_ln939_3_fu_992_p2 xor ap_const_lv1_1);
    r_4_fu_1086_p2 <= "1" when (and_ln_fu_1072_p6 = ap_const_lv38_0) else "0";
    r_5_fu_1106_p2 <= "1" when (and_ln1528_1_fu_1092_p6 = ap_const_lv38_0) else "0";
    r_6_fu_1176_p2 <= (tmp_fu_1168_p3 xor ap_const_lv1_1);
    r_7_fu_1352_p2 <= (tmp_23_fu_1344_p3 xor ap_const_lv1_1);
    r_8_fu_1402_p2 <= (ret_22_fu_1064_p3 xor ap_const_lv1_1);
    r_9_fu_1338_p2 <= (tmp_22_fu_1330_p3 or p_Result_19_fu_1152_p3);
    r_fu_258_p2 <= (ret_fu_252_p2 xor ap_const_lv1_1);
    res_12_fu_554_p3 <= 
        ap_const_lv5_1E when (val_V_86_fu_548_p2(0) = '1') else 
        p_Result_7_fu_534_p6;
    res_13_fu_970_p3 <= 
        ap_const_lv5_1E when (val_V_90_fu_964_p2(0) = '1') else 
        p_Result_15_fu_950_p6;
    res_14_fu_1304_p3 <= 
        ap_const_lv9_0 when (ret_23_fu_1112_p2(0) = '1') else 
        expSumVal_V_fu_1298_p2;
    res_15_fu_1442_p3 <= 
        select_ln416_fu_1434_p3 when (ret_31_fu_1420_p2(0) = '1') else 
        res_fu_1426_p3;
    res_16_fu_1558_p3 <= 
        ap_const_lv2_1 when (ret_33_fu_1552_p2(0) = '1') else 
        ap_const_lv2_2;
    res_fu_1426_p3 <= 
        ap_const_lv37_10F0000000 when (p_Result_19_fu_1152_p3(0) = '1') else 
        ap_const_lv37_1108000000;
    ret_10_fu_620_p2 <= (select_ln359_6_fu_612_p3 xor es_V_fu_602_p4);
    ret_11_fu_668_p2 <= (val_V_88_fu_662_p2 or p_Result_10_fu_650_p3);
    ret_12_fu_680_p2 <= (r_2_fu_674_p2 and p_Result_9_fu_642_p3);
    ret_13_fu_700_p2 <= (xor_ln1527_1_fu_694_p2 and ret_11_fu_668_p2);
    ret_14_fu_730_p2 <= (val_V_87_fu_658_p1 xor select_ln359_7_fu_714_p3);
    ret_15_fu_772_p3 <= 
        p_Result_11_fu_764_p3 when (comp_V_4_fu_750_p2(0) = '1') else 
        ret_14_fu_730_p2;
    ret_16_fu_816_p3 <= 
        p_Result_12_fu_808_p3 when (comp_V_5_fu_794_p2(0) = '1') else 
        ret_15_fu_772_p3;
    ret_17_fu_860_p3 <= 
        p_Result_13_fu_852_p3 when (comp_V_6_fu_838_p2(0) = '1') else 
        ret_16_fu_816_p3;
    ret_18_fu_904_p3 <= 
        p_Result_14_fu_896_p3 when (comp_V_7_fu_882_p2(0) = '1') else 
        ret_17_fu_860_p3;
    ret_19_fu_978_p2 <= (select_ln356_1_fu_722_p3 xor opt1_V_10_fu_942_p3);
    ret_1_fu_264_p2 <= (r_fu_258_p2 and p_Result_s_fu_226_p3);
    ret_20_fu_1012_p2 <= (zext_ln217_1_fu_984_p1 xor select_ln359_12_fu_1004_p3);
    ret_21_fu_1036_p2 <= (select_ln359_13_fu_1028_p3 xor es_V_1_fu_1018_p4);
    ret_22_fu_1064_p3 <= or_ln1528_fu_1058_p2(37 downto 37);
    ret_23_fu_1112_p2 <= (r_5_fu_1106_p2 or r_4_fu_1086_p2);
    ret_25_fu_1190_p2 <= (r_6_fu_1176_p2 and p_Result_21_fu_1182_p3);
    ret_26_fu_1204_p2 <= (tmp_fu_1168_p3 xor tmp_18_fu_1196_p3);
    ret_27_fu_1210_p2 <= (ret_26_fu_1204_p2 or ret_25_fu_1190_p2);
    ret_28_fu_1216_p2 <= (ret_25_fu_1190_p2 or p_Result_20_fu_1160_p3);
    ret_29_fu_1366_p2 <= (select_ln359_14_fu_1358_p3 xor res_14_fu_1304_p3);
    ret_2_fu_284_p2 <= (xor_ln1527_fu_278_p2 and ret_fu_252_p2);
    ret_30_fu_1414_p2 <= (p_Result_25_fu_1394_p3 and and_ln1527_fu_1408_p2);
    ret_31_fu_1420_p2 <= (ret_30_fu_1414_p2 and r_7_fu_1352_p2);
    ret_32_fu_1530_p2 <= (select_ln359_15_fu_1512_p3 xor es_wo_xor_V_fu_1520_p4);
    ret_33_fu_1552_p2 <= (tmp_30_fu_1544_p3 xor tmp_28_fu_1504_p3);
    ret_34_fu_1770_p2 <= (shifted_out_V_3_fu_1760_p1 or or_ln1528_6_fu_1764_p2);
    ret_35_fu_1816_p2 <= (ret_34_fu_1770_p2 or or_ln1528_8_fu_1810_p2);
    ret_36_fu_1822_p2 <= (ret_35_fu_1816_p2 and p_Result_36_fu_1776_p3);
    ret_37_fu_1876_p2 <= (or_ln1527_fu_1870_p2 xor ap_const_lv1_1);
    ret_38_fu_1882_p2 <= (ret_37_fu_1876_p2 or p_Result_40_fu_1846_p3);
    ret_3_fu_314_p2 <= (val_V_fu_242_p1 xor select_ln359_fu_298_p3);
    ret_4_fu_356_p3 <= 
        p_Result_3_fu_348_p3 when (comp_V_fu_334_p2(0) = '1') else 
        ret_3_fu_314_p2;
    ret_5_fu_400_p3 <= 
        p_Result_4_fu_392_p3 when (comp_V_1_fu_378_p2(0) = '1') else 
        ret_4_fu_356_p3;
    ret_6_fu_444_p3 <= 
        p_Result_5_fu_436_p3 when (comp_V_2_fu_422_p2(0) = '1') else 
        ret_5_fu_400_p3;
    ret_7_fu_488_p3 <= 
        p_Result_6_fu_480_p3 when (comp_V_3_fu_466_p2(0) = '1') else 
        ret_6_fu_444_p3;
    ret_8_fu_562_p2 <= (select_ln356_fu_306_p3 xor opt1_V_9_fu_526_p3);
    ret_9_fu_596_p2 <= (zext_ln217_fu_568_p1 xor select_ln359_5_fu_588_p3);
    ret_fu_252_p2 <= (val_V_84_fu_246_p2 or p_Result_2_fu_234_p3);
    roundedResult_V_fu_1832_p2 <= std_logic_vector(unsigned(unroundedResult_V_fu_1784_p4) + unsigned(zext_ln217_6_fu_1828_p1));
    select_ln356_1_fu_722_p3 <= 
        ap_const_lv29_1FFFFFFF when (tmp_10_fu_706_p3(0) = '1') else 
        ap_const_lv29_0;
    select_ln356_fu_306_p3 <= 
        ap_const_lv29_1FFFFFFF when (tmp_1_fu_290_p3(0) = '1') else 
        ap_const_lv29_0;
    select_ln359_10_fu_844_p3 <= 
        ap_const_lv4_F when (tmp_10_fu_706_p3(0) = '1') else 
        ap_const_lv4_0;
    select_ln359_11_fu_888_p3 <= 
        ap_const_lv2_3 when (tmp_10_fu_706_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_12_fu_1004_p3 <= 
        ap_const_lv6_3F when (r_3_fu_998_p2(0) = '1') else 
        ap_const_lv6_0;
    select_ln359_13_fu_1028_p3 <= 
        ap_const_lv2_3 when (ext_1_fu_686_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_14_fu_1358_p3 <= 
        ap_const_lv9_1FF when (r_7_fu_1352_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln359_15_fu_1512_p3 <= 
        ap_const_lv2_3 when (tmp_28_fu_1504_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_1_fu_340_p3 <= 
        ap_const_lv16_FFFF when (tmp_1_fu_290_p3(0) = '1') else 
        ap_const_lv16_0;
    select_ln359_2_fu_384_p3 <= 
        ap_const_lv8_FF when (tmp_1_fu_290_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_3_fu_428_p3 <= 
        ap_const_lv4_F when (tmp_1_fu_290_p3(0) = '1') else 
        ap_const_lv4_0;
    select_ln359_4_fu_472_p3 <= 
        ap_const_lv2_3 when (tmp_1_fu_290_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_5_fu_588_p3 <= 
        ap_const_lv6_3F when (r_1_fu_582_p2(0) = '1') else 
        ap_const_lv6_0;
    select_ln359_6_fu_612_p3 <= 
        ap_const_lv2_3 when (ext_fu_270_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_7_fu_714_p3 <= 
        ap_const_lv30_3FFFFFFF when (tmp_10_fu_706_p3(0) = '1') else 
        ap_const_lv30_0;
    select_ln359_8_fu_756_p3 <= 
        ap_const_lv16_FFFF when (tmp_10_fu_706_p3(0) = '1') else 
        ap_const_lv16_0;
    select_ln359_9_fu_800_p3 <= 
        ap_const_lv8_FF when (tmp_10_fu_706_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_fu_298_p3 <= 
        ap_const_lv30_3FFFFFFF when (tmp_1_fu_290_p3(0) = '1') else 
        ap_const_lv30_0;
    select_ln416_fu_1434_p3 <= 
        ap_const_lv37_EF0000000 when (p_Result_19_fu_1152_p3(0) = '1') else 
        ap_const_lv37_F08000000;
        sext_ln217_fu_1380_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln_fu_1372_p3),7));

        sext_ln225_2_fu_1266_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(exp1_V_fu_1250_p3),9));

        sext_ln225_3_fu_1270_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(exp2_V_fu_1258_p3),9));

        sext_ln312_1_fu_1684_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_33_fu_1674_p4),44));

        sext_ln312_fu_1622_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_31_fu_1606_p7),80));

    shift_high_V_1_fu_1688_p4 <= opt1_V_13_fu_1582_p3(2 downto 1);
    shift_high_V_fu_1626_p4 <= opt1_V_13_fu_1582_p3(4 downto 3);
    shifted_V_3_fu_1720_p4 <= r_12_fu_1714_p2(37 downto 6);
    shifted_V_fu_1654_p4 <= r_11_fu_1648_p2(55 downto 24);
    shifted_out_V_1_fu_1730_p1 <= r_12_fu_1714_p2(6 - 1 downto 0);
    shifted_out_V_3_fu_1760_p1 <= r_13_fu_1754_p2(1 - 1 downto 0);
    shifted_out_V_fu_1664_p1 <= r_11_fu_1648_p2(24 - 1 downto 0);
    significand_V_fu_1500_p1 <= opt1_V_12_fu_1484_p3(27 - 1 downto 0);
    tmp_10_fu_706_p3 <= in2(30 downto 30);
    tmp_15_fu_912_p3 <= ret_18_fu_904_p3(29 downto 29);
    tmp_18_fu_1196_p3 <= ret_24_fu_1146_p2(55 downto 55);
    tmp_1_fu_290_p3 <= in1(30 downto 30);
    tmp_22_fu_1330_p3 <= opt1_V_11_fu_1242_p3(55 downto 55);
    tmp_23_fu_1344_p3 <= res_14_fu_1304_p3(8 downto 8);
    tmp_25_fu_1458_p4 <= opt1_V_11_fu_1242_p3(55 downto 28);
    tmp_28_fu_1504_p3 <= opt1_V_12_fu_1484_p3(28 downto 28);
    tmp_30_fu_1544_p3 <= opt1_V_12_fu_1484_p3(36 downto 36);
    tmp_44_fu_1862_p3 <= opt1_V_12_fu_1484_p3(27 downto 27);
    tmp_6_fu_514_p3 <= (trunc_ln312_fu_510_p1 & p_Result_2_fu_234_p3);
    tmp_7_fu_496_p3 <= ret_7_fu_488_p3(29 downto 29);
    tmp_8_fu_930_p3 <= (trunc_ln312_1_fu_926_p1 & p_Result_10_fu_650_p3);
    tmp_fu_1168_p3 <= ret_24_fu_1146_p2(57 downto 57);
    top_is_leading_V_1_fu_920_p2 <= (tmp_15_fu_912_p3 xor ap_const_lv1_1);
    top_is_leading_V_fu_504_p2 <= (tmp_7_fu_496_p3 xor ap_const_lv1_1);
    trunc_ln312_1_fu_926_p1 <= ret_18_fu_904_p3(28 - 1 downto 0);
    trunc_ln312_fu_510_p1 <= ret_7_fu_488_p3(28 - 1 downto 0);
    trunc_ln422_1_fu_938_p1 <= ret_18_fu_904_p3(29 - 1 downto 0);
    trunc_ln422_fu_522_p1 <= ret_7_fu_488_p3(29 - 1 downto 0);
    unroundedResult_V_fu_1784_p4 <= r_13_fu_1754_p2(32 downto 2);
    upper_V_1_fu_364_p4 <= ret_4_fu_356_p3(29 downto 22);
    upper_V_2_fu_408_p4 <= ret_5_fu_400_p3(29 downto 26);
    upper_V_4_fu_736_p4 <= ret_14_fu_730_p2(29 downto 14);
    upper_V_5_fu_780_p4 <= ret_15_fu_772_p3(29 downto 22);
    upper_V_6_fu_824_p4 <= ret_16_fu_816_p3(29 downto 26);
    upper_V_fu_320_p4 <= ret_3_fu_314_p2(29 downto 14);
    val_V_84_fu_246_p2 <= "0" when (val_V_fu_242_p1 = ap_const_lv30_0) else "1";
    val_V_85_fu_452_p4 <= ret_6_fu_444_p3(29 downto 28);
    val_V_86_fu_548_p2 <= "1" when (p_Result_7_fu_534_p6 = ap_const_lv5_1F) else "0";
    val_V_87_fu_658_p1 <= in2(30 - 1 downto 0);
    val_V_88_fu_662_p2 <= "0" when (val_V_87_fu_658_p1 = ap_const_lv30_0) else "1";
    val_V_89_fu_868_p4 <= ret_17_fu_860_p3(29 downto 28);
    val_V_90_fu_964_p2 <= "1" when (p_Result_15_fu_950_p6 = ap_const_lv5_1F) else "0";
    val_V_91_fu_1324_p2 <= "0" when (p_what2_s_fu_1320_p1 = ap_const_lv27_0) else "1";
    val_V_92_fu_1454_p1 <= res_14_fu_1304_p3(8 - 1 downto 0);
    val_V_93_fu_1668_p2 <= "0" when (shifted_out_V_fu_1664_p1 = ap_const_lv24_0) else "1";
    val_V_94_fu_1698_p1 <= opt1_V_13_fu_1582_p3(1 - 1 downto 0);
    val_V_95_fu_1734_p2 <= "0" when (shifted_out_V_1_fu_1730_p1 = ap_const_lv6_0) else "1";
    val_V_fu_242_p1 <= in1(30 - 1 downto 0);
    xor_ln1527_1_fu_694_p2 <= (ext_1_fu_686_p3 xor ap_const_lv1_1);
    xor_ln1527_fu_278_p2 <= (ext_fu_270_p3 xor ap_const_lv1_1);
    xor_ln939_3_fu_992_p2 <= (tmp_10_fu_706_p3 xor ext_1_fu_686_p3);
    xor_ln939_fu_576_p2 <= (tmp_1_fu_290_p3 xor ext_fu_270_p3);
    zext_ln217_1_fu_984_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_13_fu_970_p3),6));
    zext_ln217_2_fu_1278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_25_fu_1190_p2),2));
    zext_ln217_3_fu_1294_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln217_1_fu_1288_p2),9));
    zext_ln217_4_fu_1384_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln217_fu_1380_p1),9));
    zext_ln217_5_fu_1450_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_15_fu_1442_p3),40));
    zext_ln217_6_fu_1828_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_36_fu_1822_p2),31));
    zext_ln217_fu_568_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_12_fu_554_p3),6));
    zext_ln306_fu_1274_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_27_fu_1210_p2),2));
    zext_ln978_1_fu_1710_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_34_fu_1702_p3),44));
    zext_ln978_2_fu_1750_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val_V_94_fu_1698_p1),34));
    zext_ln978_fu_1644_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_32_fu_1636_p3),80));
end behav;
