-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity posit_comp_mul is
port (
    ap_local_block : OUT STD_LOGIC;
    ap_local_deadlock : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in1 : IN STD_LOGIC_VECTOR (15 downto 0);
    in2 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of posit_comp_mul is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "posit_comp_mul_posit_comp_mul,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvf1517-3-e,HLS_INPUT_CLOCK=10000.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=14.125542,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=897,HLS_VERSION=2021_2}";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv14_3FFF : STD_LOGIC_VECTOR (13 downto 0) := "11111111111111";
    constant ap_const_lv13_1FFF : STD_LOGIC_VECTOR (12 downto 0) := "1111111111111";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv20_8F000 : STD_LOGIC_VECTOR (19 downto 0) := "10001111000000000000";
    constant ap_const_lv20_90800 : STD_LOGIC_VECTOR (19 downto 0) := "10010000100000000000";
    constant ap_const_lv20_6F000 : STD_LOGIC_VECTOR (19 downto 0) := "01101111000000000000";
    constant ap_const_lv20_70800 : STD_LOGIC_VECTOR (19 downto 0) := "01110000100000000000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";

    signal val_V_76_fu_224_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_77_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_fu_216_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_208_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ext_fu_252_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1542_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_272_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_fu_280_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_3_fu_296_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_fu_302_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lower_V_fu_312_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln359_1_fu_322_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal comp_V_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_3_fu_330_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_4_fu_338_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_1_fu_346_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal lower_V_1_fu_356_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln359_2_fu_366_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal comp_V_1_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_4_fu_374_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_5_fu_382_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_78_fu_390_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lower_V_2_fu_400_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln359_3_fu_410_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal comp_V_2_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_5_fu_418_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_6_fu_426_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_6_fu_434_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln312_fu_448_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln422_fu_460_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_5_fu_452_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal top_is_leading_V_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_6_fu_472_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal val_V_79_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_11_fu_464_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln356_fu_288_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_12_fu_490_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ret_7_fu_498_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal xor_ln954_fu_512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_fu_518_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln223_fu_504_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln359_4_fu_524_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal es_V_fu_538_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln359_5_fu_548_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_1_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_8_fu_532_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_9_fu_556_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_2_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fraction_V_fu_508_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal val_V_80_fu_594_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_81_fu_598_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_fu_586_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_10_fu_604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_fu_578_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_2_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ext_1_fu_622_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1542_1_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_642_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_6_fu_650_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_13_fu_666_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_3_fu_672_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lower_V_3_fu_682_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln359_7_fu_692_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal comp_V_3_fu_686_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_10_fu_700_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_14_fu_708_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_4_fu_716_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal lower_V_4_fu_726_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln359_8_fu_736_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal comp_V_4_fu_730_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_11_fu_744_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_15_fu_752_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_fu_760_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lower_V_5_fu_770_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln359_9_fu_780_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal comp_V_5_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_12_fu_788_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_16_fu_796_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_13_fu_804_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln312_1_fu_818_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln422_1_fu_830_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_7_fu_822_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal top_is_leading_V_1_fu_812_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_13_fu_842_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal val_V_82_fu_854_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_13_fu_834_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln356_1_fu_658_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_14_fu_860_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ret_17_fu_868_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal xor_ln954_3_fu_882_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_3_fu_888_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln223_1_fu_874_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln359_10_fu_894_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal es_V_1_fu_908_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln359_11_fu_918_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_11_fu_616_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_18_fu_902_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_19_fu_926_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_12_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fraction_V_1_fu_878_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_14_fu_932_p7 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_Result_7_fu_562_p7 : STD_LOGIC_VECTOR (20 downto 0);
    signal or_ln1543_fu_948_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal and_ln_fu_962_p6 : STD_LOGIC_VECTOR (20 downto 0);
    signal and_ln1543_1_fu_982_p6 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_4_fu_976_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_5_fu_996_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_15_fu_1008_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Result_16_fu_1018_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_22_fu_1716_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_fu_1050_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_19_fu_1063_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_6_fu_1057_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_1076_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_23_fu_1070_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_24_fu_1083_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_18_fu_1043_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_26_fu_1095_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_bits_V_fu_1101_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal ret_25_fu_1089_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_20_fu_1104_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Result_21_fu_1112_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal exp1_V_fu_1128_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal exp2_V_fu_1136_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln232_2_fu_1144_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln232_3_fu_1148_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln223_2_fu_1156_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln306_fu_1152_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln223_1_fu_1166_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln223_4_fu_1172_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln223_fu_1160_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_21_fu_1002_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal expSumVal_V_fu_1176_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal res_15_fu_1120_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_what2_s_fu_1198_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_20_fu_1208_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_17_fu_1036_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_16_fu_1182_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_fu_1222_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_7_fu_1230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_12_fu_1236_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln_fu_1250_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln223_fu_1258_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln223_5_fu_1262_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_27_fu_1244_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_s_fu_1266_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_20_fu_954_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_9_fu_1216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_8_fu_1280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1542_fu_1286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_23_fu_1272_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_28_fu_1292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_29_fu_1298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln416_fu_1312_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal res_fu_1304_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal res_17_fu_1320_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Result_22_fu_1190_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal resultStickyBit_V_fu_1202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exp_V_fu_1332_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_24_fu_1336_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln223_6_fu_1328_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal p_Result_24_fu_1346_p7 : STD_LOGIC_VECTOR (22 downto 0);
    signal res_18_fu_1362_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_28_fu_1382_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal es_wo_xor_V_fu_1398_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln359_13_fu_1390_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_30_fu_1422_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_31_fu_1430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal low_k_V_fu_1444_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_26_fu_1414_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_10_fu_1454_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln312_fu_1436_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_28_fu_1476_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_30_fu_1408_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal significand_V_fu_1378_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_27_fu_1468_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_29_fu_1484_p7 : STD_LOGIC_VECTOR (28 downto 0);
    signal res_19_fu_1460_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1508_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_30_fu_1518_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln312_fu_1500_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal zext_ln993_fu_1526_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal r_11_fu_1530_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal shifted_out_V_fu_1536_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_2_fu_1546_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_31_fu_1556_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal shift_low_V_fu_1504_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln993_fu_1566_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln993_1_fu_1570_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal lshr_ln993_fu_1574_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_out_V_1_fu_1580_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_12_fu_1584_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_83_fu_1540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_33_fu_1622_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_34_fu_1614_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1543_7_fu_1630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_32_fu_1590_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_32_fu_1596_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_33_fu_1636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_34_fu_1642_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal unroundedResult_V_fu_1604_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln223_3_fu_1648_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Result_25_fu_1370_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal roundedResult_V_fu_1652_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Result_36_fu_1666_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_fu_1682_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1542_fu_1690_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_35_fu_1696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_36_fu_1702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_37_fu_1674_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_35_fu_1658_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component posit_comp_mul_mul_mul_13s_13s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (12 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;



begin
    mul_mul_13s_13s_26_1_1_U1 : component posit_comp_mul_mul_mul_13s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 13,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => p_Result_16_fu_1018_p4,
        din1 => p_Result_15_fu_1008_p4,
        dout => ret_22_fu_1716_p2);




    add_ln223_1_fu_1166_p2 <= std_logic_vector(unsigned(zext_ln223_2_fu_1156_p1) + unsigned(zext_ln306_fu_1152_p1));
    add_ln223_fu_1160_p2 <= std_logic_vector(signed(sext_ln232_2_fu_1144_p1) + signed(sext_ln232_3_fu_1148_p1));
    and_ln1542_fu_1286_p2 <= (r_9_fu_1216_p2 and r_8_fu_1280_p2);
    and_ln1543_1_fu_982_p6 <= ((((ret_11_fu_616_p2 & ap_const_lv7_0) & p_Result_8_fu_578_p3) & ret_12_fu_636_p2) & ap_const_lv11_0);
    and_ln_fu_962_p6 <= ((((ret_1_fu_246_p2 & ap_const_lv7_0) & p_Result_s_fu_208_p3) & ret_2_fu_266_p2) & ap_const_lv11_0);
    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_local_block <= ap_const_logic_0;
    ap_local_deadlock <= ap_const_logic_0;
    ap_ready <= ap_start;
    ap_return <= 
        p_Result_37_fu_1674_p3 when (ret_36_fu_1702_p2(0) = '1') else 
        p_Result_35_fu_1658_p3;
    comp_V_1_fu_360_p2 <= "1" when (upper_V_1_fu_346_p4 = ap_const_lv4_0) else "0";
    comp_V_2_fu_404_p2 <= "1" when (val_V_78_fu_390_p4 = ap_const_lv2_0) else "0";
    comp_V_3_fu_686_p2 <= "1" when (upper_V_3_fu_672_p4 = ap_const_lv8_0) else "0";
    comp_V_4_fu_730_p2 <= "1" when (upper_V_4_fu_716_p4 = ap_const_lv4_0) else "0";
    comp_V_5_fu_774_p2 <= "1" when (val_V_fu_760_p4 = ap_const_lv2_0) else "0";
    comp_V_fu_316_p2 <= "1" when (upper_V_fu_302_p4 = ap_const_lv8_0) else "0";
    es_V_1_fu_908_p4 <= ret_17_fu_868_p2(12 downto 11);
    es_V_fu_538_p4 <= ret_7_fu_498_p2(12 downto 11);
    es_wo_xor_V_fu_1398_p4 <= res_18_fu_1362_p3(14 downto 13);
    exp1_V_fu_1128_p3 <= (ret_8_fu_532_p2 & ret_9_fu_556_p2);
    exp2_V_fu_1136_p3 <= (ret_18_fu_902_p2 & ret_19_fu_926_p2);
    expSumVal_V_fu_1176_p2 <= std_logic_vector(unsigned(zext_ln223_4_fu_1172_p1) + unsigned(add_ln223_fu_1160_p2));
    exp_V_fu_1332_p1 <= res_16_fu_1182_p3(7 - 1 downto 0);
    ext_1_fu_622_p3 <= in2(15 downto 15);
    ext_fu_252_p3 <= in1(15 downto 15);
    fraction_V_1_fu_878_p1 <= ret_17_fu_868_p2(11 - 1 downto 0);
    fraction_V_fu_508_p1 <= ret_7_fu_498_p2(11 - 1 downto 0);
    last_bits_V_fu_1101_p1 <= ret_22_fu_1716_p2(23 - 1 downto 0);
    low_k_V_fu_1444_p4 <= res_18_fu_1362_p3(18 downto 15);
    lower_V_1_fu_356_p1 <= ret_4_fu_338_p3(10 - 1 downto 0);
    lower_V_2_fu_400_p1 <= ret_5_fu_382_p3(12 - 1 downto 0);
    lower_V_3_fu_682_p1 <= ret_13_fu_666_p2(6 - 1 downto 0);
    lower_V_4_fu_726_p1 <= ret_14_fu_708_p3(10 - 1 downto 0);
    lower_V_5_fu_770_p1 <= ret_15_fu_752_p3(12 - 1 downto 0);
    lower_V_fu_312_p1 <= ret_3_fu_296_p2(6 - 1 downto 0);
    lshr_ln993_fu_1574_p2 <= std_logic_vector(shift_right(unsigned(sext_ln993_fu_1566_p1),to_integer(unsigned('0' & zext_ln993_1_fu_1570_p1(22-1 downto 0)))));
    or_ln1542_fu_1690_p2 <= (tmp_42_fu_1682_p3 or tmp_28_fu_1382_p3);
    or_ln1543_7_fu_1630_p2 <= (p_Result_34_fu_1614_p3 or p_Result_33_fu_1622_p3);
    or_ln1543_fu_948_p2 <= (p_Result_7_fu_562_p7 or p_Result_14_fu_932_p7);
    or_ln_fu_1250_p3 <= (ap_const_lv3_4 & r_7_fu_1230_p2);
    p_Result_10_fu_700_p3 <= (lower_V_3_fu_682_p1 & select_ln359_7_fu_692_p3);
    p_Result_11_fu_744_p3 <= (lower_V_4_fu_726_p1 & select_ln359_8_fu_736_p3);
    p_Result_12_fu_788_p3 <= (lower_V_5_fu_770_p1 & select_ln359_9_fu_780_p3);
    p_Result_13_fu_842_p5 <= (((comp_V_3_fu_686_p2 & comp_V_4_fu_730_p2) & comp_V_5_fu_774_p2) & top_is_leading_V_1_fu_812_p2);
    p_Result_14_fu_932_p7 <= (((((ret_11_fu_616_p2 & ret_18_fu_902_p2) & ret_19_fu_926_p2) & p_Result_8_fu_578_p3) & ret_12_fu_636_p2) & fraction_V_1_fu_878_p1);
    p_Result_15_fu_1008_p4 <= ((p_Result_s_fu_208_p3 & ret_2_fu_266_p2) & fraction_V_fu_508_p1);
    p_Result_16_fu_1018_p4 <= ((p_Result_8_fu_578_p3 & ret_12_fu_636_p2) & fraction_V_1_fu_878_p1);
    p_Result_17_fu_1036_p3 <= ret_22_fu_1716_p2(25 downto 25);
    p_Result_18_fu_1043_p3 <= ret_22_fu_1716_p2(23 downto 23);
    p_Result_19_fu_1063_p3 <= ret_22_fu_1716_p2(24 downto 24);
    p_Result_20_fu_1104_p3 <= (ret_26_fu_1095_p2 & last_bits_V_fu_1101_p1);
    p_Result_21_fu_1112_p3 <= (last_bits_V_fu_1101_p1 & ap_const_lv1_0);
    p_Result_22_fu_1190_p3 <= res_15_fu_1120_p3(11 downto 11);
    p_Result_23_fu_1272_p3 <= p_Val2_s_fu_1266_p2(7 downto 7);
    p_Result_24_fu_1346_p7 <= (((((p_Result_22_fu_1190_p3 & resultStickyBit_V_fu_1202_p2) & ret_20_fu_954_p3) & exp_V_fu_1332_p1) & p_Result_17_fu_1036_p3) & tmp_24_fu_1336_p4);
    p_Result_25_fu_1370_p3 <= res_18_fu_1362_p3(12 downto 12);
    p_Result_26_fu_1414_p3 <= res_18_fu_1362_p3(19 downto 19);
    p_Result_27_fu_1468_p3 <= res_18_fu_1362_p3(22 downto 22);
    p_Result_28_fu_1476_p3 <= select_ln312_fu_1436_p3(1 downto 1);
    p_Result_29_fu_1484_p7 <= (((((p_Result_28_fu_1476_p3 & select_ln312_fu_1436_p3) & ret_30_fu_1408_p2) & significand_V_fu_1378_p1) & p_Result_27_fu_1468_p3) & ap_const_lv12_0);
    p_Result_2_fu_216_p3 <= in1(14 downto 14);
    p_Result_30_fu_1518_p3 <= (tmp_s_fu_1508_p4 & ap_const_lv2_0);
    p_Result_31_fu_1556_p4 <= ((p_Result_28_fu_1476_p3 & tmp_2_fu_1546_p4) & ap_const_lv3_0);
    p_Result_32_fu_1596_p3 <= lshr_ln993_fu_1574_p2(3 downto 3);
    p_Result_33_fu_1622_p3 <= res_18_fu_1362_p3(21 downto 21);
    p_Result_34_fu_1614_p3 <= lshr_ln993_fu_1574_p2(4 downto 4);
    p_Result_35_fu_1658_p3 <= (p_Result_25_fu_1370_p3 & roundedResult_V_fu_1652_p2);
    p_Result_36_fu_1666_p3 <= res_18_fu_1362_p3(20 downto 20);
    p_Result_37_fu_1674_p3 <= (p_Result_36_fu_1666_p3 & ap_const_lv15_0);
    p_Result_3_fu_330_p3 <= (lower_V_fu_312_p1 & select_ln359_1_fu_322_p3);
    p_Result_4_fu_374_p3 <= (lower_V_1_fu_356_p1 & select_ln359_2_fu_366_p3);
    p_Result_5_fu_418_p3 <= (lower_V_2_fu_400_p1 & select_ln359_3_fu_410_p3);
    p_Result_6_fu_472_p5 <= (((comp_V_fu_316_p2 & comp_V_1_fu_360_p2) & comp_V_2_fu_404_p2) & top_is_leading_V_fu_442_p2);
    p_Result_7_fu_562_p7 <= (((((ret_1_fu_246_p2 & ret_8_fu_532_p2) & ret_9_fu_556_p2) & p_Result_s_fu_208_p3) & ret_2_fu_266_p2) & fraction_V_fu_508_p1);
    p_Result_8_fu_578_p3 <= in2(15 downto 15);
    p_Result_9_fu_586_p3 <= in2(14 downto 14);
    p_Result_s_fu_208_p3 <= in1(15 downto 15);
    p_Val2_s_fu_1266_p2 <= std_logic_vector(unsigned(zext_ln223_5_fu_1262_p1) + unsigned(ret_27_fu_1244_p2));
    p_what2_s_fu_1198_p1 <= res_15_fu_1120_p3(11 - 1 downto 0);
    r_10_fu_1454_p2 <= (low_k_V_fu_1444_p4 xor ap_const_lv4_F);
    r_11_fu_1530_p2 <= std_logic_vector(shift_right(unsigned(sext_ln312_fu_1500_p1),to_integer(unsigned('0' & zext_ln993_fu_1526_p1(31-1 downto 0)))));
    r_12_fu_1584_p2 <= "0" when (shifted_out_V_1_fu_1580_p1 = ap_const_lv3_0) else "1";
    r_1_fu_518_p2 <= (xor_ln954_fu_512_p2 xor ap_const_lv1_1);
    r_2_fu_610_p2 <= (ret_10_fu_604_p2 xor ap_const_lv1_1);
    r_3_fu_888_p2 <= (xor_ln954_3_fu_882_p2 xor ap_const_lv1_1);
    r_4_fu_976_p2 <= "1" when (and_ln_fu_962_p6 = ap_const_lv21_0) else "0";
    r_5_fu_996_p2 <= "1" when (and_ln1543_1_fu_982_p6 = ap_const_lv21_0) else "0";
    r_6_fu_1057_p2 <= (tmp_fu_1050_p3 xor ap_const_lv1_1);
    r_7_fu_1230_p2 <= (tmp_21_fu_1222_p3 xor ap_const_lv1_1);
    r_8_fu_1280_p2 <= (ret_20_fu_954_p3 xor ap_const_lv1_1);
    r_9_fu_1216_p2 <= (tmp_20_fu_1208_p3 or p_Result_17_fu_1036_p3);
    r_fu_240_p2 <= (ret_fu_234_p2 xor ap_const_lv1_1);
    res_11_fu_464_p3 <= 
        trunc_ln422_fu_460_p1 when (tmp_6_fu_434_p3(0) = '1') else 
        tmp_5_fu_452_p3;
    res_12_fu_490_p3 <= 
        ap_const_lv4_E when (val_V_79_fu_484_p2(0) = '1') else 
        p_Result_6_fu_472_p5;
    res_13_fu_834_p3 <= 
        trunc_ln422_1_fu_830_p1 when (tmp_13_fu_804_p3(0) = '1') else 
        tmp_7_fu_822_p3;
    res_14_fu_860_p3 <= 
        ap_const_lv4_E when (val_V_82_fu_854_p2(0) = '1') else 
        p_Result_13_fu_842_p5;
    res_15_fu_1120_p3 <= 
        p_Result_20_fu_1104_p3 when (ret_25_fu_1089_p2(0) = '1') else 
        p_Result_21_fu_1112_p3;
    res_16_fu_1182_p3 <= 
        ap_const_lv8_0 when (ret_21_fu_1002_p2(0) = '1') else 
        expSumVal_V_fu_1176_p2;
    res_17_fu_1320_p3 <= 
        select_ln416_fu_1312_p3 when (ret_29_fu_1298_p2(0) = '1') else 
        res_fu_1304_p3;
    res_18_fu_1362_p3 <= 
        zext_ln223_6_fu_1328_p1 when (ret_28_fu_1292_p2(0) = '1') else 
        p_Result_24_fu_1346_p7;
    res_19_fu_1460_p3 <= 
        r_10_fu_1454_p2 when (p_Result_26_fu_1414_p3(0) = '1') else 
        low_k_V_fu_1444_p4;
    res_fu_1304_p3 <= 
        ap_const_lv20_8F000 when (p_Result_17_fu_1036_p3(0) = '1') else 
        ap_const_lv20_90800;
    resultStickyBit_V_fu_1202_p2 <= "0" when (p_what2_s_fu_1198_p1 = ap_const_lv11_0) else "1";
    ret_10_fu_604_p2 <= (val_V_81_fu_598_p2 or p_Result_9_fu_586_p3);
    ret_11_fu_616_p2 <= (r_2_fu_610_p2 and p_Result_8_fu_578_p3);
    ret_12_fu_636_p2 <= (xor_ln1542_1_fu_630_p2 and ret_10_fu_604_p2);
    ret_13_fu_666_p2 <= (val_V_80_fu_594_p1 xor select_ln359_6_fu_650_p3);
    ret_14_fu_708_p3 <= 
        p_Result_10_fu_700_p3 when (comp_V_3_fu_686_p2(0) = '1') else 
        ret_13_fu_666_p2;
    ret_15_fu_752_p3 <= 
        p_Result_11_fu_744_p3 when (comp_V_4_fu_730_p2(0) = '1') else 
        ret_14_fu_708_p3;
    ret_16_fu_796_p3 <= 
        p_Result_12_fu_788_p3 when (comp_V_5_fu_774_p2(0) = '1') else 
        ret_15_fu_752_p3;
    ret_17_fu_868_p2 <= (select_ln356_1_fu_658_p3 xor res_13_fu_834_p3);
    ret_18_fu_902_p2 <= (zext_ln223_1_fu_874_p1 xor select_ln359_10_fu_894_p3);
    ret_19_fu_926_p2 <= (select_ln359_11_fu_918_p3 xor es_V_1_fu_908_p4);
    ret_1_fu_246_p2 <= (r_fu_240_p2 and p_Result_s_fu_208_p3);
    ret_20_fu_954_p3 <= or_ln1543_fu_948_p2(20 downto 20);
    ret_21_fu_1002_p2 <= (r_5_fu_996_p2 or r_4_fu_976_p2);
    ret_23_fu_1070_p2 <= (r_6_fu_1057_p2 and p_Result_19_fu_1063_p3);
    ret_24_fu_1083_p2 <= (tmp_fu_1050_p3 xor tmp_16_fu_1076_p3);
    ret_25_fu_1089_p2 <= (ret_24_fu_1083_p2 or ret_23_fu_1070_p2);
    ret_26_fu_1095_p2 <= (ret_23_fu_1070_p2 or p_Result_18_fu_1043_p3);
    ret_27_fu_1244_p2 <= (select_ln359_12_fu_1236_p3 xor res_16_fu_1182_p3);
    ret_28_fu_1292_p2 <= (p_Result_23_fu_1272_p3 and and_ln1542_fu_1286_p2);
    ret_29_fu_1298_p2 <= (ret_28_fu_1292_p2 and r_7_fu_1230_p2);
    ret_2_fu_266_p2 <= (xor_ln1542_fu_260_p2 and ret_fu_234_p2);
    ret_30_fu_1408_p2 <= (select_ln359_13_fu_1390_p3 xor es_wo_xor_V_fu_1398_p4);
    ret_31_fu_1430_p2 <= (tmp_30_fu_1422_p3 xor tmp_28_fu_1382_p3);
    ret_32_fu_1590_p2 <= (val_V_83_fu_1540_p2 or r_12_fu_1584_p2);
    ret_33_fu_1636_p2 <= (ret_32_fu_1590_p2 or or_ln1543_7_fu_1630_p2);
    ret_34_fu_1642_p2 <= (ret_33_fu_1636_p2 and p_Result_32_fu_1596_p3);
    ret_35_fu_1696_p2 <= (or_ln1542_fu_1690_p2 xor ap_const_lv1_1);
    ret_36_fu_1702_p2 <= (ret_35_fu_1696_p2 or p_Result_36_fu_1666_p3);
    ret_3_fu_296_p2 <= (val_V_76_fu_224_p1 xor select_ln359_fu_280_p3);
    ret_4_fu_338_p3 <= 
        p_Result_3_fu_330_p3 when (comp_V_fu_316_p2(0) = '1') else 
        ret_3_fu_296_p2;
    ret_5_fu_382_p3 <= 
        p_Result_4_fu_374_p3 when (comp_V_1_fu_360_p2(0) = '1') else 
        ret_4_fu_338_p3;
    ret_6_fu_426_p3 <= 
        p_Result_5_fu_418_p3 when (comp_V_2_fu_404_p2(0) = '1') else 
        ret_5_fu_382_p3;
    ret_7_fu_498_p2 <= (select_ln356_fu_288_p3 xor res_11_fu_464_p3);
    ret_8_fu_532_p2 <= (zext_ln223_fu_504_p1 xor select_ln359_4_fu_524_p3);
    ret_9_fu_556_p2 <= (select_ln359_5_fu_548_p3 xor es_V_fu_538_p4);
    ret_fu_234_p2 <= (val_V_77_fu_228_p2 or p_Result_2_fu_216_p3);
    roundedResult_V_fu_1652_p2 <= std_logic_vector(unsigned(unroundedResult_V_fu_1604_p4) + unsigned(zext_ln223_3_fu_1648_p1));
    select_ln312_fu_1436_p3 <= 
        ap_const_lv2_1 when (ret_31_fu_1430_p2(0) = '1') else 
        ap_const_lv2_2;
    select_ln356_1_fu_658_p3 <= 
        ap_const_lv13_1FFF when (tmp_9_fu_642_p3(0) = '1') else 
        ap_const_lv13_0;
    select_ln356_fu_288_p3 <= 
        ap_const_lv13_1FFF when (tmp_1_fu_272_p3(0) = '1') else 
        ap_const_lv13_0;
    select_ln359_10_fu_894_p3 <= 
        ap_const_lv5_1F when (r_3_fu_888_p2(0) = '1') else 
        ap_const_lv5_0;
    select_ln359_11_fu_918_p3 <= 
        ap_const_lv2_3 when (ext_1_fu_622_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_12_fu_1236_p3 <= 
        ap_const_lv8_FF when (r_7_fu_1230_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_13_fu_1390_p3 <= 
        ap_const_lv2_3 when (tmp_28_fu_1382_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_1_fu_322_p3 <= 
        ap_const_lv8_FF when (tmp_1_fu_272_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_2_fu_366_p3 <= 
        ap_const_lv4_F when (tmp_1_fu_272_p3(0) = '1') else 
        ap_const_lv4_0;
    select_ln359_3_fu_410_p3 <= 
        ap_const_lv2_3 when (tmp_1_fu_272_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_4_fu_524_p3 <= 
        ap_const_lv5_1F when (r_1_fu_518_p2(0) = '1') else 
        ap_const_lv5_0;
    select_ln359_5_fu_548_p3 <= 
        ap_const_lv2_3 when (ext_fu_252_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_6_fu_650_p3 <= 
        ap_const_lv14_3FFF when (tmp_9_fu_642_p3(0) = '1') else 
        ap_const_lv14_0;
    select_ln359_7_fu_692_p3 <= 
        ap_const_lv8_FF when (tmp_9_fu_642_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_8_fu_736_p3 <= 
        ap_const_lv4_F when (tmp_9_fu_642_p3(0) = '1') else 
        ap_const_lv4_0;
    select_ln359_9_fu_780_p3 <= 
        ap_const_lv2_3 when (tmp_9_fu_642_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_fu_280_p3 <= 
        ap_const_lv14_3FFF when (tmp_1_fu_272_p3(0) = '1') else 
        ap_const_lv14_0;
    select_ln416_fu_1312_p3 <= 
        ap_const_lv20_6F000 when (p_Result_17_fu_1036_p3(0) = '1') else 
        ap_const_lv20_70800;
        sext_ln223_fu_1258_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln_fu_1250_p3),6));

        sext_ln232_2_fu_1144_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(exp1_V_fu_1128_p3),8));

        sext_ln232_3_fu_1148_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(exp2_V_fu_1136_p3),8));

        sext_ln312_fu_1500_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_29_fu_1484_p7),40));

        sext_ln993_fu_1566_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_31_fu_1556_p4),22));

    shift_low_V_fu_1504_p1 <= res_19_fu_1460_p3(2 - 1 downto 0);
    shifted_out_V_1_fu_1580_p1 <= lshr_ln993_fu_1574_p2(3 - 1 downto 0);
    shifted_out_V_fu_1536_p1 <= r_11_fu_1530_p2(12 - 1 downto 0);
    significand_V_fu_1378_p1 <= res_18_fu_1362_p3(11 - 1 downto 0);
    tmp_13_fu_804_p3 <= ret_16_fu_796_p3(13 downto 13);
    tmp_16_fu_1076_p3 <= ret_22_fu_1716_p2(23 downto 23);
    tmp_1_fu_272_p3 <= in1(14 downto 14);
    tmp_20_fu_1208_p3 <= res_15_fu_1120_p3(23 downto 23);
    tmp_21_fu_1222_p3 <= res_16_fu_1182_p3(7 downto 7);
    tmp_24_fu_1336_p4 <= res_15_fu_1120_p3(23 downto 12);
    tmp_28_fu_1382_p3 <= res_18_fu_1362_p3(12 downto 12);
    tmp_2_fu_1546_p4 <= r_11_fu_1530_p2(27 downto 12);
    tmp_30_fu_1422_p3 <= res_18_fu_1362_p3(19 downto 19);
    tmp_42_fu_1682_p3 <= res_18_fu_1362_p3(11 downto 11);
    tmp_5_fu_452_p3 <= (trunc_ln312_fu_448_p1 & p_Result_2_fu_216_p3);
    tmp_6_fu_434_p3 <= ret_6_fu_426_p3(13 downto 13);
    tmp_7_fu_822_p3 <= (trunc_ln312_1_fu_818_p1 & p_Result_9_fu_586_p3);
    tmp_9_fu_642_p3 <= in2(14 downto 14);
    tmp_fu_1050_p3 <= ret_22_fu_1716_p2(25 downto 25);
    tmp_s_fu_1508_p4 <= res_19_fu_1460_p3(3 downto 2);
    top_is_leading_V_1_fu_812_p2 <= (tmp_13_fu_804_p3 xor ap_const_lv1_1);
    top_is_leading_V_fu_442_p2 <= (tmp_6_fu_434_p3 xor ap_const_lv1_1);
    trunc_ln312_1_fu_818_p1 <= ret_16_fu_796_p3(12 - 1 downto 0);
    trunc_ln312_fu_448_p1 <= ret_6_fu_426_p3(12 - 1 downto 0);
    trunc_ln422_1_fu_830_p1 <= ret_16_fu_796_p3(13 - 1 downto 0);
    trunc_ln422_fu_460_p1 <= ret_6_fu_426_p3(13 - 1 downto 0);
    unroundedResult_V_fu_1604_p4 <= lshr_ln993_fu_1574_p2(18 downto 4);
    upper_V_1_fu_346_p4 <= ret_4_fu_338_p3(13 downto 10);
    upper_V_3_fu_672_p4 <= ret_13_fu_666_p2(13 downto 6);
    upper_V_4_fu_716_p4 <= ret_14_fu_708_p3(13 downto 10);
    upper_V_fu_302_p4 <= ret_3_fu_296_p2(13 downto 6);
    val_V_76_fu_224_p1 <= in1(14 - 1 downto 0);
    val_V_77_fu_228_p2 <= "0" when (val_V_76_fu_224_p1 = ap_const_lv14_0) else "1";
    val_V_78_fu_390_p4 <= ret_5_fu_382_p3(13 downto 12);
    val_V_79_fu_484_p2 <= "1" when (p_Result_6_fu_472_p5 = ap_const_lv4_F) else "0";
    val_V_80_fu_594_p1 <= in2(14 - 1 downto 0);
    val_V_81_fu_598_p2 <= "0" when (val_V_80_fu_594_p1 = ap_const_lv14_0) else "1";
    val_V_82_fu_854_p2 <= "1" when (p_Result_13_fu_842_p5 = ap_const_lv4_F) else "0";
    val_V_83_fu_1540_p2 <= "0" when (shifted_out_V_fu_1536_p1 = ap_const_lv12_0) else "1";
    val_V_fu_760_p4 <= ret_15_fu_752_p3(13 downto 12);
    xor_ln1542_1_fu_630_p2 <= (ext_1_fu_622_p3 xor ap_const_lv1_1);
    xor_ln1542_fu_260_p2 <= (ext_fu_252_p3 xor ap_const_lv1_1);
    xor_ln954_3_fu_882_p2 <= (tmp_9_fu_642_p3 xor ext_1_fu_622_p3);
    xor_ln954_fu_512_p2 <= (tmp_1_fu_272_p3 xor ext_fu_252_p3);
    zext_ln223_1_fu_874_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_14_fu_860_p3),5));
    zext_ln223_2_fu_1156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_23_fu_1070_p2),2));
    zext_ln223_3_fu_1648_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_34_fu_1642_p2),15));
    zext_ln223_4_fu_1172_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln223_1_fu_1166_p2),8));
    zext_ln223_5_fu_1262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln223_fu_1258_p1),8));
    zext_ln223_6_fu_1328_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_17_fu_1320_p3),23));
    zext_ln223_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_12_fu_490_p3),5));
    zext_ln306_fu_1152_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_25_fu_1089_p2),2));
    zext_ln993_1_fu_1570_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shift_low_V_fu_1504_p1),22));
    zext_ln993_fu_1526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_30_fu_1518_p3),40));
end behav;
