-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity posit_comp_mul is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in1 : IN STD_LOGIC_VECTOR (15 downto 0);
    in2 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of posit_comp_mul is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "posit_comp_mul_posit_comp_mul,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=10000.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=29.380400,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=859,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv14_3FFF : STD_LOGIC_VECTOR (13 downto 0) := "11111111111111";
    constant ap_const_lv13_1FFF : STD_LOGIC_VECTOR (12 downto 0) := "1111111111111";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv20_8E000 : STD_LOGIC_VECTOR (19 downto 0) := "10001110000000000000";
    constant ap_const_lv20_91000 : STD_LOGIC_VECTOR (19 downto 0) := "10010001000000000000";
    constant ap_const_lv20_6E000 : STD_LOGIC_VECTOR (19 downto 0) := "01101110000000000000";
    constant ap_const_lv20_71000 : STD_LOGIC_VECTOR (19 downto 0) := "01110001000000000000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal val_V_92_fu_216_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_93_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_fu_208_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_200_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_244_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1527_fu_252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_264_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_fu_272_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_3_fu_288_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_fu_294_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lower_V_fu_304_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln359_1_fu_314_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal comp_V_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_3_fu_322_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_4_fu_330_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_1_fu_338_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal lower_V_1_fu_348_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln359_2_fu_358_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal comp_V_1_fu_352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_4_fu_366_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_5_fu_374_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_94_fu_382_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lower_V_2_fu_392_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln359_3_fu_402_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal comp_V_2_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_5_fu_410_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_6_fu_418_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_6_fu_426_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln312_fu_440_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln422_fu_452_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_5_fu_444_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal top_is_leading_V_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_6_fu_464_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal val_V_95_fu_476_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal opt1_V_9_fu_456_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln356_fu_280_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_12_fu_482_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ret_7_fu_490_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal xor_ln939_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln217_fu_496_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln359_4_fu_516_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_V_96_fu_530_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_1_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_8_fu_524_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_9_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_2_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fraction_V_fu_500_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal val_V_97_fu_576_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_98_fu_580_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_fu_568_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_10_fu_586_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_fu_560_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_2_fu_592_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_604_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1527_1_fu_612_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_624_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_5_fu_632_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_13_fu_648_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_3_fu_654_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lower_V_3_fu_664_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln359_6_fu_674_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal comp_V_3_fu_668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_10_fu_682_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_14_fu_690_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_4_fu_698_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal lower_V_4_fu_708_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln359_7_fu_718_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal comp_V_4_fu_712_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_11_fu_726_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_15_fu_734_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_fu_742_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lower_V_5_fu_752_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln359_8_fu_762_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal comp_V_5_fu_756_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_12_fu_770_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_16_fu_778_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_18_fu_786_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln312_1_fu_800_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln422_1_fu_812_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_7_fu_804_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal top_is_leading_V_1_fu_794_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_13_fu_824_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal val_V_99_fu_836_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal opt1_V_10_fu_816_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln356_1_fu_640_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_13_fu_842_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ret_17_fu_850_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal xor_ln939_3_fu_864_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_3_fu_870_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln217_1_fu_856_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln359_9_fu_876_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_V_100_fu_890_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_11_fu_598_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_18_fu_884_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_19_fu_898_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_12_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fraction_V_1_fu_860_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_14_fu_904_p7 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_Result_7_fu_544_p7 : STD_LOGIC_VECTOR (20 downto 0);
    signal or_ln1528_fu_920_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal and_ln_fu_934_p6 : STD_LOGIC_VECTOR (20 downto 0);
    signal and_ln1528_1_fu_954_p6 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_4_fu_948_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_5_fu_968_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_15_fu_980_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_16_fu_990_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_22_fu_1678_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_27_fu_1022_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_19_fu_1035_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_6_fu_1029_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_1048_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_23_fu_1042_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_24_fu_1055_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_18_fu_1015_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_26_fu_1067_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_bits_V_fu_1073_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal ret_25_fu_1061_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_20_fu_1076_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Result_21_fu_1084_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal exp1_V_fu_1100_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal exp2_V_fu_1108_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln225_2_fu_1116_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln225_3_fu_1120_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln217_2_fu_1128_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln306_fu_1124_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln217_1_fu_1138_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln217_4_fu_1144_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln217_fu_1132_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ret_21_fu_974_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal expSumVal_V_fu_1148_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal opt1_V_11_fu_1092_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_what2_s_fu_1170_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_33_fu_1180_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_17_fu_1008_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_14_fu_1154_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_34_fu_1194_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_7_fu_1202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_10_fu_1208_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln_fu_1222_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln217_fu_1230_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln217_5_fu_1234_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ret_27_fu_1216_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Val2_s_fu_1238_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ret_20_fu_926_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_9_fu_1188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_8_fu_1252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1527_fu_1258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_23_fu_1244_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_28_fu_1264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_29_fu_1270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln416_fu_1284_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal res_fu_1276_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal res_15_fu_1292_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Result_22_fu_1162_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_101_fu_1174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_102_fu_1304_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_36_fu_1308_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln217_6_fu_1300_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal p_Result_24_fu_1318_p7 : STD_LOGIC_VECTOR (22 downto 0);
    signal opt1_V_12_fu_1334_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal es_wo_xor_V_fu_1354_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_1362_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_fu_1384_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_31_fu_1392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal low_k_V_fu_1406_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_26_fu_1376_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_10_fu_1416_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal res_16_fu_1398_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_28_fu_1438_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_30_fu_1370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal significand_V_fu_1350_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_27_fu_1430_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_29_fu_1446_p7 : STD_LOGIC_VECTOR (28 downto 0);
    signal opt1_V_13_fu_1422_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal shift_high_V_fu_1466_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_30_fu_1480_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln312_fu_1462_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal zext_ln978_fu_1488_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal r_11_fu_1492_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal shifted_out_V_fu_1508_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal shifted_V_fu_1498_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_31_fu_1518_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal shift_low_V_fu_1476_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln978_fu_1528_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln978_1_fu_1532_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal lshr_ln978_fu_1536_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_out_V_1_fu_1542_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_12_fu_1546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_103_fu_1512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_33_fu_1584_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_34_fu_1576_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1528_7_fu_1592_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_32_fu_1552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_32_fu_1558_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_33_fu_1598_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_34_fu_1604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal unroundedResult_V_fu_1566_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln217_3_fu_1610_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Result_25_fu_1342_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal roundedResult_V_fu_1614_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Result_36_fu_1628_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_fu_1644_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1527_fu_1652_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_35_fu_1658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_36_fu_1664_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_37_fu_1636_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_35_fu_1620_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component posit_comp_mul_mul_mul_14s_14s_28_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (13 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;



begin
    mul_mul_14s_14s_28_1_1_U1 : component posit_comp_mul_mul_mul_14s_14s_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 14,
        dout_WIDTH => 28)
    port map (
        din0 => p_Result_16_fu_990_p4,
        din1 => p_Result_15_fu_980_p4,
        dout => ret_22_fu_1678_p2);




    add_ln217_1_fu_1138_p2 <= std_logic_vector(unsigned(zext_ln217_2_fu_1128_p1) + unsigned(zext_ln306_fu_1124_p1));
    add_ln217_fu_1132_p2 <= std_logic_vector(signed(sext_ln225_2_fu_1116_p1) + signed(sext_ln225_3_fu_1120_p1));
    and_ln1527_fu_1258_p2 <= (r_9_fu_1188_p2 and r_8_fu_1252_p2);
    and_ln1528_1_fu_954_p6 <= ((((ret_11_fu_598_p2 & ap_const_lv6_0) & p_Result_8_fu_560_p3) & ret_12_fu_618_p2) & ap_const_lv12_0);
    and_ln_fu_934_p6 <= ((((ret_1_fu_238_p2 & ap_const_lv6_0) & p_Result_s_fu_200_p3) & ret_2_fu_258_p2) & ap_const_lv12_0);
    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_ready <= ap_start;
    ap_return <= 
        p_Result_37_fu_1636_p3 when (ret_36_fu_1664_p2(0) = '1') else 
        p_Result_35_fu_1620_p3;
    comp_V_1_fu_352_p2 <= "1" when (upper_V_1_fu_338_p4 = ap_const_lv4_0) else "0";
    comp_V_2_fu_396_p2 <= "1" when (val_V_94_fu_382_p4 = ap_const_lv2_0) else "0";
    comp_V_3_fu_668_p2 <= "1" when (upper_V_3_fu_654_p4 = ap_const_lv8_0) else "0";
    comp_V_4_fu_712_p2 <= "1" when (upper_V_4_fu_698_p4 = ap_const_lv4_0) else "0";
    comp_V_5_fu_756_p2 <= "1" when (val_V_fu_742_p4 = ap_const_lv2_0) else "0";
    comp_V_fu_308_p2 <= "1" when (upper_V_fu_294_p4 = ap_const_lv8_0) else "0";
    es_wo_xor_V_fu_1354_p3 <= opt1_V_12_fu_1334_p3(14 downto 14);
    exp1_V_fu_1100_p3 <= (ret_8_fu_524_p2 & ret_9_fu_538_p2);
    exp2_V_fu_1108_p3 <= (ret_18_fu_884_p2 & ret_19_fu_898_p2);
    expSumVal_V_fu_1148_p2 <= std_logic_vector(unsigned(zext_ln217_4_fu_1144_p1) + unsigned(add_ln217_fu_1132_p2));
    fraction_V_1_fu_860_p1 <= ret_17_fu_850_p2(12 - 1 downto 0);
    fraction_V_fu_500_p1 <= ret_7_fu_490_p2(12 - 1 downto 0);
    last_bits_V_fu_1073_p1 <= ret_22_fu_1678_p2(25 - 1 downto 0);
    low_k_V_fu_1406_p4 <= opt1_V_12_fu_1334_p3(18 downto 15);
    lower_V_1_fu_348_p1 <= ret_4_fu_330_p3(10 - 1 downto 0);
    lower_V_2_fu_392_p1 <= ret_5_fu_374_p3(12 - 1 downto 0);
    lower_V_3_fu_664_p1 <= ret_13_fu_648_p2(6 - 1 downto 0);
    lower_V_4_fu_708_p1 <= ret_14_fu_690_p3(10 - 1 downto 0);
    lower_V_5_fu_752_p1 <= ret_15_fu_734_p3(12 - 1 downto 0);
    lower_V_fu_304_p1 <= ret_3_fu_288_p2(6 - 1 downto 0);
    lshr_ln978_fu_1536_p2 <= std_logic_vector(shift_right(unsigned(sext_ln978_fu_1528_p1),to_integer(unsigned('0' & zext_ln978_1_fu_1532_p1(22-1 downto 0)))));
    opt1_V_10_fu_816_p3 <= 
        trunc_ln422_1_fu_812_p1 when (tmp_18_fu_786_p3(0) = '1') else 
        tmp_7_fu_804_p3;
    opt1_V_11_fu_1092_p3 <= 
        p_Result_20_fu_1076_p3 when (ret_25_fu_1061_p2(0) = '1') else 
        p_Result_21_fu_1084_p3;
    opt1_V_12_fu_1334_p3 <= 
        zext_ln217_6_fu_1300_p1 when (ret_28_fu_1264_p2(0) = '1') else 
        p_Result_24_fu_1318_p7;
    opt1_V_13_fu_1422_p3 <= 
        r_10_fu_1416_p2 when (p_Result_26_fu_1376_p3(0) = '1') else 
        low_k_V_fu_1406_p4;
    opt1_V_9_fu_456_p3 <= 
        trunc_ln422_fu_452_p1 when (tmp_6_fu_426_p3(0) = '1') else 
        tmp_5_fu_444_p3;
    or_ln1527_fu_1652_p2 <= (tmp_54_fu_1644_p3 or tmp_40_fu_1362_p3);
    or_ln1528_7_fu_1592_p2 <= (p_Result_34_fu_1576_p3 or p_Result_33_fu_1584_p3);
    or_ln1528_fu_920_p2 <= (p_Result_7_fu_544_p7 or p_Result_14_fu_904_p7);
    or_ln_fu_1222_p3 <= (ap_const_lv2_2 & r_7_fu_1202_p2);
    p_Result_10_fu_682_p3 <= (lower_V_3_fu_664_p1 & select_ln359_6_fu_674_p3);
    p_Result_11_fu_726_p3 <= (lower_V_4_fu_708_p1 & select_ln359_7_fu_718_p3);
    p_Result_12_fu_770_p3 <= (lower_V_5_fu_752_p1 & select_ln359_8_fu_762_p3);
    p_Result_13_fu_824_p5 <= (((comp_V_3_fu_668_p2 & comp_V_4_fu_712_p2) & comp_V_5_fu_756_p2) & top_is_leading_V_1_fu_794_p2);
    p_Result_14_fu_904_p7 <= (((((ret_11_fu_598_p2 & ret_18_fu_884_p2) & ret_19_fu_898_p2) & p_Result_8_fu_560_p3) & ret_12_fu_618_p2) & fraction_V_1_fu_860_p1);
    p_Result_15_fu_980_p4 <= ((p_Result_s_fu_200_p3 & ret_2_fu_258_p2) & fraction_V_fu_500_p1);
    p_Result_16_fu_990_p4 <= ((p_Result_8_fu_560_p3 & ret_12_fu_618_p2) & fraction_V_1_fu_860_p1);
    p_Result_17_fu_1008_p3 <= ret_22_fu_1678_p2(27 downto 27);
    p_Result_18_fu_1015_p3 <= ret_22_fu_1678_p2(25 downto 25);
    p_Result_19_fu_1035_p3 <= ret_22_fu_1678_p2(26 downto 26);
    p_Result_20_fu_1076_p3 <= (ret_26_fu_1067_p2 & last_bits_V_fu_1073_p1);
    p_Result_21_fu_1084_p3 <= (last_bits_V_fu_1073_p1 & ap_const_lv1_0);
    p_Result_22_fu_1162_p3 <= opt1_V_11_fu_1092_p3(12 downto 12);
    p_Result_23_fu_1244_p3 <= p_Val2_s_fu_1238_p2(6 downto 6);
    p_Result_24_fu_1318_p7 <= (((((p_Result_22_fu_1162_p3 & val_V_101_fu_1174_p2) & ret_20_fu_926_p3) & val_V_102_fu_1304_p1) & p_Result_17_fu_1008_p3) & tmp_36_fu_1308_p4);
    p_Result_25_fu_1342_p3 <= opt1_V_12_fu_1334_p3(13 downto 13);
    p_Result_26_fu_1376_p3 <= opt1_V_12_fu_1334_p3(19 downto 19);
    p_Result_27_fu_1430_p3 <= opt1_V_12_fu_1334_p3(22 downto 22);
    p_Result_28_fu_1438_p3 <= res_16_fu_1398_p3(1 downto 1);
    p_Result_29_fu_1446_p7 <= (((((p_Result_28_fu_1438_p3 & res_16_fu_1398_p3) & ret_30_fu_1370_p2) & significand_V_fu_1350_p1) & p_Result_27_fu_1430_p3) & ap_const_lv12_0);
    p_Result_2_fu_208_p3 <= in1(14 downto 14);
    p_Result_30_fu_1480_p3 <= (shift_high_V_fu_1466_p4 & ap_const_lv2_0);
    p_Result_31_fu_1518_p4 <= ((p_Result_28_fu_1438_p3 & shifted_V_fu_1498_p4) & ap_const_lv3_0);
    p_Result_32_fu_1558_p3 <= lshr_ln978_fu_1536_p2(3 downto 3);
    p_Result_33_fu_1584_p3 <= opt1_V_12_fu_1334_p3(21 downto 21);
    p_Result_34_fu_1576_p3 <= lshr_ln978_fu_1536_p2(4 downto 4);
    p_Result_35_fu_1620_p3 <= (p_Result_25_fu_1342_p3 & roundedResult_V_fu_1614_p2);
    p_Result_36_fu_1628_p3 <= opt1_V_12_fu_1334_p3(20 downto 20);
    p_Result_37_fu_1636_p3 <= (p_Result_36_fu_1628_p3 & ap_const_lv15_0);
    p_Result_3_fu_322_p3 <= (lower_V_fu_304_p1 & select_ln359_1_fu_314_p3);
    p_Result_4_fu_366_p3 <= (lower_V_1_fu_348_p1 & select_ln359_2_fu_358_p3);
    p_Result_5_fu_410_p3 <= (lower_V_2_fu_392_p1 & select_ln359_3_fu_402_p3);
    p_Result_6_fu_464_p5 <= (((comp_V_fu_308_p2 & comp_V_1_fu_352_p2) & comp_V_2_fu_396_p2) & top_is_leading_V_fu_434_p2);
    p_Result_7_fu_544_p7 <= (((((ret_1_fu_238_p2 & ret_8_fu_524_p2) & ret_9_fu_538_p2) & p_Result_s_fu_200_p3) & ret_2_fu_258_p2) & fraction_V_fu_500_p1);
    p_Result_8_fu_560_p3 <= in2(15 downto 15);
    p_Result_9_fu_568_p3 <= in2(14 downto 14);
    p_Result_s_fu_200_p3 <= in1(15 downto 15);
    p_Val2_s_fu_1238_p2 <= std_logic_vector(unsigned(zext_ln217_5_fu_1234_p1) + unsigned(ret_27_fu_1216_p2));
    p_what2_s_fu_1170_p1 <= opt1_V_11_fu_1092_p3(12 - 1 downto 0);
    r_10_fu_1416_p2 <= (low_k_V_fu_1406_p4 xor ap_const_lv4_F);
    r_11_fu_1492_p2 <= std_logic_vector(shift_right(unsigned(sext_ln312_fu_1462_p1),to_integer(unsigned('0' & zext_ln978_fu_1488_p1(31-1 downto 0)))));
    r_12_fu_1546_p2 <= "0" when (shifted_out_V_1_fu_1542_p1 = ap_const_lv3_0) else "1";
    r_1_fu_510_p2 <= (xor_ln939_fu_504_p2 xor ap_const_lv1_1);
    r_2_fu_592_p2 <= (ret_10_fu_586_p2 xor ap_const_lv1_1);
    r_3_fu_870_p2 <= (xor_ln939_3_fu_864_p2 xor ap_const_lv1_1);
    r_4_fu_948_p2 <= "1" when (and_ln_fu_934_p6 = ap_const_lv21_0) else "0";
    r_5_fu_968_p2 <= "1" when (and_ln1528_1_fu_954_p6 = ap_const_lv21_0) else "0";
    r_6_fu_1029_p2 <= (tmp_27_fu_1022_p3 xor ap_const_lv1_1);
    r_7_fu_1202_p2 <= (tmp_34_fu_1194_p3 xor ap_const_lv1_1);
    r_8_fu_1252_p2 <= (ret_20_fu_926_p3 xor ap_const_lv1_1);
    r_9_fu_1188_p2 <= (tmp_33_fu_1180_p3 or p_Result_17_fu_1008_p3);
    r_fu_232_p2 <= (ret_fu_226_p2 xor ap_const_lv1_1);
    res_12_fu_482_p3 <= 
        ap_const_lv4_E when (val_V_95_fu_476_p2(0) = '1') else 
        p_Result_6_fu_464_p5;
    res_13_fu_842_p3 <= 
        ap_const_lv4_E when (val_V_99_fu_836_p2(0) = '1') else 
        p_Result_13_fu_824_p5;
    res_14_fu_1154_p3 <= 
        ap_const_lv7_0 when (ret_21_fu_974_p2(0) = '1') else 
        expSumVal_V_fu_1148_p2;
    res_15_fu_1292_p3 <= 
        select_ln416_fu_1284_p3 when (ret_29_fu_1270_p2(0) = '1') else 
        res_fu_1276_p3;
    res_16_fu_1398_p3 <= 
        ap_const_lv2_1 when (ret_31_fu_1392_p2(0) = '1') else 
        ap_const_lv2_2;
    res_fu_1276_p3 <= 
        ap_const_lv20_8E000 when (p_Result_17_fu_1008_p3(0) = '1') else 
        ap_const_lv20_91000;
    ret_10_fu_586_p2 <= (val_V_98_fu_580_p2 or p_Result_9_fu_568_p3);
    ret_11_fu_598_p2 <= (r_2_fu_592_p2 and p_Result_8_fu_560_p3);
    ret_12_fu_618_p2 <= (xor_ln1527_1_fu_612_p2 and ret_10_fu_586_p2);
    ret_13_fu_648_p2 <= (val_V_97_fu_576_p1 xor select_ln359_5_fu_632_p3);
    ret_14_fu_690_p3 <= 
        p_Result_10_fu_682_p3 when (comp_V_3_fu_668_p2(0) = '1') else 
        ret_13_fu_648_p2;
    ret_15_fu_734_p3 <= 
        p_Result_11_fu_726_p3 when (comp_V_4_fu_712_p2(0) = '1') else 
        ret_14_fu_690_p3;
    ret_16_fu_778_p3 <= 
        p_Result_12_fu_770_p3 when (comp_V_5_fu_756_p2(0) = '1') else 
        ret_15_fu_734_p3;
    ret_17_fu_850_p2 <= (select_ln356_1_fu_640_p3 xor opt1_V_10_fu_816_p3);
    ret_18_fu_884_p2 <= (zext_ln217_1_fu_856_p1 xor select_ln359_9_fu_876_p3);
    ret_19_fu_898_p2 <= (val_V_100_fu_890_p3 xor tmp_13_fu_604_p3);
    ret_1_fu_238_p2 <= (r_fu_232_p2 and p_Result_s_fu_200_p3);
    ret_20_fu_926_p3 <= or_ln1528_fu_920_p2(20 downto 20);
    ret_21_fu_974_p2 <= (r_5_fu_968_p2 or r_4_fu_948_p2);
    ret_23_fu_1042_p2 <= (r_6_fu_1029_p2 and p_Result_19_fu_1035_p3);
    ret_24_fu_1055_p2 <= (tmp_29_fu_1048_p3 xor tmp_27_fu_1022_p3);
    ret_25_fu_1061_p2 <= (ret_24_fu_1055_p2 or ret_23_fu_1042_p2);
    ret_26_fu_1067_p2 <= (ret_23_fu_1042_p2 or p_Result_18_fu_1015_p3);
    ret_27_fu_1216_p2 <= (select_ln359_10_fu_1208_p3 xor res_14_fu_1154_p3);
    ret_28_fu_1264_p2 <= (p_Result_23_fu_1244_p3 and and_ln1527_fu_1258_p2);
    ret_29_fu_1270_p2 <= (ret_28_fu_1264_p2 and r_7_fu_1202_p2);
    ret_2_fu_258_p2 <= (xor_ln1527_fu_252_p2 and ret_fu_226_p2);
    ret_30_fu_1370_p2 <= (tmp_40_fu_1362_p3 xor es_wo_xor_V_fu_1354_p3);
    ret_31_fu_1392_p2 <= (tmp_42_fu_1384_p3 xor tmp_40_fu_1362_p3);
    ret_32_fu_1552_p2 <= (val_V_103_fu_1512_p2 or r_12_fu_1546_p2);
    ret_33_fu_1598_p2 <= (ret_32_fu_1552_p2 or or_ln1528_7_fu_1592_p2);
    ret_34_fu_1604_p2 <= (ret_33_fu_1598_p2 and p_Result_32_fu_1558_p3);
    ret_35_fu_1658_p2 <= (or_ln1527_fu_1652_p2 xor ap_const_lv1_1);
    ret_36_fu_1664_p2 <= (ret_35_fu_1658_p2 or p_Result_36_fu_1628_p3);
    ret_3_fu_288_p2 <= (val_V_92_fu_216_p1 xor select_ln359_fu_272_p3);
    ret_4_fu_330_p3 <= 
        p_Result_3_fu_322_p3 when (comp_V_fu_308_p2(0) = '1') else 
        ret_3_fu_288_p2;
    ret_5_fu_374_p3 <= 
        p_Result_4_fu_366_p3 when (comp_V_1_fu_352_p2(0) = '1') else 
        ret_4_fu_330_p3;
    ret_6_fu_418_p3 <= 
        p_Result_5_fu_410_p3 when (comp_V_2_fu_396_p2(0) = '1') else 
        ret_5_fu_374_p3;
    ret_7_fu_490_p2 <= (select_ln356_fu_280_p3 xor opt1_V_9_fu_456_p3);
    ret_8_fu_524_p2 <= (zext_ln217_fu_496_p1 xor select_ln359_4_fu_516_p3);
    ret_9_fu_538_p2 <= (val_V_96_fu_530_p3 xor tmp_fu_244_p3);
    ret_fu_226_p2 <= (val_V_93_fu_220_p2 or p_Result_2_fu_208_p3);
    roundedResult_V_fu_1614_p2 <= std_logic_vector(unsigned(unroundedResult_V_fu_1566_p4) + unsigned(zext_ln217_3_fu_1610_p1));
    select_ln356_1_fu_640_p3 <= 
        ap_const_lv13_1FFF when (tmp_14_fu_624_p3(0) = '1') else 
        ap_const_lv13_0;
    select_ln356_fu_280_p3 <= 
        ap_const_lv13_1FFF when (tmp_1_fu_264_p3(0) = '1') else 
        ap_const_lv13_0;
    select_ln359_10_fu_1208_p3 <= 
        ap_const_lv7_7F when (r_7_fu_1202_p2(0) = '1') else 
        ap_const_lv7_0;
    select_ln359_1_fu_314_p3 <= 
        ap_const_lv8_FF when (tmp_1_fu_264_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_2_fu_358_p3 <= 
        ap_const_lv4_F when (tmp_1_fu_264_p3(0) = '1') else 
        ap_const_lv4_0;
    select_ln359_3_fu_402_p3 <= 
        ap_const_lv2_3 when (tmp_1_fu_264_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_4_fu_516_p3 <= 
        ap_const_lv5_1F when (r_1_fu_510_p2(0) = '1') else 
        ap_const_lv5_0;
    select_ln359_5_fu_632_p3 <= 
        ap_const_lv14_3FFF when (tmp_14_fu_624_p3(0) = '1') else 
        ap_const_lv14_0;
    select_ln359_6_fu_674_p3 <= 
        ap_const_lv8_FF when (tmp_14_fu_624_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_7_fu_718_p3 <= 
        ap_const_lv4_F when (tmp_14_fu_624_p3(0) = '1') else 
        ap_const_lv4_0;
    select_ln359_8_fu_762_p3 <= 
        ap_const_lv2_3 when (tmp_14_fu_624_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_9_fu_876_p3 <= 
        ap_const_lv5_1F when (r_3_fu_870_p2(0) = '1') else 
        ap_const_lv5_0;
    select_ln359_fu_272_p3 <= 
        ap_const_lv14_3FFF when (tmp_1_fu_264_p3(0) = '1') else 
        ap_const_lv14_0;
    select_ln416_fu_1284_p3 <= 
        ap_const_lv20_6E000 when (p_Result_17_fu_1008_p3(0) = '1') else 
        ap_const_lv20_71000;
        sext_ln217_fu_1230_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln_fu_1222_p3),5));

        sext_ln225_2_fu_1116_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(exp1_V_fu_1100_p3),7));

        sext_ln225_3_fu_1120_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(exp2_V_fu_1108_p3),7));

        sext_ln312_fu_1462_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_29_fu_1446_p7),40));

        sext_ln978_fu_1528_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_31_fu_1518_p4),22));

    shift_high_V_fu_1466_p4 <= opt1_V_13_fu_1422_p3(3 downto 2);
    shift_low_V_fu_1476_p1 <= opt1_V_13_fu_1422_p3(2 - 1 downto 0);
    shifted_V_fu_1498_p4 <= r_11_fu_1492_p2(27 downto 12);
    shifted_out_V_1_fu_1542_p1 <= lshr_ln978_fu_1536_p2(3 - 1 downto 0);
    shifted_out_V_fu_1508_p1 <= r_11_fu_1492_p2(12 - 1 downto 0);
    significand_V_fu_1350_p1 <= opt1_V_12_fu_1334_p3(12 - 1 downto 0);
    tmp_13_fu_604_p3 <= in2(15 downto 15);
    tmp_14_fu_624_p3 <= in2(14 downto 14);
    tmp_18_fu_786_p3 <= ret_16_fu_778_p3(13 downto 13);
    tmp_1_fu_264_p3 <= in1(14 downto 14);
    tmp_27_fu_1022_p3 <= ret_22_fu_1678_p2(27 downto 27);
    tmp_29_fu_1048_p3 <= ret_22_fu_1678_p2(25 downto 25);
    tmp_33_fu_1180_p3 <= opt1_V_11_fu_1092_p3(25 downto 25);
    tmp_34_fu_1194_p3 <= res_14_fu_1154_p3(6 downto 6);
    tmp_36_fu_1308_p4 <= opt1_V_11_fu_1092_p3(25 downto 13);
    tmp_40_fu_1362_p3 <= opt1_V_12_fu_1334_p3(13 downto 13);
    tmp_42_fu_1384_p3 <= opt1_V_12_fu_1334_p3(19 downto 19);
    tmp_54_fu_1644_p3 <= opt1_V_12_fu_1334_p3(12 downto 12);
    tmp_5_fu_444_p3 <= (trunc_ln312_fu_440_p1 & p_Result_2_fu_208_p3);
    tmp_6_fu_426_p3 <= ret_6_fu_418_p3(13 downto 13);
    tmp_7_fu_804_p3 <= (trunc_ln312_1_fu_800_p1 & p_Result_9_fu_568_p3);
    tmp_fu_244_p3 <= in1(15 downto 15);
    top_is_leading_V_1_fu_794_p2 <= (tmp_18_fu_786_p3 xor ap_const_lv1_1);
    top_is_leading_V_fu_434_p2 <= (tmp_6_fu_426_p3 xor ap_const_lv1_1);
    trunc_ln312_1_fu_800_p1 <= ret_16_fu_778_p3(12 - 1 downto 0);
    trunc_ln312_fu_440_p1 <= ret_6_fu_418_p3(12 - 1 downto 0);
    trunc_ln422_1_fu_812_p1 <= ret_16_fu_778_p3(13 - 1 downto 0);
    trunc_ln422_fu_452_p1 <= ret_6_fu_418_p3(13 - 1 downto 0);
    unroundedResult_V_fu_1566_p4 <= lshr_ln978_fu_1536_p2(18 downto 4);
    upper_V_1_fu_338_p4 <= ret_4_fu_330_p3(13 downto 10);
    upper_V_3_fu_654_p4 <= ret_13_fu_648_p2(13 downto 6);
    upper_V_4_fu_698_p4 <= ret_14_fu_690_p3(13 downto 10);
    upper_V_fu_294_p4 <= ret_3_fu_288_p2(13 downto 6);
    val_V_100_fu_890_p3 <= ret_17_fu_850_p2(12 downto 12);
    val_V_101_fu_1174_p2 <= "0" when (p_what2_s_fu_1170_p1 = ap_const_lv12_0) else "1";
    val_V_102_fu_1304_p1 <= res_14_fu_1154_p3(6 - 1 downto 0);
    val_V_103_fu_1512_p2 <= "0" when (shifted_out_V_fu_1508_p1 = ap_const_lv12_0) else "1";
    val_V_92_fu_216_p1 <= in1(14 - 1 downto 0);
    val_V_93_fu_220_p2 <= "0" when (val_V_92_fu_216_p1 = ap_const_lv14_0) else "1";
    val_V_94_fu_382_p4 <= ret_5_fu_374_p3(13 downto 12);
    val_V_95_fu_476_p2 <= "1" when (p_Result_6_fu_464_p5 = ap_const_lv4_F) else "0";
    val_V_96_fu_530_p3 <= ret_7_fu_490_p2(12 downto 12);
    val_V_97_fu_576_p1 <= in2(14 - 1 downto 0);
    val_V_98_fu_580_p2 <= "0" when (val_V_97_fu_576_p1 = ap_const_lv14_0) else "1";
    val_V_99_fu_836_p2 <= "1" when (p_Result_13_fu_824_p5 = ap_const_lv4_F) else "0";
    val_V_fu_742_p4 <= ret_15_fu_734_p3(13 downto 12);
    xor_ln1527_1_fu_612_p2 <= (tmp_13_fu_604_p3 xor ap_const_lv1_1);
    xor_ln1527_fu_252_p2 <= (tmp_fu_244_p3 xor ap_const_lv1_1);
    xor_ln939_3_fu_864_p2 <= (tmp_14_fu_624_p3 xor tmp_13_fu_604_p3);
    xor_ln939_fu_504_p2 <= (tmp_fu_244_p3 xor tmp_1_fu_264_p3);
    zext_ln217_1_fu_856_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_13_fu_842_p3),5));
    zext_ln217_2_fu_1128_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_23_fu_1042_p2),2));
    zext_ln217_3_fu_1610_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_34_fu_1604_p2),15));
    zext_ln217_4_fu_1144_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln217_1_fu_1138_p2),7));
    zext_ln217_5_fu_1234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln217_fu_1230_p1),7));
    zext_ln217_6_fu_1300_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_15_fu_1292_p3),23));
    zext_ln217_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_12_fu_482_p3),5));
    zext_ln306_fu_1124_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_25_fu_1061_p2),2));
    zext_ln978_1_fu_1532_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shift_low_V_fu_1476_p1),22));
    zext_ln978_fu_1488_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_30_fu_1480_p3),40));
end behav;
