-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity posit_comp_mul is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in1 : IN STD_LOGIC_VECTOR (15 downto 0);
    in2 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of posit_comp_mul is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "posit_comp_mul_posit_comp_mul,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=5000000.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=16.990900,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=21,HLS_SYN_LUT=888,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv14_3FFF : STD_LOGIC_VECTOR (13 downto 0) := "11111111111111";
    constant ap_const_lv13_1FFF : STD_LOGIC_VECTOR (12 downto 0) := "1111111111111";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv20_8F000 : STD_LOGIC_VECTOR (19 downto 0) := "10001111000000000000";
    constant ap_const_lv20_90800 : STD_LOGIC_VECTOR (19 downto 0) := "10010000100000000000";
    constant ap_const_lv20_6F000 : STD_LOGIC_VECTOR (19 downto 0) := "01101111000000000000";
    constant ap_const_lv20_70800 : STD_LOGIC_VECTOR (19 downto 0) := "01110000100000000000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ret_8_fu_528_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_8_reg_1716 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_9_fu_552_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_9_reg_1721 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_18_fu_898_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_18_reg_1726 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_19_fu_922_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_19_reg_1731 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_20_reg_1736 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_4_fu_972_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_4_reg_1742 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_5_fu_992_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_5_reg_1747 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_91_fu_220_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_92_fu_224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_fu_212_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_fu_230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_204_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ext_fu_248_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1527_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_268_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_fu_276_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_3_fu_292_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_fu_298_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lower_V_fu_308_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln359_1_fu_318_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal comp_V_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_3_fu_326_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_4_fu_334_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_1_fu_342_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal lower_V_1_fu_352_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln359_2_fu_362_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal comp_V_1_fu_356_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_4_fu_370_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_5_fu_378_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_93_fu_386_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lower_V_2_fu_396_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln359_3_fu_406_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal comp_V_2_fu_400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_5_fu_414_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_6_fu_422_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_6_fu_430_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln312_fu_444_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln422_fu_456_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_5_fu_448_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal top_is_leading_V_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_6_fu_468_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal val_V_94_fu_480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal opt1_V_9_fu_460_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln356_fu_284_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_12_fu_486_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ret_7_fu_494_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal xor_ln939_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln217_fu_500_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln359_4_fu_520_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal es_V_fu_534_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln359_5_fu_544_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_1_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_2_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fraction_V_fu_504_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal val_V_95_fu_590_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_96_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_fu_582_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_10_fu_600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_fu_574_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_2_fu_606_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ext_1_fu_618_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1527_1_fu_626_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_638_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_6_fu_646_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_13_fu_662_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_3_fu_668_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lower_V_3_fu_678_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln359_7_fu_688_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal comp_V_3_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_10_fu_696_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_14_fu_704_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal upper_V_4_fu_712_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal lower_V_4_fu_722_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln359_8_fu_732_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal comp_V_4_fu_726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_11_fu_740_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_15_fu_748_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal val_V_fu_756_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lower_V_5_fu_766_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln359_9_fu_776_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal comp_V_5_fu_770_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_12_fu_784_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_16_fu_792_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_13_fu_800_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln312_1_fu_814_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln422_1_fu_826_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_7_fu_818_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal top_is_leading_V_1_fu_808_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_13_fu_838_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal val_V_97_fu_850_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal opt1_V_10_fu_830_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln356_1_fu_654_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_13_fu_856_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ret_17_fu_864_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal xor_ln939_3_fu_878_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_3_fu_884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln217_1_fu_870_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln359_10_fu_890_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal es_V_1_fu_904_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln359_11_fu_914_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_11_fu_612_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_12_fu_632_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fraction_V_1_fu_874_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_14_fu_928_p7 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_Result_7_fu_558_p7 : STD_LOGIC_VECTOR (20 downto 0);
    signal or_ln1528_fu_944_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal and_ln_fu_958_p6 : STD_LOGIC_VECTOR (20 downto 0);
    signal and_ln1528_1_fu_978_p6 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_Result_15_fu_998_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Result_16_fu_1008_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_fu_1704_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_fu_1044_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_19_fu_1057_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_6_fu_1051_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_1070_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_23_fu_1064_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_24_fu_1077_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_18_fu_1037_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_26_fu_1089_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_bits_V_fu_1095_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal ret_25_fu_1083_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_20_fu_1098_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Result_21_fu_1106_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal exp1_V_fu_1122_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal exp2_V_fu_1128_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln225_2_fu_1134_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln225_3_fu_1138_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln217_2_fu_1146_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln306_fu_1142_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln217_1_fu_1156_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln217_4_fu_1162_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln217_fu_1150_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_21_fu_1026_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal expSumVal_V_fu_1166_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal opt1_V_11_fu_1114_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_what2_s_fu_1188_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_20_fu_1198_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_17_fu_1030_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_14_fu_1172_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_fu_1212_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_7_fu_1220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_12_fu_1226_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln_fu_1240_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln217_fu_1248_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln217_5_fu_1252_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_27_fu_1234_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_s_fu_1256_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_9_fu_1206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_8_fu_1270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1527_fu_1275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_23_fu_1262_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_28_fu_1281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_29_fu_1287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln416_fu_1301_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal res_fu_1293_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal res_15_fu_1309_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Result_22_fu_1180_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_98_fu_1192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_99_fu_1321_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_23_fu_1325_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln217_6_fu_1317_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal p_Result_24_fu_1335_p7 : STD_LOGIC_VECTOR (22 downto 0);
    signal opt1_V_12_fu_1350_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_26_fu_1370_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal es_wo_xor_V_fu_1386_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln359_13_fu_1378_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_28_fu_1410_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_31_fu_1418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal low_k_V_fu_1432_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_26_fu_1402_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_10_fu_1442_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal res_16_fu_1424_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_28_fu_1464_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_30_fu_1396_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal significand_V_fu_1366_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_27_fu_1456_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_29_fu_1472_p7 : STD_LOGIC_VECTOR (28 downto 0);
    signal opt1_V_13_fu_1448_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal shift_high_V_fu_1492_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_30_fu_1506_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln312_fu_1488_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal zext_ln978_fu_1514_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal r_11_fu_1518_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal shifted_out_V_fu_1534_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal shifted_V_fu_1524_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_31_fu_1544_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal shift_low_V_fu_1502_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln978_fu_1554_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln978_1_fu_1558_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal lshr_ln978_fu_1562_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_out_V_1_fu_1568_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_12_fu_1572_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_100_fu_1538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_33_fu_1610_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_34_fu_1602_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1528_7_fu_1618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_32_fu_1578_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_32_fu_1584_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_33_fu_1624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_34_fu_1630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal unroundedResult_V_fu_1592_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln217_3_fu_1636_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Result_25_fu_1358_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal roundedResult_V_fu_1640_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Result_36_fu_1654_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_1670_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1527_fu_1678_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_35_fu_1684_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_36_fu_1690_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_37_fu_1662_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_35_fu_1646_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component posit_comp_mul_mul_mul_13s_13s_26_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (12 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;



begin
    mul_mul_13s_13s_26_4_1_U1 : component posit_comp_mul_mul_mul_13s_13s_26_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 13,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_Result_16_fu_1008_p4,
        din1 => p_Result_15_fu_998_p4,
        ce => ap_const_logic_1,
        dout => grp_fu_1704_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                r_4_reg_1742 <= r_4_fu_972_p2;
                r_5_reg_1747 <= r_5_fu_992_p2;
                ret_18_reg_1726 <= ret_18_fu_898_p2;
                ret_19_reg_1731 <= ret_19_fu_922_p2;
                ret_20_reg_1736 <= or_ln1528_fu_944_p2(20 downto 20);
                ret_8_reg_1716 <= ret_8_fu_528_p2;
                ret_9_reg_1721 <= ret_9_fu_552_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln217_1_fu_1156_p2 <= std_logic_vector(unsigned(zext_ln217_2_fu_1146_p1) + unsigned(zext_ln306_fu_1142_p1));
    add_ln217_fu_1150_p2 <= std_logic_vector(signed(sext_ln225_2_fu_1134_p1) + signed(sext_ln225_3_fu_1138_p1));
    and_ln1527_fu_1275_p2 <= (r_9_fu_1206_p2 and r_8_fu_1270_p2);
    and_ln1528_1_fu_978_p6 <= ((((ret_11_fu_612_p2 & ap_const_lv7_0) & p_Result_8_fu_574_p3) & ret_12_fu_632_p2) & ap_const_lv11_0);
    and_ln_fu_958_p6 <= ((((ret_1_fu_242_p2 & ap_const_lv7_0) & p_Result_s_fu_204_p3) & ret_2_fu_262_p2) & ap_const_lv11_0);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= 
        p_Result_37_fu_1662_p3 when (ret_36_fu_1690_p2(0) = '1') else 
        p_Result_35_fu_1646_p3;
    comp_V_1_fu_356_p2 <= "1" when (upper_V_1_fu_342_p4 = ap_const_lv4_0) else "0";
    comp_V_2_fu_400_p2 <= "1" when (val_V_93_fu_386_p4 = ap_const_lv2_0) else "0";
    comp_V_3_fu_682_p2 <= "1" when (upper_V_3_fu_668_p4 = ap_const_lv8_0) else "0";
    comp_V_4_fu_726_p2 <= "1" when (upper_V_4_fu_712_p4 = ap_const_lv4_0) else "0";
    comp_V_5_fu_770_p2 <= "1" when (val_V_fu_756_p4 = ap_const_lv2_0) else "0";
    comp_V_fu_312_p2 <= "1" when (upper_V_fu_298_p4 = ap_const_lv8_0) else "0";
    es_V_1_fu_904_p4 <= ret_17_fu_864_p2(12 downto 11);
    es_V_fu_534_p4 <= ret_7_fu_494_p2(12 downto 11);
    es_wo_xor_V_fu_1386_p4 <= opt1_V_12_fu_1350_p3(14 downto 13);
    exp1_V_fu_1122_p3 <= (ret_8_reg_1716 & ret_9_reg_1721);
    exp2_V_fu_1128_p3 <= (ret_18_reg_1726 & ret_19_reg_1731);
    expSumVal_V_fu_1166_p2 <= std_logic_vector(unsigned(zext_ln217_4_fu_1162_p1) + unsigned(add_ln217_fu_1150_p2));
    ext_1_fu_618_p3 <= in2(15 downto 15);
    ext_fu_248_p3 <= in1(15 downto 15);
    fraction_V_1_fu_874_p1 <= ret_17_fu_864_p2(11 - 1 downto 0);
    fraction_V_fu_504_p1 <= ret_7_fu_494_p2(11 - 1 downto 0);
    last_bits_V_fu_1095_p1 <= grp_fu_1704_p2(23 - 1 downto 0);
    low_k_V_fu_1432_p4 <= opt1_V_12_fu_1350_p3(18 downto 15);
    lower_V_1_fu_352_p1 <= ret_4_fu_334_p3(10 - 1 downto 0);
    lower_V_2_fu_396_p1 <= ret_5_fu_378_p3(12 - 1 downto 0);
    lower_V_3_fu_678_p1 <= ret_13_fu_662_p2(6 - 1 downto 0);
    lower_V_4_fu_722_p1 <= ret_14_fu_704_p3(10 - 1 downto 0);
    lower_V_5_fu_766_p1 <= ret_15_fu_748_p3(12 - 1 downto 0);
    lower_V_fu_308_p1 <= ret_3_fu_292_p2(6 - 1 downto 0);
    lshr_ln978_fu_1562_p2 <= std_logic_vector(shift_right(unsigned(sext_ln978_fu_1554_p1),to_integer(unsigned('0' & zext_ln978_1_fu_1558_p1(22-1 downto 0)))));
    opt1_V_10_fu_830_p3 <= 
        trunc_ln422_1_fu_826_p1 when (tmp_13_fu_800_p3(0) = '1') else 
        tmp_7_fu_818_p3;
    opt1_V_11_fu_1114_p3 <= 
        p_Result_20_fu_1098_p3 when (ret_25_fu_1083_p2(0) = '1') else 
        p_Result_21_fu_1106_p3;
    opt1_V_12_fu_1350_p3 <= 
        zext_ln217_6_fu_1317_p1 when (ret_28_fu_1281_p2(0) = '1') else 
        p_Result_24_fu_1335_p7;
    opt1_V_13_fu_1448_p3 <= 
        r_10_fu_1442_p2 when (p_Result_26_fu_1402_p3(0) = '1') else 
        low_k_V_fu_1432_p4;
    opt1_V_9_fu_460_p3 <= 
        trunc_ln422_fu_456_p1 when (tmp_6_fu_430_p3(0) = '1') else 
        tmp_5_fu_448_p3;
    or_ln1527_fu_1678_p2 <= (tmp_40_fu_1670_p3 or tmp_26_fu_1370_p3);
    or_ln1528_7_fu_1618_p2 <= (p_Result_34_fu_1602_p3 or p_Result_33_fu_1610_p3);
    or_ln1528_fu_944_p2 <= (p_Result_7_fu_558_p7 or p_Result_14_fu_928_p7);
    or_ln_fu_1240_p3 <= (ap_const_lv3_4 & r_7_fu_1220_p2);
    p_Result_10_fu_696_p3 <= (lower_V_3_fu_678_p1 & select_ln359_7_fu_688_p3);
    p_Result_11_fu_740_p3 <= (lower_V_4_fu_722_p1 & select_ln359_8_fu_732_p3);
    p_Result_12_fu_784_p3 <= (lower_V_5_fu_766_p1 & select_ln359_9_fu_776_p3);
    p_Result_13_fu_838_p5 <= (((comp_V_3_fu_682_p2 & comp_V_4_fu_726_p2) & comp_V_5_fu_770_p2) & top_is_leading_V_1_fu_808_p2);
    p_Result_14_fu_928_p7 <= (((((ret_11_fu_612_p2 & ret_18_fu_898_p2) & ret_19_fu_922_p2) & p_Result_8_fu_574_p3) & ret_12_fu_632_p2) & fraction_V_1_fu_874_p1);
    p_Result_15_fu_998_p4 <= ((p_Result_s_fu_204_p3 & ret_2_fu_262_p2) & fraction_V_fu_504_p1);
    p_Result_16_fu_1008_p4 <= ((p_Result_8_fu_574_p3 & ret_12_fu_632_p2) & fraction_V_1_fu_874_p1);
    p_Result_17_fu_1030_p3 <= grp_fu_1704_p2(25 downto 25);
    p_Result_18_fu_1037_p3 <= grp_fu_1704_p2(23 downto 23);
    p_Result_19_fu_1057_p3 <= grp_fu_1704_p2(24 downto 24);
    p_Result_20_fu_1098_p3 <= (ret_26_fu_1089_p2 & last_bits_V_fu_1095_p1);
    p_Result_21_fu_1106_p3 <= (last_bits_V_fu_1095_p1 & ap_const_lv1_0);
    p_Result_22_fu_1180_p3 <= opt1_V_11_fu_1114_p3(11 downto 11);
    p_Result_23_fu_1262_p3 <= p_Val2_s_fu_1256_p2(7 downto 7);
    p_Result_24_fu_1335_p7 <= (((((p_Result_22_fu_1180_p3 & val_V_98_fu_1192_p2) & ret_20_reg_1736) & val_V_99_fu_1321_p1) & p_Result_17_fu_1030_p3) & tmp_23_fu_1325_p4);
    p_Result_25_fu_1358_p3 <= opt1_V_12_fu_1350_p3(12 downto 12);
    p_Result_26_fu_1402_p3 <= opt1_V_12_fu_1350_p3(19 downto 19);
    p_Result_27_fu_1456_p3 <= opt1_V_12_fu_1350_p3(22 downto 22);
    p_Result_28_fu_1464_p3 <= res_16_fu_1424_p3(1 downto 1);
    p_Result_29_fu_1472_p7 <= (((((p_Result_28_fu_1464_p3 & res_16_fu_1424_p3) & ret_30_fu_1396_p2) & significand_V_fu_1366_p1) & p_Result_27_fu_1456_p3) & ap_const_lv12_0);
    p_Result_2_fu_212_p3 <= in1(14 downto 14);
    p_Result_30_fu_1506_p3 <= (shift_high_V_fu_1492_p4 & ap_const_lv2_0);
    p_Result_31_fu_1544_p4 <= ((p_Result_28_fu_1464_p3 & shifted_V_fu_1524_p4) & ap_const_lv3_0);
    p_Result_32_fu_1584_p3 <= lshr_ln978_fu_1562_p2(3 downto 3);
    p_Result_33_fu_1610_p3 <= opt1_V_12_fu_1350_p3(21 downto 21);
    p_Result_34_fu_1602_p3 <= lshr_ln978_fu_1562_p2(4 downto 4);
    p_Result_35_fu_1646_p3 <= (p_Result_25_fu_1358_p3 & roundedResult_V_fu_1640_p2);
    p_Result_36_fu_1654_p3 <= opt1_V_12_fu_1350_p3(20 downto 20);
    p_Result_37_fu_1662_p3 <= (p_Result_36_fu_1654_p3 & ap_const_lv15_0);
    p_Result_3_fu_326_p3 <= (lower_V_fu_308_p1 & select_ln359_1_fu_318_p3);
    p_Result_4_fu_370_p3 <= (lower_V_1_fu_352_p1 & select_ln359_2_fu_362_p3);
    p_Result_5_fu_414_p3 <= (lower_V_2_fu_396_p1 & select_ln359_3_fu_406_p3);
    p_Result_6_fu_468_p5 <= (((comp_V_fu_312_p2 & comp_V_1_fu_356_p2) & comp_V_2_fu_400_p2) & top_is_leading_V_fu_438_p2);
    p_Result_7_fu_558_p7 <= (((((ret_1_fu_242_p2 & ret_8_fu_528_p2) & ret_9_fu_552_p2) & p_Result_s_fu_204_p3) & ret_2_fu_262_p2) & fraction_V_fu_504_p1);
    p_Result_8_fu_574_p3 <= in2(15 downto 15);
    p_Result_9_fu_582_p3 <= in2(14 downto 14);
    p_Result_s_fu_204_p3 <= in1(15 downto 15);
    p_Val2_s_fu_1256_p2 <= std_logic_vector(unsigned(zext_ln217_5_fu_1252_p1) + unsigned(ret_27_fu_1234_p2));
    p_what2_s_fu_1188_p1 <= opt1_V_11_fu_1114_p3(11 - 1 downto 0);
    r_10_fu_1442_p2 <= (low_k_V_fu_1432_p4 xor ap_const_lv4_F);
    r_11_fu_1518_p2 <= std_logic_vector(shift_right(unsigned(sext_ln312_fu_1488_p1),to_integer(unsigned('0' & zext_ln978_fu_1514_p1(31-1 downto 0)))));
    r_12_fu_1572_p2 <= "0" when (shifted_out_V_1_fu_1568_p1 = ap_const_lv3_0) else "1";
    r_1_fu_514_p2 <= (xor_ln939_fu_508_p2 xor ap_const_lv1_1);
    r_2_fu_606_p2 <= (ret_10_fu_600_p2 xor ap_const_lv1_1);
    r_3_fu_884_p2 <= (xor_ln939_3_fu_878_p2 xor ap_const_lv1_1);
    r_4_fu_972_p2 <= "1" when (and_ln_fu_958_p6 = ap_const_lv21_0) else "0";
    r_5_fu_992_p2 <= "1" when (and_ln1528_1_fu_978_p6 = ap_const_lv21_0) else "0";
    r_6_fu_1051_p2 <= (tmp_fu_1044_p3 xor ap_const_lv1_1);
    r_7_fu_1220_p2 <= (tmp_21_fu_1212_p3 xor ap_const_lv1_1);
    r_8_fu_1270_p2 <= (ret_20_reg_1736 xor ap_const_lv1_1);
    r_9_fu_1206_p2 <= (tmp_20_fu_1198_p3 or p_Result_17_fu_1030_p3);
    r_fu_236_p2 <= (ret_fu_230_p2 xor ap_const_lv1_1);
    res_12_fu_486_p3 <= 
        ap_const_lv4_E when (val_V_94_fu_480_p2(0) = '1') else 
        p_Result_6_fu_468_p5;
    res_13_fu_856_p3 <= 
        ap_const_lv4_E when (val_V_97_fu_850_p2(0) = '1') else 
        p_Result_13_fu_838_p5;
    res_14_fu_1172_p3 <= 
        ap_const_lv8_0 when (ret_21_fu_1026_p2(0) = '1') else 
        expSumVal_V_fu_1166_p2;
    res_15_fu_1309_p3 <= 
        select_ln416_fu_1301_p3 when (ret_29_fu_1287_p2(0) = '1') else 
        res_fu_1293_p3;
    res_16_fu_1424_p3 <= 
        ap_const_lv2_1 when (ret_31_fu_1418_p2(0) = '1') else 
        ap_const_lv2_2;
    res_fu_1293_p3 <= 
        ap_const_lv20_8F000 when (p_Result_17_fu_1030_p3(0) = '1') else 
        ap_const_lv20_90800;
    ret_10_fu_600_p2 <= (val_V_96_fu_594_p2 or p_Result_9_fu_582_p3);
    ret_11_fu_612_p2 <= (r_2_fu_606_p2 and p_Result_8_fu_574_p3);
    ret_12_fu_632_p2 <= (xor_ln1527_1_fu_626_p2 and ret_10_fu_600_p2);
    ret_13_fu_662_p2 <= (val_V_95_fu_590_p1 xor select_ln359_6_fu_646_p3);
    ret_14_fu_704_p3 <= 
        p_Result_10_fu_696_p3 when (comp_V_3_fu_682_p2(0) = '1') else 
        ret_13_fu_662_p2;
    ret_15_fu_748_p3 <= 
        p_Result_11_fu_740_p3 when (comp_V_4_fu_726_p2(0) = '1') else 
        ret_14_fu_704_p3;
    ret_16_fu_792_p3 <= 
        p_Result_12_fu_784_p3 when (comp_V_5_fu_770_p2(0) = '1') else 
        ret_15_fu_748_p3;
    ret_17_fu_864_p2 <= (select_ln356_1_fu_654_p3 xor opt1_V_10_fu_830_p3);
    ret_18_fu_898_p2 <= (zext_ln217_1_fu_870_p1 xor select_ln359_10_fu_890_p3);
    ret_19_fu_922_p2 <= (select_ln359_11_fu_914_p3 xor es_V_1_fu_904_p4);
    ret_1_fu_242_p2 <= (r_fu_236_p2 and p_Result_s_fu_204_p3);
    ret_21_fu_1026_p2 <= (r_5_reg_1747 or r_4_reg_1742);
    ret_23_fu_1064_p2 <= (r_6_fu_1051_p2 and p_Result_19_fu_1057_p3);
    ret_24_fu_1077_p2 <= (tmp_fu_1044_p3 xor tmp_16_fu_1070_p3);
    ret_25_fu_1083_p2 <= (ret_24_fu_1077_p2 or ret_23_fu_1064_p2);
    ret_26_fu_1089_p2 <= (ret_23_fu_1064_p2 or p_Result_18_fu_1037_p3);
    ret_27_fu_1234_p2 <= (select_ln359_12_fu_1226_p3 xor res_14_fu_1172_p3);
    ret_28_fu_1281_p2 <= (p_Result_23_fu_1262_p3 and and_ln1527_fu_1275_p2);
    ret_29_fu_1287_p2 <= (ret_28_fu_1281_p2 and r_7_fu_1220_p2);
    ret_2_fu_262_p2 <= (xor_ln1527_fu_256_p2 and ret_fu_230_p2);
    ret_30_fu_1396_p2 <= (select_ln359_13_fu_1378_p3 xor es_wo_xor_V_fu_1386_p4);
    ret_31_fu_1418_p2 <= (tmp_28_fu_1410_p3 xor tmp_26_fu_1370_p3);
    ret_32_fu_1578_p2 <= (val_V_100_fu_1538_p2 or r_12_fu_1572_p2);
    ret_33_fu_1624_p2 <= (ret_32_fu_1578_p2 or or_ln1528_7_fu_1618_p2);
    ret_34_fu_1630_p2 <= (ret_33_fu_1624_p2 and p_Result_32_fu_1584_p3);
    ret_35_fu_1684_p2 <= (or_ln1527_fu_1678_p2 xor ap_const_lv1_1);
    ret_36_fu_1690_p2 <= (ret_35_fu_1684_p2 or p_Result_36_fu_1654_p3);
    ret_3_fu_292_p2 <= (val_V_91_fu_220_p1 xor select_ln359_fu_276_p3);
    ret_4_fu_334_p3 <= 
        p_Result_3_fu_326_p3 when (comp_V_fu_312_p2(0) = '1') else 
        ret_3_fu_292_p2;
    ret_5_fu_378_p3 <= 
        p_Result_4_fu_370_p3 when (comp_V_1_fu_356_p2(0) = '1') else 
        ret_4_fu_334_p3;
    ret_6_fu_422_p3 <= 
        p_Result_5_fu_414_p3 when (comp_V_2_fu_400_p2(0) = '1') else 
        ret_5_fu_378_p3;
    ret_7_fu_494_p2 <= (select_ln356_fu_284_p3 xor opt1_V_9_fu_460_p3);
    ret_8_fu_528_p2 <= (zext_ln217_fu_500_p1 xor select_ln359_4_fu_520_p3);
    ret_9_fu_552_p2 <= (select_ln359_5_fu_544_p3 xor es_V_fu_534_p4);
    ret_fu_230_p2 <= (val_V_92_fu_224_p2 or p_Result_2_fu_212_p3);
    roundedResult_V_fu_1640_p2 <= std_logic_vector(unsigned(unroundedResult_V_fu_1592_p4) + unsigned(zext_ln217_3_fu_1636_p1));
    select_ln356_1_fu_654_p3 <= 
        ap_const_lv13_1FFF when (tmp_9_fu_638_p3(0) = '1') else 
        ap_const_lv13_0;
    select_ln356_fu_284_p3 <= 
        ap_const_lv13_1FFF when (tmp_1_fu_268_p3(0) = '1') else 
        ap_const_lv13_0;
    select_ln359_10_fu_890_p3 <= 
        ap_const_lv5_1F when (r_3_fu_884_p2(0) = '1') else 
        ap_const_lv5_0;
    select_ln359_11_fu_914_p3 <= 
        ap_const_lv2_3 when (ext_1_fu_618_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_12_fu_1226_p3 <= 
        ap_const_lv8_FF when (r_7_fu_1220_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_13_fu_1378_p3 <= 
        ap_const_lv2_3 when (tmp_26_fu_1370_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_1_fu_318_p3 <= 
        ap_const_lv8_FF when (tmp_1_fu_268_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_2_fu_362_p3 <= 
        ap_const_lv4_F when (tmp_1_fu_268_p3(0) = '1') else 
        ap_const_lv4_0;
    select_ln359_3_fu_406_p3 <= 
        ap_const_lv2_3 when (tmp_1_fu_268_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_4_fu_520_p3 <= 
        ap_const_lv5_1F when (r_1_fu_514_p2(0) = '1') else 
        ap_const_lv5_0;
    select_ln359_5_fu_544_p3 <= 
        ap_const_lv2_3 when (ext_fu_248_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_6_fu_646_p3 <= 
        ap_const_lv14_3FFF when (tmp_9_fu_638_p3(0) = '1') else 
        ap_const_lv14_0;
    select_ln359_7_fu_688_p3 <= 
        ap_const_lv8_FF when (tmp_9_fu_638_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_8_fu_732_p3 <= 
        ap_const_lv4_F when (tmp_9_fu_638_p3(0) = '1') else 
        ap_const_lv4_0;
    select_ln359_9_fu_776_p3 <= 
        ap_const_lv2_3 when (tmp_9_fu_638_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_fu_276_p3 <= 
        ap_const_lv14_3FFF when (tmp_1_fu_268_p3(0) = '1') else 
        ap_const_lv14_0;
    select_ln416_fu_1301_p3 <= 
        ap_const_lv20_6F000 when (p_Result_17_fu_1030_p3(0) = '1') else 
        ap_const_lv20_70800;
        sext_ln217_fu_1248_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln_fu_1240_p3),6));

        sext_ln225_2_fu_1134_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(exp1_V_fu_1122_p3),8));

        sext_ln225_3_fu_1138_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(exp2_V_fu_1128_p3),8));

        sext_ln312_fu_1488_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_29_fu_1472_p7),40));

        sext_ln978_fu_1554_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_31_fu_1544_p4),22));

    shift_high_V_fu_1492_p4 <= opt1_V_13_fu_1448_p3(3 downto 2);
    shift_low_V_fu_1502_p1 <= opt1_V_13_fu_1448_p3(2 - 1 downto 0);
    shifted_V_fu_1524_p4 <= r_11_fu_1518_p2(27 downto 12);
    shifted_out_V_1_fu_1568_p1 <= lshr_ln978_fu_1562_p2(3 - 1 downto 0);
    shifted_out_V_fu_1534_p1 <= r_11_fu_1518_p2(12 - 1 downto 0);
    significand_V_fu_1366_p1 <= opt1_V_12_fu_1350_p3(11 - 1 downto 0);
    tmp_13_fu_800_p3 <= ret_16_fu_792_p3(13 downto 13);
    tmp_16_fu_1070_p3 <= grp_fu_1704_p2(23 downto 23);
    tmp_1_fu_268_p3 <= in1(14 downto 14);
    tmp_20_fu_1198_p3 <= opt1_V_11_fu_1114_p3(23 downto 23);
    tmp_21_fu_1212_p3 <= res_14_fu_1172_p3(7 downto 7);
    tmp_23_fu_1325_p4 <= opt1_V_11_fu_1114_p3(23 downto 12);
    tmp_26_fu_1370_p3 <= opt1_V_12_fu_1350_p3(12 downto 12);
    tmp_28_fu_1410_p3 <= opt1_V_12_fu_1350_p3(19 downto 19);
    tmp_40_fu_1670_p3 <= opt1_V_12_fu_1350_p3(11 downto 11);
    tmp_5_fu_448_p3 <= (trunc_ln312_fu_444_p1 & p_Result_2_fu_212_p3);
    tmp_6_fu_430_p3 <= ret_6_fu_422_p3(13 downto 13);
    tmp_7_fu_818_p3 <= (trunc_ln312_1_fu_814_p1 & p_Result_9_fu_582_p3);
    tmp_9_fu_638_p3 <= in2(14 downto 14);
    tmp_fu_1044_p3 <= grp_fu_1704_p2(25 downto 25);
    top_is_leading_V_1_fu_808_p2 <= (tmp_13_fu_800_p3 xor ap_const_lv1_1);
    top_is_leading_V_fu_438_p2 <= (tmp_6_fu_430_p3 xor ap_const_lv1_1);
    trunc_ln312_1_fu_814_p1 <= ret_16_fu_792_p3(12 - 1 downto 0);
    trunc_ln312_fu_444_p1 <= ret_6_fu_422_p3(12 - 1 downto 0);
    trunc_ln422_1_fu_826_p1 <= ret_16_fu_792_p3(13 - 1 downto 0);
    trunc_ln422_fu_456_p1 <= ret_6_fu_422_p3(13 - 1 downto 0);
    unroundedResult_V_fu_1592_p4 <= lshr_ln978_fu_1562_p2(18 downto 4);
    upper_V_1_fu_342_p4 <= ret_4_fu_334_p3(13 downto 10);
    upper_V_3_fu_668_p4 <= ret_13_fu_662_p2(13 downto 6);
    upper_V_4_fu_712_p4 <= ret_14_fu_704_p3(13 downto 10);
    upper_V_fu_298_p4 <= ret_3_fu_292_p2(13 downto 6);
    val_V_100_fu_1538_p2 <= "0" when (shifted_out_V_fu_1534_p1 = ap_const_lv12_0) else "1";
    val_V_91_fu_220_p1 <= in1(14 - 1 downto 0);
    val_V_92_fu_224_p2 <= "0" when (val_V_91_fu_220_p1 = ap_const_lv14_0) else "1";
    val_V_93_fu_386_p4 <= ret_5_fu_378_p3(13 downto 12);
    val_V_94_fu_480_p2 <= "1" when (p_Result_6_fu_468_p5 = ap_const_lv4_F) else "0";
    val_V_95_fu_590_p1 <= in2(14 - 1 downto 0);
    val_V_96_fu_594_p2 <= "0" when (val_V_95_fu_590_p1 = ap_const_lv14_0) else "1";
    val_V_97_fu_850_p2 <= "1" when (p_Result_13_fu_838_p5 = ap_const_lv4_F) else "0";
    val_V_98_fu_1192_p2 <= "0" when (p_what2_s_fu_1188_p1 = ap_const_lv11_0) else "1";
    val_V_99_fu_1321_p1 <= res_14_fu_1172_p3(7 - 1 downto 0);
    val_V_fu_756_p4 <= ret_15_fu_748_p3(13 downto 12);
    xor_ln1527_1_fu_626_p2 <= (ext_1_fu_618_p3 xor ap_const_lv1_1);
    xor_ln1527_fu_256_p2 <= (ext_fu_248_p3 xor ap_const_lv1_1);
    xor_ln939_3_fu_878_p2 <= (tmp_9_fu_638_p3 xor ext_1_fu_618_p3);
    xor_ln939_fu_508_p2 <= (tmp_1_fu_268_p3 xor ext_fu_248_p3);
    zext_ln217_1_fu_870_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_13_fu_856_p3),5));
    zext_ln217_2_fu_1146_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_23_fu_1064_p2),2));
    zext_ln217_3_fu_1636_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_34_fu_1630_p2),15));
    zext_ln217_4_fu_1162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln217_1_fu_1156_p2),8));
    zext_ln217_5_fu_1252_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln217_fu_1248_p1),8));
    zext_ln217_6_fu_1317_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_15_fu_1309_p3),23));
    zext_ln217_fu_500_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_12_fu_486_p3),5));
    zext_ln306_fu_1142_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_25_fu_1083_p2),2));
    zext_ln978_1_fu_1558_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shift_low_V_fu_1502_p1),22));
    zext_ln978_fu_1514_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_30_fu_1506_p3),40));
end behav;
