-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity posit_comp_add is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in1 : IN STD_LOGIC_VECTOR (31 downto 0);
    in2 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of posit_comp_add is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "posit_comp_add_posit_comp_add,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=5000.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=47.115264,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=2339,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv30_3FFFFFFF : STD_LOGIC_VECTOR (29 downto 0) := "111111111111111111111111111111";
    constant ap_const_lv29_1FFFFFFF : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111111111111111111";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_ready : STD_LOGIC;
    signal add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_in1 : STD_LOGIC_VECTOR (37 downto 0);
    signal add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_in2 : STD_LOGIC_VECTOR (37 downto 0);
    signal add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_return : STD_LOGIC_VECTOR (39 downto 0);
    signal val_V_84_fu_202_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal val_V_85_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_fu_194_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_186_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ext_fu_230_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1527_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_250_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_fu_258_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_3_fu_274_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal upper_V_fu_280_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal lower_V_fu_290_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln359_1_fu_300_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal comp_V_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_3_fu_308_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_4_fu_316_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal upper_V_1_fu_324_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lower_V_1_fu_334_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln359_2_fu_344_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal comp_V_1_fu_338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_4_fu_352_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_5_fu_360_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal upper_V_2_fu_368_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal lower_V_2_fu_378_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal select_ln359_3_fu_388_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal comp_V_2_fu_382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_5_fu_396_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_6_fu_404_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal val_V_86_fu_412_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lower_V_3_fu_422_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln359_4_fu_432_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal comp_V_3_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_6_fu_440_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_7_fu_448_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_7_fu_456_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln312_fu_470_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal trunc_ln422_fu_482_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_6_fu_474_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal top_is_leading_V_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_7_fu_494_p6 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_V_87_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal opt1_V_4_fu_486_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln356_fu_266_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal res_fu_514_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_8_fu_522_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal xor_ln939_fu_536_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_fu_542_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln217_fu_528_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln359_5_fu_548_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal es_V_fu_562_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln359_6_fu_572_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_1_fu_224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_9_fu_556_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ret_10_fu_580_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_2_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fraction_V_fu_532_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal val_V_88_fu_619_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal val_V_89_fu_623_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_10_fu_611_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_11_fu_629_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_fu_603_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_2_fu_635_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ext_1_fu_647_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1527_1_fu_655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_667_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln359_7_fu_675_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_14_fu_691_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal upper_V_4_fu_697_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal lower_V_4_fu_707_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln359_8_fu_717_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal comp_V_4_fu_711_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_11_fu_725_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_15_fu_733_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal upper_V_5_fu_741_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lower_V_5_fu_751_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln359_9_fu_761_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal comp_V_5_fu_755_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_12_fu_769_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_16_fu_777_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal upper_V_6_fu_785_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal lower_V_6_fu_795_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal select_ln359_10_fu_805_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal comp_V_6_fu_799_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_13_fu_813_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_17_fu_821_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal val_V_fu_829_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lower_V_7_fu_839_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln359_11_fu_849_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal comp_V_7_fu_843_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_14_fu_857_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_18_fu_865_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_15_fu_873_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln312_1_fu_887_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal trunc_ln422_1_fu_899_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_8_fu_891_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal top_is_leading_V_1_fu_881_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_15_fu_911_p6 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_V_90_fu_925_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal opt1_V_5_fu_903_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln356_1_fu_683_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal res_2_fu_931_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_19_fu_939_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal xor_ln939_3_fu_953_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_3_fu_959_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln217_1_fu_945_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln359_12_fu_965_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal es_V_1_fu_979_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln359_13_fu_989_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_12_fu_641_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_20_fu_973_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ret_21_fu_997_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ret_13_fu_661_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fraction_V_1_fu_949_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_fu_1032_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal es_wo_xor_V_fu_1048_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln359_14_fu_1040_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_fu_1072_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_23_fu_1080_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal low_k_V_fu_1094_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Result_18_fu_1064_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_4_fu_1104_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal res_3_fu_1086_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_20_fu_1126_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_22_fu_1058_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal significand_V_fu_1028_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_19_fu_1118_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_21_fu_1134_p7 : STD_LOGIC_VECTOR (56 downto 0);
    signal opt1_V_fu_1110_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shift_high_V_fu_1154_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_22_fu_1164_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln312_fu_1150_p1 : STD_LOGIC_VECTOR (79 downto 0);
    signal zext_ln978_fu_1172_p1 : STD_LOGIC_VECTOR (79 downto 0);
    signal r_5_fu_1176_p2 : STD_LOGIC_VECTOR (79 downto 0);
    signal shifted_out_V_fu_1192_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal shifted_V_fu_1182_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_23_fu_1202_p4 : STD_LOGIC_VECTOR (38 downto 0);
    signal shift_high_V_1_fu_1216_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_24_fu_1230_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln312_1_fu_1212_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal zext_ln978_1_fu_1238_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal r_6_fu_1242_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal shifted_out_V_1_fu_1258_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shifted_V_3_fu_1248_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_V_92_fu_1226_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_25_fu_1268_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln978_2_fu_1278_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal r_7_fu_1282_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal val_V_93_fu_1262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_91_fu_1196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1528_fu_1292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shifted_out_V_3_fu_1288_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_27_fu_1330_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_28_fu_1322_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1528_2_fu_1338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_24_fu_1298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_26_fu_1304_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_25_fu_1344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_26_fu_1350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal unroundedResult_V_fu_1312_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln217_2_fu_1356_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal p_Result_17_fu_1020_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal roundedResult_V_fu_1360_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal p_Result_30_fu_1374_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_fu_1390_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1527_fu_1398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_27_fu_1404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_28_fu_1410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_fu_1382_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_29_fu_1366_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component posit_comp_add_posit_add_32u_2u_VivadoWrapper_s IS
    port (
        ap_ready : OUT STD_LOGIC;
        in1 : IN STD_LOGIC_VECTOR (37 downto 0);
        in2 : IN STD_LOGIC_VECTOR (37 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;



begin
    add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180 : component posit_comp_add_posit_add_32u_2u_VivadoWrapper_s
    port map (
        ap_ready => add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_ready,
        in1 => add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_in1,
        in2 => add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_in2,
        ap_return => add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_return);




    add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_in1 <= (((((ret_1_fu_224_p2 & ret_9_fu_556_p2) & ret_10_fu_580_p2) & p_Result_s_fu_186_p3) & ret_2_fu_244_p2) & fraction_V_fu_532_p1);
    add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_in2 <= (((((ret_12_fu_641_p2 & ret_20_fu_973_p2) & ret_21_fu_997_p2) & p_Result_9_fu_603_p3) & ret_13_fu_661_p2) & fraction_V_1_fu_949_p1);
    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_ready <= ap_start;
    ap_return <= 
        p_Result_31_fu_1382_p3 when (ret_28_fu_1410_p2(0) = '1') else 
        p_Result_29_fu_1366_p3;
    comp_V_1_fu_338_p2 <= "1" when (upper_V_1_fu_324_p4 = ap_const_lv8_0) else "0";
    comp_V_2_fu_382_p2 <= "1" when (upper_V_2_fu_368_p4 = ap_const_lv4_0) else "0";
    comp_V_3_fu_426_p2 <= "1" when (val_V_86_fu_412_p4 = ap_const_lv2_0) else "0";
    comp_V_4_fu_711_p2 <= "1" when (upper_V_4_fu_697_p4 = ap_const_lv16_0) else "0";
    comp_V_5_fu_755_p2 <= "1" when (upper_V_5_fu_741_p4 = ap_const_lv8_0) else "0";
    comp_V_6_fu_799_p2 <= "1" when (upper_V_6_fu_785_p4 = ap_const_lv4_0) else "0";
    comp_V_7_fu_843_p2 <= "1" when (val_V_fu_829_p4 = ap_const_lv2_0) else "0";
    comp_V_fu_294_p2 <= "1" when (upper_V_fu_280_p4 = ap_const_lv16_0) else "0";
    es_V_1_fu_979_p4 <= ret_19_fu_939_p2(28 downto 27);
    es_V_fu_562_p4 <= ret_8_fu_522_p2(28 downto 27);
    es_wo_xor_V_fu_1048_p4 <= add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_return(30 downto 29);
    ext_1_fu_647_p3 <= in2(31 downto 31);
    ext_fu_230_p3 <= in1(31 downto 31);
    fraction_V_1_fu_949_p1 <= ret_19_fu_939_p2(27 - 1 downto 0);
    fraction_V_fu_532_p1 <= ret_8_fu_522_p2(27 - 1 downto 0);
    low_k_V_fu_1094_p4 <= add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_return(35 downto 31);
    lower_V_1_fu_334_p1 <= ret_4_fu_316_p3(22 - 1 downto 0);
    lower_V_2_fu_378_p1 <= ret_5_fu_360_p3(26 - 1 downto 0);
    lower_V_3_fu_422_p1 <= ret_6_fu_404_p3(28 - 1 downto 0);
    lower_V_4_fu_707_p1 <= ret_14_fu_691_p2(14 - 1 downto 0);
    lower_V_5_fu_751_p1 <= ret_15_fu_733_p3(22 - 1 downto 0);
    lower_V_6_fu_795_p1 <= ret_16_fu_777_p3(26 - 1 downto 0);
    lower_V_7_fu_839_p1 <= ret_17_fu_821_p3(28 - 1 downto 0);
    lower_V_fu_290_p1 <= ret_3_fu_274_p2(14 - 1 downto 0);
    opt1_V_4_fu_486_p3 <= 
        trunc_ln422_fu_482_p1 when (tmp_7_fu_456_p3(0) = '1') else 
        tmp_6_fu_474_p3;
    opt1_V_5_fu_903_p3 <= 
        trunc_ln422_1_fu_899_p1 when (tmp_15_fu_873_p3(0) = '1') else 
        tmp_8_fu_891_p3;
    opt1_V_fu_1110_p3 <= 
        r_4_fu_1104_p2 when (p_Result_18_fu_1064_p3(0) = '1') else 
        low_k_V_fu_1094_p4;
    or_ln1527_fu_1398_p2 <= (tmp_fu_1032_p3 or tmp_32_fu_1390_p3);
    or_ln1528_2_fu_1338_p2 <= (p_Result_28_fu_1322_p3 or p_Result_27_fu_1330_p3);
    or_ln1528_fu_1292_p2 <= (val_V_93_fu_1262_p2 or val_V_91_fu_1196_p2);
    p_Result_10_fu_611_p3 <= in2(30 downto 30);
    p_Result_11_fu_725_p3 <= (lower_V_4_fu_707_p1 & select_ln359_8_fu_717_p3);
    p_Result_12_fu_769_p3 <= (lower_V_5_fu_751_p1 & select_ln359_9_fu_761_p3);
    p_Result_13_fu_813_p3 <= (lower_V_6_fu_795_p1 & select_ln359_10_fu_805_p3);
    p_Result_14_fu_857_p3 <= (lower_V_7_fu_839_p1 & select_ln359_11_fu_849_p3);
    p_Result_15_fu_911_p6 <= ((((comp_V_4_fu_711_p2 & comp_V_5_fu_755_p2) & comp_V_6_fu_799_p2) & comp_V_7_fu_843_p2) & top_is_leading_V_1_fu_881_p2);
    p_Result_17_fu_1020_p3 <= add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_return(28 downto 28);
    p_Result_18_fu_1064_p3 <= add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_return(36 downto 36);
    p_Result_19_fu_1118_p3 <= add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_return(39 downto 39);
    p_Result_20_fu_1126_p3 <= res_3_fu_1086_p3(1 downto 1);
    p_Result_21_fu_1134_p7 <= (((((p_Result_20_fu_1126_p3 & res_3_fu_1086_p3) & ret_22_fu_1058_p2) & significand_V_fu_1028_p1) & p_Result_19_fu_1118_p3) & ap_const_lv24_0);
    p_Result_22_fu_1164_p3 <= (shift_high_V_fu_1154_p4 & ap_const_lv3_0);
    p_Result_23_fu_1202_p4 <= ((p_Result_20_fu_1126_p3 & shifted_V_fu_1182_p4) & ap_const_lv6_0);
    p_Result_24_fu_1230_p3 <= (shift_high_V_1_fu_1216_p4 & ap_const_lv1_0);
    p_Result_25_fu_1268_p4 <= ((p_Result_20_fu_1126_p3 & shifted_V_3_fu_1248_p4) & ap_const_lv1_0);
    p_Result_26_fu_1304_p3 <= r_7_fu_1282_p2(1 downto 1);
    p_Result_27_fu_1330_p3 <= add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_return(38 downto 38);
    p_Result_28_fu_1322_p3 <= r_7_fu_1282_p2(2 downto 2);
    p_Result_29_fu_1366_p3 <= (p_Result_17_fu_1020_p3 & roundedResult_V_fu_1360_p2);
    p_Result_2_fu_194_p3 <= in1(30 downto 30);
    p_Result_30_fu_1374_p3 <= add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_return(37 downto 37);
    p_Result_31_fu_1382_p3 <= (p_Result_30_fu_1374_p3 & ap_const_lv31_0);
    p_Result_3_fu_308_p3 <= (lower_V_fu_290_p1 & select_ln359_1_fu_300_p3);
    p_Result_4_fu_352_p3 <= (lower_V_1_fu_334_p1 & select_ln359_2_fu_344_p3);
    p_Result_5_fu_396_p3 <= (lower_V_2_fu_378_p1 & select_ln359_3_fu_388_p3);
    p_Result_6_fu_440_p3 <= (lower_V_3_fu_422_p1 & select_ln359_4_fu_432_p3);
    p_Result_7_fu_494_p6 <= ((((comp_V_fu_294_p2 & comp_V_1_fu_338_p2) & comp_V_2_fu_382_p2) & comp_V_3_fu_426_p2) & top_is_leading_V_fu_464_p2);
    p_Result_9_fu_603_p3 <= in2(31 downto 31);
    p_Result_s_fu_186_p3 <= in1(31 downto 31);
    r_1_fu_542_p2 <= (xor_ln939_fu_536_p2 xor ap_const_lv1_1);
    r_2_fu_635_p2 <= (ret_11_fu_629_p2 xor ap_const_lv1_1);
    r_3_fu_959_p2 <= (xor_ln939_3_fu_953_p2 xor ap_const_lv1_1);
    r_4_fu_1104_p2 <= (low_k_V_fu_1094_p4 xor ap_const_lv5_1F);
    r_5_fu_1176_p2 <= std_logic_vector(shift_right(unsigned(sext_ln312_fu_1150_p1),to_integer(unsigned('0' & zext_ln978_fu_1172_p1(31-1 downto 0)))));
    r_6_fu_1242_p2 <= std_logic_vector(shift_right(unsigned(sext_ln312_1_fu_1212_p1),to_integer(unsigned('0' & zext_ln978_1_fu_1238_p1(31-1 downto 0)))));
    r_7_fu_1282_p2 <= std_logic_vector(shift_right(unsigned(p_Result_25_fu_1268_p4),to_integer(unsigned('0' & zext_ln978_2_fu_1278_p1(31-1 downto 0)))));
    r_fu_218_p2 <= (ret_fu_212_p2 xor ap_const_lv1_1);
    res_2_fu_931_p3 <= 
        ap_const_lv5_1E when (val_V_90_fu_925_p2(0) = '1') else 
        p_Result_15_fu_911_p6;
    res_3_fu_1086_p3 <= 
        ap_const_lv2_1 when (ret_23_fu_1080_p2(0) = '1') else 
        ap_const_lv2_2;
    res_fu_514_p3 <= 
        ap_const_lv5_1E when (val_V_87_fu_508_p2(0) = '1') else 
        p_Result_7_fu_494_p6;
    ret_10_fu_580_p2 <= (select_ln359_6_fu_572_p3 xor es_V_fu_562_p4);
    ret_11_fu_629_p2 <= (val_V_89_fu_623_p2 or p_Result_10_fu_611_p3);
    ret_12_fu_641_p2 <= (r_2_fu_635_p2 and p_Result_9_fu_603_p3);
    ret_13_fu_661_p2 <= (xor_ln1527_1_fu_655_p2 and ret_11_fu_629_p2);
    ret_14_fu_691_p2 <= (val_V_88_fu_619_p1 xor select_ln359_7_fu_675_p3);
    ret_15_fu_733_p3 <= 
        p_Result_11_fu_725_p3 when (comp_V_4_fu_711_p2(0) = '1') else 
        ret_14_fu_691_p2;
    ret_16_fu_777_p3 <= 
        p_Result_12_fu_769_p3 when (comp_V_5_fu_755_p2(0) = '1') else 
        ret_15_fu_733_p3;
    ret_17_fu_821_p3 <= 
        p_Result_13_fu_813_p3 when (comp_V_6_fu_799_p2(0) = '1') else 
        ret_16_fu_777_p3;
    ret_18_fu_865_p3 <= 
        p_Result_14_fu_857_p3 when (comp_V_7_fu_843_p2(0) = '1') else 
        ret_17_fu_821_p3;
    ret_19_fu_939_p2 <= (select_ln356_1_fu_683_p3 xor opt1_V_5_fu_903_p3);
    ret_1_fu_224_p2 <= (r_fu_218_p2 and p_Result_s_fu_186_p3);
    ret_20_fu_973_p2 <= (zext_ln217_1_fu_945_p1 xor select_ln359_12_fu_965_p3);
    ret_21_fu_997_p2 <= (select_ln359_13_fu_989_p3 xor es_V_1_fu_979_p4);
    ret_22_fu_1058_p2 <= (select_ln359_14_fu_1040_p3 xor es_wo_xor_V_fu_1048_p4);
    ret_23_fu_1080_p2 <= (tmp_fu_1032_p3 xor tmp_18_fu_1072_p3);
    ret_24_fu_1298_p2 <= (shifted_out_V_3_fu_1288_p1 or or_ln1528_fu_1292_p2);
    ret_25_fu_1344_p2 <= (ret_24_fu_1298_p2 or or_ln1528_2_fu_1338_p2);
    ret_26_fu_1350_p2 <= (ret_25_fu_1344_p2 and p_Result_26_fu_1304_p3);
    ret_27_fu_1404_p2 <= (or_ln1527_fu_1398_p2 xor ap_const_lv1_1);
    ret_28_fu_1410_p2 <= (ret_27_fu_1404_p2 or p_Result_30_fu_1374_p3);
    ret_2_fu_244_p2 <= (xor_ln1527_fu_238_p2 and ret_fu_212_p2);
    ret_3_fu_274_p2 <= (val_V_84_fu_202_p1 xor select_ln359_fu_258_p3);
    ret_4_fu_316_p3 <= 
        p_Result_3_fu_308_p3 when (comp_V_fu_294_p2(0) = '1') else 
        ret_3_fu_274_p2;
    ret_5_fu_360_p3 <= 
        p_Result_4_fu_352_p3 when (comp_V_1_fu_338_p2(0) = '1') else 
        ret_4_fu_316_p3;
    ret_6_fu_404_p3 <= 
        p_Result_5_fu_396_p3 when (comp_V_2_fu_382_p2(0) = '1') else 
        ret_5_fu_360_p3;
    ret_7_fu_448_p3 <= 
        p_Result_6_fu_440_p3 when (comp_V_3_fu_426_p2(0) = '1') else 
        ret_6_fu_404_p3;
    ret_8_fu_522_p2 <= (select_ln356_fu_266_p3 xor opt1_V_4_fu_486_p3);
    ret_9_fu_556_p2 <= (zext_ln217_fu_528_p1 xor select_ln359_5_fu_548_p3);
    ret_fu_212_p2 <= (val_V_85_fu_206_p2 or p_Result_2_fu_194_p3);
    roundedResult_V_fu_1360_p2 <= std_logic_vector(unsigned(unroundedResult_V_fu_1312_p4) + unsigned(zext_ln217_2_fu_1356_p1));
    select_ln356_1_fu_683_p3 <= 
        ap_const_lv29_1FFFFFFF when (tmp_10_fu_667_p3(0) = '1') else 
        ap_const_lv29_0;
    select_ln356_fu_266_p3 <= 
        ap_const_lv29_1FFFFFFF when (tmp_1_fu_250_p3(0) = '1') else 
        ap_const_lv29_0;
    select_ln359_10_fu_805_p3 <= 
        ap_const_lv4_F when (tmp_10_fu_667_p3(0) = '1') else 
        ap_const_lv4_0;
    select_ln359_11_fu_849_p3 <= 
        ap_const_lv2_3 when (tmp_10_fu_667_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_12_fu_965_p3 <= 
        ap_const_lv6_3F when (r_3_fu_959_p2(0) = '1') else 
        ap_const_lv6_0;
    select_ln359_13_fu_989_p3 <= 
        ap_const_lv2_3 when (ext_1_fu_647_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_14_fu_1040_p3 <= 
        ap_const_lv2_3 when (tmp_fu_1032_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_1_fu_300_p3 <= 
        ap_const_lv16_FFFF when (tmp_1_fu_250_p3(0) = '1') else 
        ap_const_lv16_0;
    select_ln359_2_fu_344_p3 <= 
        ap_const_lv8_FF when (tmp_1_fu_250_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_3_fu_388_p3 <= 
        ap_const_lv4_F when (tmp_1_fu_250_p3(0) = '1') else 
        ap_const_lv4_0;
    select_ln359_4_fu_432_p3 <= 
        ap_const_lv2_3 when (tmp_1_fu_250_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_5_fu_548_p3 <= 
        ap_const_lv6_3F when (r_1_fu_542_p2(0) = '1') else 
        ap_const_lv6_0;
    select_ln359_6_fu_572_p3 <= 
        ap_const_lv2_3 when (ext_fu_230_p3(0) = '1') else 
        ap_const_lv2_0;
    select_ln359_7_fu_675_p3 <= 
        ap_const_lv30_3FFFFFFF when (tmp_10_fu_667_p3(0) = '1') else 
        ap_const_lv30_0;
    select_ln359_8_fu_717_p3 <= 
        ap_const_lv16_FFFF when (tmp_10_fu_667_p3(0) = '1') else 
        ap_const_lv16_0;
    select_ln359_9_fu_761_p3 <= 
        ap_const_lv8_FF when (tmp_10_fu_667_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln359_fu_258_p3 <= 
        ap_const_lv30_3FFFFFFF when (tmp_1_fu_250_p3(0) = '1') else 
        ap_const_lv30_0;
        sext_ln312_1_fu_1212_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_23_fu_1202_p4),44));

        sext_ln312_fu_1150_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_21_fu_1134_p7),80));

    shift_high_V_1_fu_1216_p4 <= opt1_V_fu_1110_p3(2 downto 1);
    shift_high_V_fu_1154_p4 <= opt1_V_fu_1110_p3(4 downto 3);
    shifted_V_3_fu_1248_p4 <= r_6_fu_1242_p2(37 downto 6);
    shifted_V_fu_1182_p4 <= r_5_fu_1176_p2(55 downto 24);
    shifted_out_V_1_fu_1258_p1 <= r_6_fu_1242_p2(6 - 1 downto 0);
    shifted_out_V_3_fu_1288_p1 <= r_7_fu_1282_p2(1 - 1 downto 0);
    shifted_out_V_fu_1192_p1 <= r_5_fu_1176_p2(24 - 1 downto 0);
    significand_V_fu_1028_p1 <= add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_return(27 - 1 downto 0);
    tmp_10_fu_667_p3 <= in2(30 downto 30);
    tmp_15_fu_873_p3 <= ret_18_fu_865_p3(29 downto 29);
    tmp_18_fu_1072_p3 <= add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_return(36 downto 36);
    tmp_1_fu_250_p3 <= in1(30 downto 30);
    tmp_32_fu_1390_p3 <= add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_return(27 downto 27);
    tmp_6_fu_474_p3 <= (trunc_ln312_fu_470_p1 & p_Result_2_fu_194_p3);
    tmp_7_fu_456_p3 <= ret_7_fu_448_p3(29 downto 29);
    tmp_8_fu_891_p3 <= (trunc_ln312_1_fu_887_p1 & p_Result_10_fu_611_p3);
    tmp_fu_1032_p3 <= add_V_posit_add_32u_2u_VivadoWrapper_s_fu_180_ap_return(28 downto 28);
    top_is_leading_V_1_fu_881_p2 <= (tmp_15_fu_873_p3 xor ap_const_lv1_1);
    top_is_leading_V_fu_464_p2 <= (tmp_7_fu_456_p3 xor ap_const_lv1_1);
    trunc_ln312_1_fu_887_p1 <= ret_18_fu_865_p3(28 - 1 downto 0);
    trunc_ln312_fu_470_p1 <= ret_7_fu_448_p3(28 - 1 downto 0);
    trunc_ln422_1_fu_899_p1 <= ret_18_fu_865_p3(29 - 1 downto 0);
    trunc_ln422_fu_482_p1 <= ret_7_fu_448_p3(29 - 1 downto 0);
    unroundedResult_V_fu_1312_p4 <= r_7_fu_1282_p2(32 downto 2);
    upper_V_1_fu_324_p4 <= ret_4_fu_316_p3(29 downto 22);
    upper_V_2_fu_368_p4 <= ret_5_fu_360_p3(29 downto 26);
    upper_V_4_fu_697_p4 <= ret_14_fu_691_p2(29 downto 14);
    upper_V_5_fu_741_p4 <= ret_15_fu_733_p3(29 downto 22);
    upper_V_6_fu_785_p4 <= ret_16_fu_777_p3(29 downto 26);
    upper_V_fu_280_p4 <= ret_3_fu_274_p2(29 downto 14);
    val_V_84_fu_202_p1 <= in1(30 - 1 downto 0);
    val_V_85_fu_206_p2 <= "0" when (val_V_84_fu_202_p1 = ap_const_lv30_0) else "1";
    val_V_86_fu_412_p4 <= ret_6_fu_404_p3(29 downto 28);
    val_V_87_fu_508_p2 <= "1" when (p_Result_7_fu_494_p6 = ap_const_lv5_1F) else "0";
    val_V_88_fu_619_p1 <= in2(30 - 1 downto 0);
    val_V_89_fu_623_p2 <= "0" when (val_V_88_fu_619_p1 = ap_const_lv30_0) else "1";
    val_V_90_fu_925_p2 <= "1" when (p_Result_15_fu_911_p6 = ap_const_lv5_1F) else "0";
    val_V_91_fu_1196_p2 <= "0" when (shifted_out_V_fu_1192_p1 = ap_const_lv24_0) else "1";
    val_V_92_fu_1226_p1 <= opt1_V_fu_1110_p3(1 - 1 downto 0);
    val_V_93_fu_1262_p2 <= "0" when (shifted_out_V_1_fu_1258_p1 = ap_const_lv6_0) else "1";
    val_V_fu_829_p4 <= ret_17_fu_821_p3(29 downto 28);
    xor_ln1527_1_fu_655_p2 <= (ext_1_fu_647_p3 xor ap_const_lv1_1);
    xor_ln1527_fu_238_p2 <= (ext_fu_230_p3 xor ap_const_lv1_1);
    xor_ln939_3_fu_953_p2 <= (tmp_10_fu_667_p3 xor ext_1_fu_647_p3);
    xor_ln939_fu_536_p2 <= (tmp_1_fu_250_p3 xor ext_fu_230_p3);
    zext_ln217_1_fu_945_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_2_fu_931_p3),6));
    zext_ln217_2_fu_1356_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_26_fu_1350_p2),31));
    zext_ln217_fu_528_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_fu_514_p3),6));
    zext_ln978_1_fu_1238_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_24_fu_1230_p3),44));
    zext_ln978_2_fu_1278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val_V_92_fu_1226_p1),34));
    zext_ln978_fu_1172_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_22_fu_1164_p3),80));
end behav;
